### ISSUE TITLE
Possibility of data leakage with `loo` on multiple imputed datasets

### ISSUE THREAD

**Issue by al-obrien** [paul-buerkner/brms#1010]
With `brm_multiple()` we can fit datasets that had their missing values imputed via MICE. Model selection is typically the next step and I am **wondering if using `brms::loo()` would suffer from data leakage**. 

I believe the normal workflow is for any training set to be fit separately, imputation included, from the testing (i.e holdout) set during every fold of cross validation. Information may leak between the sets if the imputation model used the entire dataset initially prior to CV. I suspect `waic()` may be preferred in these circumstances if the imputation model cannot be part of the cross validation process. 

The MICE package is currently in the process of adding a way to access the imputation model so that it can be used on testing sets separately: https://github.com/amices/mice/issues/32

I searched around and couldn't find any R related threads that seemed to raise this issue with `loo()` with imputed missing data so perhaps I am misunderstanding something with this implementation. Maybe this is a question for the `loo` page, but I thought I would start here.

**Comment by paul-buerkner** [comment]
I agree, there is a data leakage if the later left-out observations were initially used in the imputation process. However, I currently don't have a good suggestion how to fix that from the brms side, as brms doesn't impute data sets itself but rather uses a list of data sets imputed with another package such as MICE.

**Comment by al-obrien** [comment]
I wanted to point out that, just recently, the MICE package implemented a way to retrieve the imputation model (many thanks to @prockenschaub: https://github.com/amices/mice/issues/32#issuecomment-716141128 and [example](https://github.com/prockenschaub/Misc/blob/master/R/mice.reuse/mice.reuse_example.md)). As such, this will allow one to use the same imputation model on split datasets for training/testing. However, similar to your prior comment, I am also not sure how/if this new feature in MICE can interface with `loo` and `brms` to avoid data leakage.

**Comment by prockenschaub** [comment]
Happy to get involved in the discussion as to how the new `mice` functionality may be integrated into `loo` and `brms` (if possible and sensible). 

The new functionality enables a `mids` object to be trained on only a subset of the data contained within it but for imputations to be made on the entire dataset (thus avoiding data leakage). As one option that comes to mind, `brms` and `loo` could allow the user to pass an untrained `mids` object (i.e. a `mids` object with `maxit=0` in order to define `methods`, `predictorMatrix`, `blocks`, etc.). `brms`/`loo` could then run `mice.mids` N times, always leaving out one observation. Imputation would therefore occur within `brms` which may or may not be wanted. `brms`/`loo` would also need to reinialize the first set of "imputations" for each leave-one-out-imputation, which is usually chosen during initialization of the `mids` object based on random draws from the columns.

The limiting factor is likely computation time, since multiple imputation can already be time intensive even for medium size datasets and instead of once this process would now be run N times. However, data leakage in a leave-one-out setting is probably most problematic in small datasets, for which it might still be feasible to do this, and the entire process should also be trivially parallelisable.

**Comment by paul-buerkner** [comment]
Closing this issue for now to reduce the load of the issue tracker. If someone has time and wants to work on this, feel free to write here and I am happy to reopen.
