### ISSUE TITLE
Priors: Impose bounds on more classes

### ISSUE THREAD

**Issue by hsbadr** [paul-buerkner/brms#1094]
Currently, upper and lower bounds are only allowed for classes `"b"`. In many cases, with strong priors on the ranges, imposing bounds significantly reduces the computation time.

https://github.com/paul-buerkner/brms/blob/e45f64e8e73b87605d7bf39e1eac2b171818fe48/R/priors.R#L19-L22

Moreover, it isn't allowed to impose bounds with QR decomposition.
https://github.com/paul-buerkner/brms/blob/5eca085ec227cf65b5002d719501525f483c2bb9/R/stan-predictor.R#L335

**Comment by paul-buerkner** [comment]
I agree. The prior bounds framework needs to be reworked and made more flexible.

**Comment by drjhw** [comment]
I have the same problem - my model only converges if I set both the 'lb' and 'ub' arguments using set_prior. I need these bounds to constrain the intercept for the half-time in a non-linear model (similar to SSlogis, in package nlme)  to sensible (positive) values. But, setting these bounds for the intercept then prevents the model from estimating coefficients for the variables of interest, because these covariates can lengthen or shorten the half-time. 
I've been hoping to perform these analyses for more than a decade. So, I was excited to find that brms could estimate the basic model, with no covariates - but then frustrated to find that I could not relax the bounds to estimate the covariate effects.

**Comment by DoktorMike** [comment]
I also would love this feature, but currently you can still do it if you use nonlinear formulas instead which forces you to set priors for all of your parameters. It's very flexible but also quite verbose.

**Comment by paul-buerkner** [comment]
Closed via #1324

**Comment by lnalborczyk** [comment]
Hi Paul,

I am echoing the remark of @mpirikL above, it does not seem possible to specify a prior with a lower bound on a specific beta parameter. For instance, `prior(normal(0, 1), class = b, coef = "x", lb = 0)` gives the following error: `Error: Argument 'coef' may not be specified when using boundaries`.

Do you know whether there is a way to get around this issue?

Thank you!

Ladislas

**Comment by paul-buerkner** [comment]
use brms non linear syntax to define two separate linear predictors to
specify different bounds.

Ladislas Nalborczyk ***@***.***> schrieb am Fr., 11. Nov.
2022, 15:06:

**Comment by lnalborczyk** [comment]
Perfect, thanks!

**Comment by mschubert** [comment]
For reference, an example to

> use brms non linear syntax to define two separate linear predictors to specify different bounds

is here: https://github.com/paul-buerkner/brms/issues/1422#issuecomment-1298235977

**Comment by herryATcsiro** [comment]
except non-linear syntax doesn't work with missing values, so imposing lb and ub on coef is not possible with mi(). So hopefully this will become possible in the future ;-)
