### ISSUE TITLE
disambiguate correlation parameter names in the posterior

### ISSUE THREAD

**Issue by schmettow** [paul-buerkner/brms#118]
in the raw posterior distribution, correlation coefficients are currently named:
cor_correlate1_correlate2

Problem:

Correlates themselves have two (ranef, fixef) or three (nonlin) components that are separated by underscores. When reporting correlation coefficients, users may want to split the variable name into the two correlates names, using dplyr::separate() or stringr::str_detect(). The ambiguity of the separator makes this rather unpractical.

Possible solution: 

Use an unambiguous term. This may also not be ":", as this is reserved for interaction effects. The following could work, as "[]" is used for random effects entities, which should never appear as part of a correlation.

cor_[correlate1]_[correlate2]

Background:

Currently, I am working on a package for Bayesian reporting (github:schmettow/bayr). The package stores posterior distribution by long form (one row per draw, not per iteration). This makes  it possible to  extract components of a variable and classify them as:

iter | nonlin | fixef |re_factor | re_entity| value

Currently, variable components are extracted from parameter names using regular expressions, which is much easier with a consistent and syntactically unambiguous naming scheme. 

In general, the underscore deems problematic under this perspective, as many users routinely use it in variable names.

**Comment by paul-buerkner** [comment]
You are right. That is indeed a problem. As of **brms** 1.0.0, the new names of correlations are `cor_group_nlpar1_coef1_nlpar2_coef2`, so group effectively occurs only once. This of course doesn't solve your problem, but I just want to make sure we are one the same page. 

I think we have two options to make names unambigous:

1. Do as you suggested and use, for instance, `cor_group_[nlpar1_coef1]_[nlpar2_coef2]`. This would be unambigoues since non-linear parameters are not allowed to have underscores. However, it comes with the problem that the parameter names are not valid R variable names anymore. Of course, we have the same problem for group-level effects (e.g. `r_group[1,Intercept]`), but these parameters are less frequently accessed by users. 

2. Remove / replace underscores in `group` and `coef`. I do this a lot for special characters. For instance, when a predictor is named `I(x^2)`, I replace the brackets and the `^` to make sure we have valid R variable names in the end. I could do this too with underscores and as far as I understand, this would make names unambigoues. 

What do you think?

Whatever we choose, I will have to implement it until tomorrow morning, since I need to release **brms** 1.0.0 before the weekend. Of course, we can change parameter names in a later version, but this will definitly break backwards compatibility and a major release is the best opportunity to get it in.

**Comment by schmettow** [comment]
A double underscore between correlates would solve the problem, I guess.
Much success with the release! brms is awesome!

**Comment by paul-buerkner** [comment]
I am not entirely sure. We could split both correlates, yes (double underscores are prohibted in variable names in **brms**), but how do we split `group` and the correlates, if `group` also contains underscores?

**Comment by paul-buerkner** [comment]
Ok, something like `cor_group__nlpar1_coef1__nlpar2_coef2` and `sd_group__nlpar_coef` should work. If you are ok with it, too, I go ahead and put it in today.

**Comment by schmettow** [comment]
It works. Many thanks!

D <- dplyr::data_frame(parameter = c("cor_Part__maxp_Intercept__pexp_Intercept",
                              "cor_Part__SM__VSA"))

D %>% 
  tidyr::extract(parameter,
                 "^cor_(.+)__(.+)__(.+)$",
                 into = c("re_factor","corr1","corr2")) %>% 
  tidyr::separate(corr1, into = c("nonlin1", "fixef1"), fill = "left") %>% 
  tidyr::separate(corr2, into = c("nonlin2", "fixef2"), fill = `"left")

**Comment by paul-buerkner** [comment]
I reopen this issue since I haven't implemented it yet ;-)

**Comment by paul-buerkner** [comment]
Ok, the new names are implemented. The logic is as follows: Whenever a variable name (i.e. name of a grouping factor or predictor variable) appears within a parameter name, it is followed by two underscores, unless it stands at the end of a string or it is followed by another unique pattern (such as `[`).

In addition to changing sds and cors in the described way, this also changes the names of the `r` parameters: `r_group_nlpar[1, coef]` becomes `r_group__nlpar[1, coef]`. I know that this is not really required since `nlpar` can be identified in combination with `[`, but it is more consistent this way from my perspective.

Parameter names of old models are automatically renamed inside S3 methods so that we should not get problems with backwards compatibility.

Many thanks for your ideas and suggestions!

**Comment by schmettow** [comment]
can i send you a pizza?

**Comment by paul-buerkner** [comment]
I just had one ;-)

I think this change really makes sense. Going forward, I can split the parameter names myself using regular expressions, instead of having to rebuild them in order to avoid ambiguity.
