### ISSUE TITLE
Document the various additional response functions

### ISSUE THREAD

**Issue by jackobailey** [paul-buerkner/brms#1183]
brms now has a host of useful "Additional Response Information" functions that provide ways to account for various modelling quirks. But at present they aren't well documented and it is hard to know what some do. For example, if I search for "resp_dec brms" there is almost no information on what this function does. The same is true for other.

It would be good if someone could write a short vignette that explained them all.

**Comment by paul-buerkner** [comment]
Can you provide some feedback on which information on the addition terms in ?brmsformula is missing? I don't think a vignette on them would be needed at this point, but I do agree the documentation may be good to extend, if people can tell me what is missing currently.

**Comment by jackobailey** [comment]
True, perhaps extending the details section would be better. I think the information that is missing is just what each of them does. Sometimes (like resp_weights) it's obvious. Other times (like resp_vint and resp_vreal) I have no idea, can find no information, but expect it is something to do with the underlying Stan code based on existing knowledge of Stan. I assume many users will have no knowledge of Stan, so it might be worth explaining.

**Comment by wpetry** [comment]
I agree there is room for improvement, but to me the bigger issue is finding the documentation rather than its current detail/quality. Maybe this is true for @jackobailey too? There seems to be some mismatch in the thread about information presented in the `addition-terms` (=where I expected to find it) vs. `brmsformula` (=where I found it) help pages.

I think there are really good reasons to describe each of the 'aterms' as-is alongside the rest of the formula documentation. But it does make it more challenging for users to find the information. I suggest three changes that could help:

### On the `addition-terms` help page itself:
1) More clearly flag the help page as a placeholder. Most users will be looking for the desctiptions of each 'aterm' type when they first encounter this page. Since that information is located elsewhere, it would be helpful to acknowledge this early on the page and in multiple sections. As currently written, it's presented at the very end of the Details section. Consider adding a note to the Description section and reversing the presentation in the Details section such that [where to find full docs] comes before [justification for not having them on `addition-terms`, as might have been expected]).
2) When pointing users to `brmsformula` > Details, include the subsection name where the information is presented ("Additional response information"). Knowing exactly what to look for would make it easier to navigate the _massive_ Details section on the`brmsformula` help page.

### On the backend:
3) Add aliases for each of the `resp_*` functions. I think most users will rarely (if ever) encounter the `resp_*` prefixed form of these functions. Being able to directly search using `?*` would help avoid the additional steps/confusion in finding information on these incredibly versatile constructors.

As always, kudos @paul-buerkner for this remarkable package.

**Comment by paul-buerkner** [comment]
I have now improved the doc specifically by adding pointers more visibly and improving the searchability of terms.
