### ISSUE TITLE
Question regarding stan model

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#12]
I'm trying to see if I can speed up my runs. They take up to many days for larger 3 or 4 level models. 

I was reading on the stan manual that when it comes to picking row m of matrix M, it's much more efficient to use an array of row_vectors (page 40). I see that you use this technique in defining the data, but it seems like it's not used in parameters. For example, in parameters block, I have:

>matrix[N_1,K_1] pre_1 

wouldn't it be better to do something like:

>row_vector[K_1] pre_1[N_1]

as later you do:

>for (i in 1:N_1) { 
>    r_1[i] <- sd_1 .* (to_vector(pre_1[i]));  # scale REs 
>  }

Is there a reason for using matrix for pre_1, etc?

**Comment by paul-buerkner** [comment]
The reason is that I can use `to_vector(pre_1) ~ normal(0,1)` in the `model` block when defining pre_1 as a matrix, which should simplify the gradient calculation of Stan. Doing the same thing with an array of vectors is not possible, if I am not mistaken, so that you had to write something like

```
for (i in 1:N_1) {
  pre_1[i] ~ normal(0,1);
}
```

From what I know about the NUTS sampler is that the gradient calculation is the bottleneck having a huge impact on the sampling speed. As a result I try to optimize the "sampling" statements sometimes at the expense of other parts of the code, as in the case you describe, while keeping the code simple at the same time. It may still be that the array formulation is faster for your models when coded appropriately.

If I remember your models correctly, you had something like

```
brm(formula = y ~ x1 + x2 + x3 +
    (1 | cat:subcat) + (x1 + x2 + x3 || cat),
    data = df,
    family = "gaussian")
````
You can try writing `(1|cat) + (0+x1|cat) + (0+x2|cat) + (0+x3|cat)` instead of  `(x1 + x2 + x3 || cat)` assuming that `x1, x2, x3` are continuous predictors.
Of course, both models are equivalent but they currently lead to slightly different Stan code in brms. I didn't have time to thoroughly test the speed of both implementations for a variety of larger models (that is why both implementations still coexist), but I think that the `(1|cat) ... ` version leads to faster sampling.

**Comment by alireza202** [comment]
Thanks for your answer. Is there a function in the package that converts R formula to Stan code?

**Comment by alireza202** [comment]
The Stan model does look different, as now it's all vectors, instead of matrices. I'll let you know about the speed comparison (for 1 example).

**Comment by alireza202** [comment]
For one example, it took 7 minutes with the new formula, versus 13 minutes for the old one. Sample of one, but it looks faster.

**Comment by paul-buerkner** [comment]
Thanks for testing! I also get comparable results for some of my smaller models.

The ``make_stancode`` function and its subfunctions  generate the Stan code. You can take a look at their code under R/stan.R here on github. 

Unfortunately, it is not just converting the formula into Stan code. In R, the same formula can imply completely different models depending on the class of the data  (factor or not). That is, a model such as ``y ~ x`` will have a fixed effects design matrix with two columns (intercept and x) if ``x`` is a continuous predictor. But it will certainly have z columns if ``x`` is a factor with z levels (intercept and z-1 columns for the factor). So to know how a random term ``(x || cat)`` really looks like, we have to know the data for x.

I will run further tests and if they come to the same result, I will change the implementation to consistently use vectors instead of matrices when random effects correlations are not modeled.

**Comment by paul-buerkner** [comment]
I finally found the time to test this thoroughly, and indeed the vector formulation is consistently faster. Thus, `(random || group)` terms are now translated into Stan code that avoids row indexing of matrices.
