### ISSUE TITLE
brm told me to inform you about parameter b

### ISSUE THREAD

**Issue by waynefoltaERI** [paul-buerkner/brms#129]
I ran the following model:

```
brm (y ~ 1, data=X, family=cumulative ())
```

Where `y` is an ordered factor. Not sure if it's a good idea -- I'm thinking it's the "null model" -- but after it ran, I had the warning:

```
Parameter b could not be renamed. This should not happen.
Please inform me so I can fix this problem
```

And so you have been informed. :-)

Looking at the `print` of the model doesn't have anything crazy in it, so without the message I would not have suspected anything, and perhaps the warning is in error.

**Comment by paul-buerkner** [comment]
Thanks for reporting this. What happens is that **brms** is trying to rename the parameter `b` that doesn't exist because there are no fixed effects in the model. It doesn't do harm in this case, but it would do if an actually existing parameter could not be renamed appropriately (thus the warning message). I believe that I already fixed this particular problem in the dev version of **brms** (I stumbled upon it myself about a week ago) as I don't get the warning anymore.

**Comment by rtaph** [comment]
Hi Paul,

FYI, I also got this message today, running version  1.1.0 downloaded on 2016-10-11 from CRAN. In my case, it did seem to cause some problems when I then tried to call `LOO` and `WAIC` on the object.

I was calling `update` on a brms.fit object, with an added predictor that had hyphens in the levels. 

```r
# this code trips up
b5 <- update(b4, .~. + owner + registeredmit,
          newdata = df, 
          seed = session_seed, 
          cores = 3, chains = 3)
```
I sanitized the factor levels to character-only, and re-ran the command, but it still does not work. It manages to save a model to `b5`, but this model has no fixed coefficients, only random ones (previously specified in `b4`).

I switched tactics to specify the full model from `brm` instead of `update`, which worked.

```r
# this worked fine
b5 <- brm(left | cens(code, right) ~ 1 + (1 | level1) + 
          (1 | level1:level2) + (1 | level1:level2:level3) + 
          owner + registeredmit,
          data = df, 
          prior = prior,
          seed = session_seed, 
          cores = 3, chains = 3,
          family = lognormal())
```

Current dev version on github is 1.1.0.9000, but since my installed release is only a few days old, I imagine maybe the bug is still lingering?

**Comment by paul-buerkner** [comment]
That's weired. Did the original model contain no fixed effects? In this case, `update.brmsfit` should recognize this and demand a recompilation since the fixed effects were not part of the **Stan** code of the original model.

**Comment by rtaph** [comment]
Correct-- the model that `update` was being called on did not have any fixed parameters, only random ones. I don't remember the exact details (I've changed my script around) but, if it makes a difference, it was also the fourth `update` call (i.e. update on and updated model).

I would share a reproducible example if I could but it's a heavy chain of analysis that isn't fully shareable.

**Comment by paul-buerkner** [comment]
I think I don't need a reproducable example here and will try to fix this tonight.

**Comment by paul-buerkner** [comment]
The `update` method should now find the discussed patterns and recompile the model. Thanks for reporting this issue!
