### ISSUE TITLE
Question regarding prediction of new factors in multilevel models

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#13]
Let's say I have such a model:
```
brm(formula = y ~ x1 + x2 + x3 +
                 (1 | cat:subcat) + (x1 + x2 + x3 || cat),
    data = df,
    family = "gaussian")
```
I know that the predict function does not support having new factors. But how can I get the best estimate for a new "subcat", given that it belongs to a given "cat"? I imagine since we already have estimated the posterior distribution for "cat:subcat" random variable, we should be able to use its mean value for a new "subcat".

**Comment by paul-buerkner** [comment]
Since all random effects are centered around zero, using the mean value of ``(1 | cat:subcat)`` basically implies ignoring it. Currently, it is possible to just ignore all random effects, but as far as I understand you, the ``(x1 + x2 + x3 || cat)`` term should be used in the prediction.

This implies that it should be possible to only ignore some random effects terms, while keeping others.

In addition, it would certainly be great to allow completely new levels of a grouping factor. Intuitively, the mean predicted value should be the same when ignoring a grouping factor and when using a new level. However, in the latter case, the variance of the predicted value should be higher, since we explicitly include the random effect (and thus its variance) instead of ignoring it.

If I have time, I will try to get something working during the weekend.

**Comment by paul-buerkner** [comment]
It should now be possible to ignore parts of the random effects in `predict` by specifying a one sided formula in the `re_formula` argument containing the random effects to be included.

For your example, the call to `predict` using newdata and ignoring the `(1|cat:subcat)` term may look like this:

```
predict(<your fitted model>, newdata = <new data>, re_formula = ~ (x1 + x2 + x3 || cat))
```

Currently, it is still necessary to include a `subcat` column in your new data even if it is not actually used in the prediction. Making this unnecessary, proved to be more difficult than I initially expected, but I hope to get it changed in the future.

**Comment by alireza202** [comment]
That's a great addition!

**Comment by paul-buerkner** [comment]
Update: Variables that are not actually used in the prediction should no longer be required in newdata.

**Comment by paul-buerkner** [comment]
It should now be possible to use new levels of random effects grouping factors in `newdata` by setting `allow_new_levels = TRUE`. In contrast to completely ignoring the random effect (an thus its variance) as done via `re_formula`, this will lead to estimates that take the random effects variance into account.
