### ISSUE TITLE
New warnings from latest Stan version

### ISSUE THREAD

**Issue by colinorourke** [paul-buerkner/brms#1301]
Hello, love brms, thanks for putting in all the effort writing and maintaining it. Just wanted to point out that when using the `cmdstanr` backend with the latest version of Stan on a model Stan produces the warning:

```
Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
```

I'm sure this is already on your RADAR, but just in case, it seems like Stan has changed its preference for how you declare arrays.

**Comment by rok-cesnovar** [comment]
Yeah, since 2.29 the old array syntax is deprecated. 

@paul-buerkner There is a quick "workaround" fix for this that would buy you a year to address this issue with a long-term solution. CmdStan 2.29 offers a preprocessor that fixes all the deprecated code that can be automatically fixed. The develop version of CmdStanR offers it via a `mod$format(canonicalize = TRUE)`, but it's just a few lines of code we can add in brms as well so that users don't need to install the development version of cmdstanr. Let me know what you prefer. Glad to help.

**Comment by paul-buerkner** [comment]
brms cannot update its Stan code base directly as long as the rstan version on CRAN does not support the new array syntax. Both option seem find to me. What would you think is most sensible?

**Comment by rok-cesnovar** [comment]
I would use the stanc3 canonicalizer to automatically transform the Stan models before compiling them with cmdstan (I can do this over the weekend or next week). 

This will not be useful after 2.32 as the canonicalizer will error (the old array syntax will no longer be supported). That should happen in about a year from now. In that time we either
a) hope rstan 2.26 hits CRAN (I am not as optimistic on that as I was before) and start using the new syntax everywhere
b) emit different code based on Stan version (this might be painful?)
