### ISSUE TITLE
Ordinal regression: proportional odds, non-proportional odds and partial

### ISSUE THREAD

**Issue by SFrav** [paul-buerkner/brms#133]
This is far from my area of expertise, but would an option for proportional odds, non-proportional odds and partial proportional odds be a good addition for the ordinal regression family of this package? As proposed in this paper: http://projecteuclid.org/euclid.ba/1422468421#supplemental

Their package source is in the supplementary material.

**Comment by paul-buerkner** [comment]
Propotional odds, as far as I understand, is just the `cumulative("logit")` family. As is written in the paper, non-propotional odds, or probably more generally called 'category specific effects', are problematic in cumulative models, since it might happen that model implied propabilities are negative, if you don't specifically adjust for it. However, in all other ordinal families `sratio`, `cratio` and `acat`, category specific effects can be modeled using the `cse` function inside the model formula in **brms**. Since both "standard" fixed effects and category specifc effects can be modeled at the same time, **brms** effectively also has the kind of "partial proportional odds" stuff, just not for the cumulative family, but for all other ordinal families.

**Comment by SFrav** [comment]
Followed-up by email.
