### ISSUE TITLE
speed up calls to `fitted()`?

### ISSUE THREAD

**Issue by JWiley** [paul-buerkner/brms#1334]
`brmsmargins` which I develop to calculate marginal effects off `brms` models relies heavily on repeated calls to `fitted()` for the same model varying the data.
Currently, these slow the overall run time down considerably. I had a look at the code for `fitted.brmsfit` which ends up quite complicated and beyond what I want to try to re-write overall. However, @paul-buerkner if there were particular parts of the methods used for `fitted()` and predictions that you know about that you've thought were slow and wanted re-written, I'd be happy to work on those. If you don't have any ideas for future feature of speeding up generating predictions & it's not a priority, can just close this issue.

**Comment by paul-buerkner** [comment]
Unfortunately, I see nothing major and general we can do from the brms side, but perhaps you could reduce the number of repeated calls to `fitted()`. That is, perhaps you could achieve with a single call to `fitted()` what you have previously achieved with multiple such calls. Because the parameter and data preparation part creates quite the overhead in repeated calling.
