### ISSUE TITLE
Add ability to assign a prior on the group standard deviation for fixed effects

### ISSUE THREAD

**Issue by ccolaneri** [paul-buerkner/brms#136]
I'm interested in modeling multiple categorical variables and assigning a prior on the group standard deviation, not just the individual term values.  In the language of fixed effects, is there a way to put a prior on the group standard deviation as you would with random effects?  Alternatively, is there a way to extract the individual random effect values and work with them directly after fitting as one would with fixed effects?  This type of model is relatively simple to define in STAN directly, and I'm wondering if it's possible to define such a model using brms.

**Comment by paul-buerkner** [comment]
I am afraid I am not exactly sure how the model you are referring to looks like. Can you show me some sample Stan code (or the relevant parts of the code) that implements such a model?

**Comment by ccolaneri** [comment]
Here is example Stan code for a 2-covariate model with priors on the group standard deviations:

data {
  int<lower=0> nObs;
  real<lower=0> y[nObs];
  int<lower=1> cov1[nObs];
  int<lower=1> cov2[nObs];
  int<lower=1> nCov1s;
  int<lower=1> nCov2s;
  real<lower=0> yMean; // data mean
  real<lower=0> ySD; // data SD
}

parameters {
  real intercept;
  vector[nCov1s] c1;
  vector[nCov2s] c2;
  real<lower=0> sigma;
  real<lower=0> c1Sigma;
  real<lower=0> c2Sigma;
}

transformed parameters {
  // corner constraint
  vector[nCov1s] c1_const;
  vector[nCov2s] c2_const;
  vector[nObs] theta;
  c1_const[1] = 0;
  c2_const[1] = 0;
  c1_const[2:nCov1s] = c1[2:nCov1s];
  c2_const[2:nCov2s] = c2[2:nCov2s];
  
  theta = intercept + c1_const[nCov1s] + c2_const[nCov2s];
}

model {
  c1Sigma ~ gamma(0.1, 0.1);
  c2Sigma ~ gamma(0.1, 0.1);
  c1 ~ normal(0, c1Sigma);
  c2 ~ normal(0, c2Sigma);
  intercept ~ normal(yMean, ySD);
  y ~ normal(theta, sigma);
}

**Comment by paul-buerkner** [comment]
To which extent does this model differ from a basic group-level (i.e. "random effects") model? On first glance it looks pretty much the same except for fixing the first value to zero. You can extract summary statistics of the group-level effects using the `ranef` method or extract the whole posterior samples using the `posterior_samples` method with argument `pars = "^r_"`.

**Comment by ccolaneri** [comment]
Yes, that's exactly right, and I think this approach is close to what I'm looking for. Is it possible to impose constraints on the random effects in the model (as is done with fixed effects) in order to reduce parameter uncertainty?

**Comment by paul-buerkner** [comment]
I am afraid it is not., but of course you can specify more informative priors on the standard deviation and correlation matrix parameters of the random effects. Do you think special constraints are necessary in your case?

**Comment by ccolaneri** [comment]
Yes, I think constraints are necessary, because I need stable parameter estimates. Without constraints, the individual coefficients will have dramatically increased variance.

**Comment by paul-buerkner** [comment]
I see and I am sorry, that this is not possible in brms. I currently don't plan to implement it as it is rather specific and hard to create a syntax for.

**Comment by jgabry** [comment]
I strongly recommend against putting hard constraints on any parameters
("fixed" or "random", that is, non-varying or varying) unless those
constraints are absolutely required (e.g. constraining a standard
deviation to be positive is required). If the amount of uncertainty in the
parameter estimates is implausibly large then you only know that because
you have some prior information telling you what is plausible. So the
natural thing to do would be to include that information in the priors.

Hope that helps,

Jonah

**Comment by jgabry** [comment]
You can write the constraints into the generated Stan code yourself
probably, but I've never (really never) seen that lead to anything good
unless the constraints are logically necessary, and that doesn't sound like
the case here.

**Comment by jnoppenheim** [comment]
I believe the original comment is about imposing such a logical constraint.  Either the sum of the coefficients of the levels of a categorical variable must either be zero, or one of the coefficients must be zero for the model to be identifiable.  This is not strictly necessary for finding the variance due to random effects, however, excluding it makes the individual effect estimates overly noisy.

**Comment by jgabry** [comment]
Out of curiosity why do think constraints are necessary as opposed to an
informative prior? Why would you get dramatically increased variance?

If you put constraints but the sampler wants to go outside the constraints
(and it sounds like it does) you will get draws bunched up against the
constraints, and you definitely don't want that.

**Comment by jnoppenheim** [comment]
It's well established that corner or sum to zero constraints are necessary for model identifiability.  That's why they're implemented directly for "fixed effects" in brms.  In general, they're needed for any categorical variable when you want converged point estimates.  When you do not impose a constraint, you gain an extra degree of freedom: In the model y ~ x, if x has N levels plus an intercept, I have N+1 variables despite only N different levels.  This leads to unconverged sampling and inflated variance.

**Comment by jgabry** [comment]
Yes you're right about identifiability and coefficients on categorical
variables. Thanks for clarifying. I failed to notice that was the
particular issue when commenting. May have read too quickly!

**Comment by jnoppenheim** [comment]
No worries.  I think there's a good bit of demand for modeling features that move beyond the traditional fixed vs random effects divide, which was always one of mathematical convenience anyhow.
