### ISSUE TITLE
algorithm = "meanfield"/"fullrank" returns 2 fewer draws than requested with adapt_engaged = FALSE

### ISSUE THREAD

**Issue by smthzch** [paul-buerkner/brms#1394]
Minimal example:

```
model <- brms::brm(
  y ~ x,
  data = data.frame(x = 0:1, y = 0:1),
  algorithm = "meanfield",
  adapt_engaged = FALSE,
  output_samples = 100
)
model$fit # only 98 draws
```

System:

```
version  R version 4.2.0 (2022-04-22)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 brms      2.16.3   2021-11-22 [1] RSPM (R 4.2.0)
```

**Comment by paul-buerkner** [comment]
I have no idea what's happening. brms passes `output_samples` unaltered to `rstan`, so brms has nothing to do with it in this case. Perhaps open an issue at rstan's github repo?  I am closing this issue here, because I can (to my current understanding) not fix it from the brms side. but please feel free to reopen it, if it turns out that it is, in fact, a brms issue.
