### ISSUE TITLE
Reconsider deprecation of global priors for categorical/mulinomial?

### ISSUE THREAD

**Issue by bwiernik** [paul-buerkner/brms#1420]
I frequently fit categorical/multinomial families with 5 to 7 categories. This becomes inconvenient when I want to put priors on things like random intercepts. For most model families, I can do something like:

```r
prior(normal(0, .1), class = "sd")
```

and it will be able to apply to all of the `"sd"` parameters, but with these families, I need to specify for each response category, even though I want to apply the same prior to each category.

```r
prior(normal(0, .1), class = "sd", dpar = "catA") +
      prior(normal(0, .1), class = "sd", dpar = "catB") +
      prior(normal(0, .1), class = "sd", dpar = "catC") +
      prior(normal(0, .1), class = "sd", dpar = "catD") +
      prior(normal(0, .1), class = "sd", dpar = "catE")
```

It seems like this requirement was a recent change in how these families work, but it makes them very difficult to use. Is there any possibility that global parameters for these families might be re-enabled?

**Comment by paul-buerkner** [comment]
Yes, I understand that this is inconvenient. Does your issue relate only to the `sd` class or also to other classes? In the latter case, to which other classes?

**Comment by bwiernik** [comment]
I've personally only run into this with "sd" class recently, but I can imagine wanting to do the same with "b" class -- eg, if I want to put a light regularizing prior for predictor X for each outcome option.

**Comment by mguzmann** [comment]
Just my perspective, but I run into this all the time with different kinds of predictors.

**Comment by paul-buerkner** [comment]
I have reconsidered allowing the discussed prior specification options and even tried to implement them. However, the amount of special case coding and resulting maintence issues would not be justified by the advantages of the feature at this point. I may revisit such ideas at a later point when I have a good idea how to make it compatible with brms prior specification framework in a more natural and less awkward manner.

That said, prior specification in brms is vectorized since some time, so you can do things like:

```R
set_prior("normal(0, 2)", dpar = c("muX", "muY", "muZ"))
```
