### ISSUE TITLE
Allow data variable in nonlinear function/syntax via stanvars and data2 arguments

### ISSUE THREAD

**Issue by Sandhu-SS** [paul-buerkner/brms#1425]
Consider the example below wherein I try to pass ‘z’ (a real) by using ```data2``` and ```stanvars``` options, but it throws error. 

The error with ```data2``` is “Error in get(covars[i], data) : object 'z' not found” and whereas using ```stanvars``` option results in “Error: The following variables can neither be found in 'data' nor in 'data2': 'z'”. 

If ‘z’ would have been a vector of same as length as nrow(dat1), then one can easily add it to the data frame e.g,., ``` dat1$z <- 2```. This could be useful because 'z' could be a small vector such as knots for custom spline functions.

```
library(brms)
#> Warning: package 'brms' was built under R version 4.1.3
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.18.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar

b <- c(2, 0.75)
x <- rnorm(100)
y <- rnorm(100, mean = b[1] * exp(b[2] * x))
dat1 <- data.frame(x, y)

prior1 <- prior(normal(1, 2), nlpar = "b1") + prior(normal(0, 2), nlpar = "b2")


try1 <- make_stancode(bf(y ~ b1 * exp(b2 * x * z), b1 + b2 ~ 1, nl = TRUE),
                      data = dat1, prior = prior1,
                      data2 = list(z = 2))
#> Error in get(covars[i], data): object 'z' not found


try2 <- make_stancode(bf(y ~ b1 * exp(b2 * x * z), b1 + b2 ~ 1, nl = TRUE),
                      data = dat1, prior = prior1,
                      stanvars = stanvar(2, name = 'z'))
#> Error: The following variables can neither be found in 'data' nor in 'data2':
#> 'z'

```

Thanks

**Comment by paul-buerkner** [comment]
brms' non-linear syntax currently treats variables in a non-linear formula either as parameter or covariate (the latter to be found in `data`). I doubt it will be easy or generally possible to add arbitrary data in non-linear formulas, because those are translated to Stan in some kind of "literal" way. Perhaps you may want to ask on https://discourse.mc-stan.org/ with your actual case where you need this and see if people come up with a workaround for you specific application.
