### ISSUE TITLE
Feature request: Are you open to a PR with a tutorial vignette + dataset?

### ISSUE THREAD

**Issue by cjvanlissa** [paul-buerkner/brms#1441]
Dear @paul-buerkner, my colleagues and I are writing a tutorial for experience sampling studies using BRMS, along with some sample data for users to follow along. The code+data currently live on the Open Science Framework (OSF.io), but we feel that it would be more in line with FAIR principles if we could contribute them to BRMS as a vignette and package data. Would you consider accepting such a pull request?

Thank you for your consideration!

**Comment by paul-buerkner** [comment]
Dear @cjvanlissa I really appreciate the idea and your motivation to make your code and data more widely available!

Unfortunately, I don't think it is viable to make this a brms vignette because those vignettes, once rendered, have a considerable size and CRAN already complains every time that brms is too big (over 5MB or something). 

An alternative would be to perhaps make a blog post on your website about it. I can then link it in my list of brms blog posts (https://paul-buerkner.github.io/blog/brms-blogposts/), which is also linked to the in brms README. 

I am open to other ideas of course. Just a brms vignette may be a bit of a difficult approach.

**Comment by cjvanlissa** [comment]
Dear Paul,

I'm guessing you're running the code in the vignetteshipping the vignettes with

**Comment by paul-buerkner** [comment]
What makes the vignettes large are their graphics. So if the vignette would be without graphics, then an addition could be possible. We would have to see from the size of the compiled vignette (html). Do you have an idea how big your vignette would roughly look like one compiled?

**Comment by cjvanlissa** [comment]
Thank you for the advice, I'll have a look and see if I can make it ultra small.
