### ISSUE TITLE
vignette HTML output

### ISSUE THREAD

**Issue by bgoodri** [paul-buerkner/brms#158]
I noticed that some of the brms vignettes do not have R output due to CRAN's time limits. We had the same problem with rstanarm. Here is how we worked around it. 

In the YAML section of the vignette, we have
```
...
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
```
and then we have in `knitr::opt_chunks$set(eval = params$EVAL)`.

If you build brms with `devtools::build` it sets the environmental variable `NOT_CRAN = true`, and the R chunks in the vignettes are evaluated. You can also but `export NOT_CRAN=true` into your .bashrc file or whatever the equivalent on Windows is. When you upload brms*.tar.gz to CRAN, there is no `NOT_CRAN` environmental variable, so when it runs `R CMD check brms*.tar.gz`, the R chunks in the vignettes are not evaluated. But when brms*.tar.gz is pushed to the CRAN website, it takes the HTML vignettes from its inst/doc subdirectory, which were built on your computer rather than on CRAN. Also, when someone installs brms as a binary, they get the correct vignettes.

**Comment by paul-buerkner** [comment]
Thanks! This is great! Before I hadn't found a way to make this possible.
Am 27.12.2016 19:36 schrieb "bgoodri" <notifications@github.com>:

**Comment by fweber144** [comment]
Sorry for digging this out. I'm currently trying to find out the reason why projpred's vignettes do not have their output shown on CRAN. I think I found that reason, but I have a general question concerning the workaround proposed here:

As explained [here](https://r-pkgs.org/vignettes.html#vignette-cran), vignettes have to be built locally and are not rebuilt on CRAN. CRAN takes the html files from `inst/doc/` as they were uploaded (i.e. hopefully with the output included) and executes the R files stored in `inst/doc/`. As far as I understand, CRAN doesn't check whether the R files stored in `inst/doc/` match the uploaded html files (because if CRAN would do so, then it would actually rebuild the vignettes).

That's why I don't really get the purpose of the workaround proposed here. Consider the following two options:

1. Setting the environment variable `NOT_CRAN` to `"true"` and running `devtools::build()` evaluates the vignettes' R code (so that the html files have the output included). *But* it also creates R files with uncommented R code in `inst/doc/`. And these R files (if uploaded) will be run by CRAN.
2. Setting `NOT_CRAN` to something other than `"true"` (or not setting it at all) and running `devtools::build()` does not evaluate the vignettes' R code. Correspondingly, the R files in `inst/doc/` have everything commented out (apart from the `params` at the beginning). *But* the html files do not have the output included, so they shouldn't be uploaded to CRAN.

Perhaps the workaround was meant to be a two-step process?: First run `devtools::build()` with `NOT_CRAN` set to `"true"` (and afterwards backup the html files with the output included), then run `devtools::build()` again with `NOT_CRAN` unset. Then, one can replace the html files from the second run (which lack the output) by those from the first run (which have the output included). But the only advantage of this two-step process would be that CRAN doesn't check the vignettes' R code (because the separate .R files have everything commented out). And as far as I can tell from their .tar.gz files downloadable from CRAN, rstanarm and brms don't follow such a two-step process (because the R code in the vignettes' separate .R files is uncommented). That also indicates that there's no time limit for CRAN's check of the vignettes' R code (or this time limit is higher than the time required by rstanarm and brms).

So, could you help me understand the advantage of this workaround?

**Comment by paul-buerkner** [comment]
This is the script I use to evaluate vignettes: 

```R
withr::with_envvar(c("NOT_CRAN" = "true"),
  devtools::build_vignettes()
)

# size reductions of PDF vignettes
# tools::compactPDF("doc/brms_overview.pdf", gs_quality = "ebook")
# tools::compactPDF("doc/brms_multilevel.pdf", gs_quality = "ebook")
```

This is the script I use to release brms to CRAN

```R
withr::with_envvar(c("NOT_CRAN" = "true"),
  devtools::release(check = FALSE, args = "--compact-vignettes=both")
)
```

Does that help?

**Comment by fweber144** [comment]
Thanks. Yes, it helps a bit in terms of confirming what I thought your build/release process must look like. But I still don't understand why we couldn't set `params$EVAL` always to `TRUE` then. Sorry if I'm missing something here.

**Comment by paul-buerkner** [comment]
to prevent CRAN itself from evaluating the vignettes because that increases
checking time too much.

Frank Weber ***@***.***> schrieb am Di., 25. Mai 2021, 14:56:

**Comment by fweber144** [comment]
It turned out that the wording in the [link](https://r-pkgs.org/vignettes.html#vignette-cran) above is mistakable: CRAN does not build the vignettes during R CMD build, but it does indeed rebuild them during R CMD check (and does not just run the corresponding .R files). The ["Writing R Extensions"](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) manual is clearer in this regard (even though not necessarily with respect to CRAN) and the [CRAN policies](https://cran.r-project.org/web/packages/policies.html) also give a hint. So yes, then this workaround does of course make sense. Sorry for taking your time for this.
