### ISSUE TITLE
plot(marginal_effects(...), points = TRUE) does not work for distributional models

### ISSUE THREAD

**Issue by JannikVindeloev** [paul-buerkner/brms#167]
Dear Paul

The following code will only plot points for one of the groups (System A):

# prepare data
library(tidyverse)
library(brms)
df_sim <- data.frame(System = c(rep("A", 75), rep("B", 25)),
                     Item = c(rep(c("A1", "A2", "A3", "A4", "A5"), each = 15),
                              rep(c("B1", "B2", "B3", "B4", "B5"), each = 5)))
df_sim$Item <- ordered(df_sim$Item, levels = unique(df_sim$Item))

set.seed(1905)
df_sim <- df_sim %>%
  mutate(value = c(rep(rnorm(n = 5, mean = 5.3, sd = 0.1), each = 15), 
                rep(rnorm(n = 5, mean = 5.2, sd = 0.05), each = 5)),
         value = c(rnorm(n = 75, mean = value, sd = 0.1),
                rnorm(n = 25, mean = value, sd = 0.05)))

# plot data
df_sim %>% 
  ggplot(aes(x = Item, y = value))+
  geom_point()

# model data
fit <- brm(brmsformula(value ~ Item-1, sigma ~ System - 1),
               data = df_sim,
               family = gaussian(),
               chains = 3)

#Plot marginal effects
plot(marginal_effects(fit), points = TRUE)

**Comment by paul-buerkner** [comment]
This is intentional and I thought I had this documented, but apparently I haven't. Thanks for pointing me to it.

The reasoning for the behavior goes as follows: When marginal effects creates a graph for a certain predictor, say `item`, is has to condition on all other predictors, `system` in your case. By default it conditions on the mean of continuous predictors and on the reference category for factors (you can change this with argument `conditions`). Since we condition on System A as it is the reference category, the points of System B are not actually intended to be predicted, which may cause the false impression of a bad model fit when adding point of System B. In your case, it would be ok to add them, but generally it isn't.

To get all points, I recommend:
```R
plot(marginal_effects(fit, "Item:System"), points = TRUE)
```

(you may install the dev version of brms from github to make this work).

**Comment by paul-buerkner** [comment]
Also, consider setting argument `method = "predict"` or otherwise you won't include `sigma` in the plotted effects.

**Comment by JannikVindeloev** [comment]
OK I get it. Thanks! Great package ;-)

**Comment by paul-buerkner** [comment]
Closed via 8151396
