### ISSUE TITLE
`lprior` not available if `normalize = FALSE`

### ISSUE THREAD

**Issue by n-kall** [paul-buerkner/brms#1672]
Currently, specifying `normalize = FALSE` will define the `lprior` in the model block, so it is not returned in the fit (resulting in priorsense giving an error). At the least, this could be added to the documentation (such as is done for bridge sampling).

Alternatively, maybe the `lprior` could be created in the generated quantities using the normalized `*_lpdf` functions in this case.

**Comment by n-kall** [comment]
We could also provide an error message pointing to `normalize = TRUE` in the priorsense helper functions when the `lprior` is not available

**Comment by paul-buerkner** [comment]
Thanks! Since the _lupdf functions are not allowed in the transformed parameters block for some reason, lprior would have to be regenerated in generated quantites but that seems like excessive effort. The speedup from using the unnormalized functions is usually small and I think that it is easiest to just have an informative error that points to lprior not being saved because normalize was FALSE. I will update this in the next patch of brms.

**Comment by paul-buerkner** [comment]
Fixed :-)
