### ISSUE TITLE
pp_check automatically plots, so if you modify...

### ISSUE THREAD

**Issue by wfolta** [paul-buerkner/brms#169]
The pp_check routines automatically plot, so if you want to use them as ggplot objects and then do something (add titles, lines, xlim, etc), you get two plots: the original directly from pp_check, and the modified one.

Could we get a plot=TRUE/FALSE option in pp_check to inhibit this? (Which may require changes to the underlying plot package you're using.

**Comment by paul-buerkner** [comment]
Hmm, could be something inside **bayesplot**. @jgabry do you have any ideas?

**Comment by jgabry** [comment]
Hmm, I think something is going on with the `pp_check.brmsfit` method because this doesn't happen with the `pp_check.stanreg` method:

```r
library(brms)
fit1 <-  brm(mpg ~ wt, data = mtcars)
p1 <- pp_check(fit) # still displays plot even though assigned to p1

library(rstanarm)
fit2 <- stan_glm(mpg ~ wt, data = mtcars)
p2 <- pp_check(fit2) # assigns but doesn't display the plot
```

I probably won't have a chance to take a closer look until after the weekend, but if you haven't sorted it out before then I'm happy to help dig around and see what's causing that.

**Comment by paul-buerkner** [comment]
You are right, thanks Jonah! I was calling `rstan::quietgg` internally, but I got rid of it.

**Comment by paul-buerkner** [comment]
@wfolta Feel free to close this once you can confirm that it is fixed in the dev version.

**Comment by wfolta** [comment]
Fixed!
