### ISSUE TITLE
Beta distribution for multivariate models 

### ISSUE THREAD

**Issue by matschmitz** [paul-buerkner/brms#1700]
As of now, responses' correlations can only be estimated for gaussian and student models. Could it please be extended to Beta() distributions? Many thanks!

**Comment by lunafazio** [comment]
Inference of correlations in multivariate gaussian and Student families is available due to their particular structure and doesn't generalize in a straightforward manner to other distributions.

There are ways to address that problem, but sorting that out would require a more detailed discussion of the analysis you have in mind, which should be posted in the Stan forums.

**Comment by nicholasjclark** [comment]
Not to hijack this thread but you can estimate correlated latent residuals for Beta-distributed observations using factor models in Stan with [{mvgam}](https://nicholasjclark.github.io/mvgam/reference/jsdgam.html) Agree though it is better to post on the Stan discourse and I can provide a reprex there to get you started
