### ISSUE TITLE
Group Level Predictor/Covariate Outputs

### ISSUE THREAD

**Issue by jebyrnes** [paul-buerkner/brms#189]
So, I've been working with some models with group level predictors lately, and have a quandry. When group level predictors are included in `brms` models, their parameters still pop out as population level estimates. For example, let's look at the Exam scores from `mlmRev` where `schavg` is a school level average - and hence a group, not individual, predictor

```
library(mlmRev)
library(brms)
library(dplyr)

## Make a smaller exam data for speed
Exam_full <- Exam

Exam <- Exam_full %>%
  group_by(school) %>%
  slice(1:5) %>%
  ungroup()

mod_brm <- brm(normexam ~ schavg + (1  | school), data=Exam)
```

in the summary produces

```
Group-Level Effects: 
~school (Number of levels: 65) 
              Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sd(Intercept)     0.13      0.08     0.01      0.3       1032    1

Population-Level Effects: 
          Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
Intercept     0.06      0.05    -0.05     0.16       4000    1
schavg        0.71      0.16     0.40     1.03       4000    1
```

My question is, for group level predictors, should they not be included in the Group Level effects table? Or is this due to something different that should be done syntactically in specifying the model (I'm adapting straight from `lme4`)?

**Comment by paul-buerkner** [comment]
The output can be interpreted as in **lme4**. In **brms** fixed effects are called population-level effects and random effects are called group-level effects. In the summary output under group-level effects only the standard deviations and correlations do appear. To extract (summary statistics of) each level of `school`, use method `ranef` (only group-level effects) or `coef` (population-level and group-level effects combined).

**Comment by jebyrnes** [comment]
OK, so, it's a names thing. I had wondered if there was some need to use `brmsformula` to specify separate individual and school level models. Or would that be something that could be done?

**Comment by paul-buerkner** [comment]
No there is no need for using brmsformula in your case. Since brms uses
lme4 syntax, you get the same likelihood in both packages when using the
same formula (but brms is much more flexible if you want to go beyond that).

Am 28.02.2017 17:52 schrieb "Jarrett Byrnes" <notifications@github.com>:

OK, so, it's a names thing. I had wondered if there was some need to use
brmsformula to specify separate individual and school level models. Or
would that be something that could be done?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/paul-buerkner/brms/issues/189#issuecomment-283097095>,
or mute the thread

**Comment by paul-buerkner** [comment]
And to answer your second question: you cannot specify models on different
levels using brmsformula.

Am 28.02.2017 18:01 schrieb "Paul Buerkner" <paul.buerkner@gmail.com>:

No there is no need for using brmsformula in your case. Since brms uses
lme4 syntax, you get the same likelihood in both packages when using the
same formula (but brms is much more flexible if you want to go beyond that).


Am 28.02.2017 17:52 schrieb "Jarrett Byrnes" <notifications@github.com>:

OK, so, it's a names thing. I had wondered if there was some need to use
brmsformula to specify separate individual and school level models. Or
would that be something that could be done?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/paul-buerkner/brms/issues/189#issuecomment-283097095>,
or mute the thread
