### ISSUE TITLE
Categorical regression with oddly-named level causes error

### ISSUE THREAD

**Issue by waynefoltaERI** [paul-buerkner/brms#194]
I just ran a categorical regression where the levels of the target variable were "AC", "AM", "AP", "AD", "?" and in the generated Stan code it's trying to create variables called "K_?" and "X_?", which cause Stan heartburn. A little unusual on my part, and I can work around it by using "NA" instead of "?" for that level, but I thought I'd report it.

**Comment by paul-buerkner** [comment]
Thanks for reporting this issue. It occured because internally categorical and non-linear models use the same interface with the response categories representing the "non-linear parameters". I just pushed a commit to github that should ensure automatic renaming and hence valid names for Stan.  Although it should now work with arbitrary category names, I recommend not using an special characters in factor level names (also for predictors) as it might happen that parameter names are no valid R variable names in the end (the latter is not a special problem of brms but happens with many R model fitting functions).

**Comment by waynefoltaERI** [comment]
Thanks! As you say, we should probably avoid such levels on general principle, so I'm sure your fix is more than enough.
