### ISSUE TITLE
Prediction of categorical getting error in make_standata

### ISSUE THREAD

**Issue by waynefoltaERI** [paul-buerkner/brms#20]
In R, using brms 0.6.0, I create a model:

    br1 <- brm (FLAG ~ Age + [[...left out rest of formula...]], data=x2.train, refresh=20,
                         prior=set_prior ("normal (0, 6)"), family="categorical",
                         n.chains=3, n.cluster=3)

And I can do:

    predict (br1)

which works, but

    predict (br1, x2.train)

results in an error 

    Error in if (max(standata$ncat) == 2) message("Only 2 levels detected so that family     'bernoulli' might be a more efficient choice.") : 
      missing value where TRUE/FALSE needed

with stack traceback:

    1: predict(br1, xyz)
    2: predict.brmsfit(br1, xyz)
    3: amend_newdata(newdata, fit = object, re_formula = re_formula, allow_new_levels =     allow_new_levels)
    4: make_standata(fit$formula, data = newdata, family = fit$family, autocor =        
        fit$autocor, partial = fit$partial, newdata 

I do notice that FLAG has no NA's in predict.brmsfit, but is entirely NA's in amend_newdata, which I think might be how the predict works, but might also be wrong.

**Comment by paul-buerkner** [comment]
Thanks for reporting the error! I will have a look into this and tell you as soon as I have found a solution.

**Comment by paul-buerkner** [comment]
I think the problem is that the response variable is overwritten in amend_newdata, although I would expect it not to be NA even then... If this is really the cause, I may have already fixed it a few weeks ago (after the release of 0.6.0), so I would suggest that you install the latest dev version from github via `devtools::install_github("paul-buerkner/brms")` and try it again.

In addition, while investigating this issue, I noticed some other potential problems when using `newdata` that I haven't thought of yet. They should not affect your model but I should fix them anyway.

**Comment by waynefoltaERI** [comment]
Looks like that fixed it, thanks! I found another issue now that I'm able to predict, which I'll enter as a separate issue.
