### ISSUE TITLE
Add functions for loo predictions

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#204]
See https://github.com/stan-dev/rstanarm/issues/159 for details about this feature.

**Comment by jgabry** [comment]
I just released a version of loo that has a new function E_loo that will
compute all of these weighted expectations, so all you'll need to do is
make a wrapper that runs PSIS for a brms model and passes E_loo the
resulting smoothed weights.

On another note, I think I'm going to get rid of the loo_pit function that
I tentatively added to rstanarm. I don't think the user ever needs to call
that directly and we only need it for plotting, so bayesplot can handle the
PIT computation instead of rstanarm and brms. The other functions (e.g.
loo_predictive_interval) could I guess be useful for users to call directly
so those are probably worth adding and exposing.

**Comment by paul-buerkner** [comment]
Thanks for your comments Jonah! I already added all of these functions locally closely following what rstanarm does. If you choose to get rid of loo_pit again, I will remove it as well.

**Comment by jgabry** [comment]
Ok great!

**Comment by paul-buerkner** [comment]
How sure are you to remove `loo_pit`? I am asking because I am thinking of not adding it to the commit in the first place.

**Comment by jgabry** [comment]
https://github.com/stan-dev/rstanarm/commit/c9b09ffc317e53b0e4dcc585ccec018846890f52

**Comment by jgabry** [comment]
Already done!

**Comment by paul-buerkner** [comment]
Amazing, thanks!

**Comment by paul-buerkner** [comment]
Since `pp_check` now also supports the new `ppc_loo_*` types, I think this issue can be closed.
