### ISSUE TITLE
Prediction seems to use a lot of RAM

### ISSUE THREAD

**Issue by waynefoltaERI** [paul-buerkner/brms#21]
I create a categorical model (target has four levels) with 12 variables, two of which are categorical. I'm running this on my employer's wimpy Windows laptop with 8 GB of RAM -- about 2 GB free --  and if I try predicting 45K test cases, it takes forever to eventually run out of RAM. If I predict 6K test cases, it does that in about 30 seonds and with very little RAM. (So I've resorted to a foreach loop to do 6,000 at a time.)

This seems like a problem, since it's routine to score a lot more data than is used for training.

**Comment by paul-buerkner** [comment]
I agree. That is a typical case of R not handling RAM very well. The prediction is performed using a call to lapply, which loops over the number of observations. Inside lapply (that is for each observation) all MCMC samples are handled at once in a vectorized manner. Unfortunately, I don't see how to vectorize the calls for both, observations and samples, at the same time. 

It may be possible to do somethinng similar to what you did as a workaround internally, when the number of observations is very large. However, it may also just be the sheer number of values to store at the same time (basically a Nobservation x Nsamples matrix) that overloads the RAM.

**Comment by waynefoltaERI** [comment]
I just ran into a complication in my workaround, which might give you an idea: in the last piec of the test data in my for each loop, it only returns three columns rather than the four that previous predicts do. (The previous has P(Y=1), ..., P(Y=4), while the last only has P(Y=1), ..., P(Y=3), which I assume is due to no test cases that have a P(Y=4) > 0.)

**Comment by paul-buerkner** [comment]
That's an issue I also encountered yesterday and it should already be fixed in the latest dev version. So installing brms from github again should solve this.

**Comment by waynefoltaERI** [comment]
I pulled the dev copy as of today, and now I'm getting a different error:

Error in if (any(standata$Y > standata$ncat)) stop(paste0("Number of categories is smaller than",  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In Ops.factor(standata$Y, standata$ncat) : ‘>’ not meaningful for factors

When I do a `standata (br1)`, the Y is numeric (the level numbers, I guess) and so is ncat.

**Comment by paul-buerkner** [comment]
I see, the error occurs because the response variable was not correctly transformed to numeric values. I will fix this asap.

**Comment by paul-buerkner** [comment]
I hope that it is working now, at least it does for my testing models. Would you mind trying it again?

**Comment by waynefoltaERI** [comment]
Looks like it worked, thanks!

**Comment by paul-buerkner** [comment]
Regarding the RAM overflow, can you try to predict all 45k data at once running `debug(predict)` before and tell me at which line of the `predict.brmsfit` function R actually crashes? 

This would help me alot in finding the source of the problem. Hopefully it appears at a point that I can actually improve with respect to RAM requirements...

**Comment by paul-buerkner** [comment]
After running some tests with large datasets, I think that 2GB of free RAM simply isn't enough to manipulate Nsamples x 45k matrices (at least for the operations needed in predict). I am hesitating to generally split up calls within the predict function itself as this would cause trouble in models where the order or position of the observations is relevant (e.g., in models with autocorrelation). However, I found some statements that could possibly be improved with respect to speed (maybe also with respect to RAM). Changing them will likely not solve your issue, but it will help with overall stability and efficiency.

**Comment by paul-buerkner** [comment]
I finally found the time to improve the code related to the predict method with respect to RAM requirements, primarily by (1) removing (or overwriting) large objects when they are no longer necessary and (2) using sparse matrices of the Matrix package in the computation of the linear predictor where useful. Depending on the model, this will reduce the RAM requirements considerably. 

For your particular case (i.e. 45k observations in a categorical model with 4 categories), one will most likely still need more than 2GB of RAM simply because the linear predictor array is so large (and not sparse), but you will definitely need (much) less RAM than before.

Additionally, you can choose to use only a subset of samples for prediction (with the arguments `subset` and `nsamples`), which will lead to a more or less linear decrease in RAM requirements.

I am going to close this know and since I cannot find any email address of yours on the internet, I use this issue to thank you again for your great blogpost! It really helped a lot in raising awareness for brms! :-)
