### ISSUE TITLE
pp_check for SN model

### ISSUE THREAD

**Issue by stephensrmmartin** [paul-buerkner/brms#233]
Error in qskew_normal(c(0.78334285897678, 0.929325148078576, 0.964127189825317,  : 
  could not find function "qskew_normal"

Currently running a truncated skew-normal regression model (y | trunc(1,7) ~ predictors), and pp_check gives the above error.

**Comment by paul-buerkner** [comment]
The reason is simply that I haven't implemented the quantile function of the skew normal distribution yet. 
There is an implementation in the **sn** package but I believe it is not fully vectorized (which we will definitely need). Before releasing the next version of **brms** on CRAN I will either add the `qskew_normal` function or throw an informative error message when calling predict with a truncated skew normal model.

**Comment by paul-buerkner** [comment]
It should be working correctly now :-)

**Comment by stephensrmmartin** [comment]
You're ridiculously quick. Thanks so much [yet again].
