### ISSUE TITLE
Implement Tweedie Distribution / aggregate distribution

### ISSUE THREAD

**Issue by Atan1988** [paul-buerkner/brms#249]
Hi Paul,

 Sometimes, in insurance data, we have to model claims at the aggregate level ( total claims dollars for a policy year, etc).  Since the conventional assumption for claim count is Poisson, and Gamm distribution for claims size distribution,  the aggregate distribution would be a version of the tweedie. 

I have modified the stan_code generated by brms::make_stancode (using the hurdle gamma family) to work with the Poisson - gamma process.  Attached please find the R code that simulates the data, as well as the stan code for the model.  Ideally, it would be also great that, we can have more flexible parings (like the hurdle and zero-inflated counterparts), such as  Poisson-Gamma/Negative-binomial + lognormnal/ Negative-binomial + Gamma. 

Would it be possible to implement this kind of aggregate models?

Thanks!
Allen

[tweedie example.zip](https://github.com/paul-buerkner/brms/files/1208723/tweedie.example.zip)

**Comment by paul-buerkner** [comment]
Thanks for the suggestion and the code! This looks like an interesting
feature! Could you provide a bit more background for me to read about those
kind of models?

Am 08.08.2017 5:54 nachm. schrieb "Atan1988" <notifications@github.com>:

**Comment by Atan1988** [comment]
Here is some slides providing some more back-ground: 
https://github.com/paul-buerkner/brms/issues/249#issuecomment-321280819

I think the clark triangle data used in the non-linear modeling example of brms, can be also modeled with Tweedie, as the responses are aggregate claims of a particular year at various development periods. 
https://cran.r-project.org/web/packages/brms/vignettes/brms_nonlinear.html

I tried to replace the guassian family in the example with tweedie.  Although it takes much longer time to sample(about 1800s for 3000 iterations, 1000 warmup, 2 chains), the model does converge to some reasonable parameters. I guess I might have coded somewhere inefficiently in my stan code. 

I have included both the R code and Stan code. 
[tweedie clark triangle.zip](https://github.com/paul-buerkner/brms/files/1218851/tweedie.clark.triangle.zip)

**Comment by paul-buerkner** [comment]
Thanks, I will take a look.

Which example did you mean exactly? Given that those have pretty low sample size, 1800 s (30 mins) seems a bit large for me

**Comment by EKtheSage** [comment]
Hello, is there an update to having Tweedie distribution in brms?

**Comment by paul-buerkner** [comment]
The tweedie distribution is not yet built in, but you can now specify it yourself using the `custom_family` feature. See https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html for an example.

**Comment by paul-buerkner** [comment]
I believe that because of the flexibility of the tweedie / aggregate distribution, it does not make sense to implement them natively in brms (we could only implement special cases anyway). Rather, as indicated above, I think such distributions are best implemented directly from the user side by means of the `custom_family` feature. Thus I am closing this issue.

**Comment by dbarneche** [comment]
Hi Paul, I tried to implement in brms the special case of the Tweedie for p [1,2] (Compound Poisson-gamma)
https://discourse.mc-stan.org/t/tweedie-likelihood-compound-poisson-gamma-in-stan/14636/9

The code is rough because it could use some vectorisation to improve speed. I was wondering though if you think this could warrant an inclusion in brms as a native family? Rather than calling it Tweedie, perhaps it could be called `compound_poisson_gamma` instead?
