### ISSUE TITLE
Improve sampling speed of models containing only fixed effects

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#25]
It appears that there is some room for improvement with regard to sampling speed when fitting models containing only fixed effects (see also #24). From what I have seen, this seems to be an issue primarily for highly correlated predictors, but it might be as well more general.

**Comment by paul-buerkner** [comment]
It turned out that centering the fixed effects design matrix around its column means improved sampling speed noticeably and could explain the speed differences discussed in #24 that were unrelated to compilation time.

I would like to thank @waynefoltaERI for investigating and reporting this issue!

**Comment by jgabry** [comment]
Yeah, that's what we do for rstanarm. It's a nice and simple way to get a
bit of a speed up in most cases Although (depending on how you implement
the intercept term) it might require correcting the estimate of the
intercept so that the intercept reported to the user corresponds to the one
that would be obtained without centering X.

**Comment by paul-buerkner** [comment]
You are right. I have also implemented the intercept correction, and it appears to produce the expected results. While testing, I stumbled upon a problem in rstanarm related to the centering of X. I will open an issue for it on the rstanarm github page.

**Comment by jgabry** [comment]
Ok thanks!
