### ISSUE TITLE
Compatible formula()-method?

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#273]
Getting the right-hand-side of formulas from `brmsfit`-models is not as straighforward as for other models.

`stats::formula(m)[[3L]]` works for many models, including those fitted with `rstanarm`, but does not work for `brmsfit`-objects.

I guess this is no minor issue to fix?

**Comment by paul-buerkner** [comment]
This is because the model formula in brms can consist of multiple formulas not just one. If you look at 
`str(formula(m))`, you will see its structure is actually a list. In your case go for `formula(m)$formula[[3L]]`.

**Comment by strengejacke** [comment]
Yes, just saw that `$formula` is the formula object I needed. I implemented a rule for brmsfit-obj. in my pkg when retrieving the model formula.

Another question, which does not exactly fit into this topic, but this issue can be closed anyway and I don't want to open another one: 

when using `as.data.frame(model)` for models with random intercept and slope, are the random effects always prefixes "r_", and ending with "."?

**Comment by paul-buerkner** [comment]
They are starting with `r_` but why do you think they are ending with `.`?

**Comment by strengejacke** [comment]
Sorry, I was talking about the column names here. It looks like this is the pattern:

``` r
library(lme4)
library(brms)
data(sleepstudy)
fit <- brm(Reaction ~ Days + (Days | Subject), data = sleepstudy)

colnames(as.data.frame(fit))
#>  [1] "b_Intercept"                  "b_Days"                      
#>  [3] "sd_Subject__Intercept"        "sd_Subject__Days"            
#>  [5] "cor_Subject__Intercept__Days" "sigma"                       
#>  [7] "r_Subject.308.Intercept."     "r_Subject.309.Intercept."    
#>  [9] "r_Subject.310.Intercept."     "r_Subject.330.Intercept."    
#> [11] "r_Subject.331.Intercept."     "r_Subject.332.Intercept."    
#> [13] "r_Subject.333.Intercept."     "r_Subject.334.Intercept."    
#> [15] "r_Subject.335.Intercept."     "r_Subject.337.Intercept."    
#> [17] "r_Subject.349.Intercept."     "r_Subject.350.Intercept."    
#> [19] "r_Subject.351.Intercept."     "r_Subject.352.Intercept."    
#> [21] "r_Subject.369.Intercept."     "r_Subject.370.Intercept."    
#> [23] "r_Subject.371.Intercept."     "r_Subject.372.Intercept."    
#> [25] "r_Subject.308.Days."          "r_Subject.309.Days."         
#> [27] "r_Subject.310.Days."          "r_Subject.330.Days."         
#> [29] "r_Subject.331.Days."          "r_Subject.332.Days."         
#> [31] "r_Subject.333.Days."          "r_Subject.334.Days."         
#> [33] "r_Subject.335.Days."          "r_Subject.337.Days."         
#> [35] "r_Subject.349.Days."          "r_Subject.350.Days."         
#> [37] "r_Subject.351.Days."          "r_Subject.352.Days."         
#> [39] "r_Subject.369.Days."          "r_Subject.370.Days."         
#> [41] "r_Subject.371.Days."          "r_Subject.372.Days."         
#> [43] "lp__"
```

**Comment by paul-buerkner** [comment]
This comes from make.names of the data.frame method. Try out as.matrix to
see the "real" names.

Am 11.10.2017 12:28 nachm. schrieb "Daniel" <notifications@github.com>:

Sorry, I was talking about the column names here. It looks like this is the
pattern:

library(lme4)
library(brms)
data(sleepstudy)fit <- brm(Reaction ~ Days + (Days | Subject), data =
sleepstudy)

colnames(as.data.frame(fit))#>  [1] "b_Intercept"
"b_Days"                      #>  [3] "sd_Subject__Intercept"
"sd_Subject__Days"            #>  [5] "cor_Subject__Intercept__Days"
"sigma"                       #>  [7] "r_Subject.308.Intercept."
"r_Subject.309.Intercept."    #>  [9] "r_Subject.310.Intercept."
"r_Subject.330.Intercept."    #> [11] "r_Subject.331.Intercept."
"r_Subject.332.Intercept."    #> [13] "r_Subject.333.Intercept."
"r_Subject.334.Intercept."    #> [15] "r_Subject.335.Intercept."
"r_Subject.337.Intercept."    #> [17] "r_Subject.349.Intercept."
"r_Subject.350.Intercept."    #> [19] "r_Subject.351.Intercept."
"r_Subject.352.Intercept."    #> [21] "r_Subject.369.Intercept."
"r_Subject.370.Intercept."    #> [23] "r_Subject.371.Intercept."
"r_Subject.372.Intercept."    #> [25] "r_Subject.308.Days."
"r_Subject.309.Days."         #> [27] "r_Subject.310.Days."
"r_Subject.330.Days."         #> [29] "r_Subject.331.Days."
"r_Subject.332.Days."         #> [31] "r_Subject.333.Days."
"r_Subject.334.Days."         #> [33] "r_Subject.335.Days."
"r_Subject.337.Days."         #> [35] "r_Subject.349.Days."
"r_Subject.350.Days."         #> [37] "r_Subject.351.Days."
"r_Subject.352.Days."         #> [39] "r_Subject.369.Days."
"r_Subject.370.Days."         #> [41] "r_Subject.371.Days."
"r_Subject.372.Days."         #> [43] "lp__"

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/paul-buerkner/brms/issues/273#issuecomment-335766784>,
or mute the thread
