### ISSUE TITLE
Error on model name for `kfold`

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#288]
I've fit two models to data, and I'd now like to compare them using `brms::kfold`, but I get a "failed to parse" error in `stanc`. 

The `brmsfit` objects were saved to `.RData` binaries by the fitting scripts. I'm now trying to load them with a script like the below:

```r
load(file.path(results_dir, "model_1.RData"))
fit_1 <- fit_main  # both were called "fit_main"

load(file.path(results_dir, "model_2.RData"))
fit_2 <- fit_main

rm(fit_main)

# do kfold:
kfold <- brms::kfold(fit_1, fit_2,
                     update_args = list(iter = 5000, chains = 4, cores = 4))

```

I get the following error:

```
Fitting model 1 out of 10
Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file149d2b530790' due to the above error.
```

Any ideas where I'm going wrong? I've sent Paul the offending model objects via email.

**Comment by paul-buerkner** [comment]
Did you fit those models on the same machine where you are calling kfold?

Am 05.11.2017 15:05 schrieb "Tom Wallis" <notifications@github.com>:

**Comment by tomwallis** [comment]
I get the same error whether I call kfold on my laptop or on the same
workstation that did the fitting.

Am 05.11.2017 17:21 schrieb "Paul-Christian Bürkner" <
notifications@github.com>:

**Comment by paul-buerkner** [comment]
This seems to be a bug that occurs when trying to recompile a brms model, which contains user defined Stan function passed via argument `stan_funs`. I will try to fix it during the next days.

**Comment by tomwallis** [comment]
Great, thanks Paul.

**Comment by paul-buerkner** [comment]
The problem was that `stan_funs` was not stored in brmsfit objects and thus could not be found inside `update.brmsfit`, which is used inside `kfold`. This is now fixed in the dev version for new models. For older models, please store `stan_funs` manually in `.$stan_funs`, where `.` is your brmsfit object. 

To avoid unecessary recompilations inside `kfold`, update your original model once and then run `kfold` with it. You may also use a dummy model:

```R
temp_oddity_2param <- update(fit_oddity_2param, chains = 0)
```

Please tell me if this really fixes your issue :-)

**Comment by tomwallis** [comment]
This seems to have done the trick, thanks Paul!

**Comment by paul-buerkner** [comment]
Great! I will close this issue now.
