### ISSUE TITLE
  '.' in formula and no 'data' argument

### ISSUE THREAD

**Issue by fishextinction** [paul-buerkner/brms#299]
I've been trying to search for the proper way to pass brms a set of predictor variable names without directly listing each variable name in the model object, in the manner of the base lm() function.

Example:
```
data(cars)
lm(speed~.,data=cars)

Call:
lm(formula = speed ~ ., data = cars)

Coefficients:
(Intercept)         dist  
     8.2839       0.1656  

brm(speed~.,data=cars)
Error in terms.formula(as.formula(x)) : 
  '.' in formula and no 'data' argument
```
Perhaps there's an easy way to accomplish this, but I can't find anything in the documentation, and several solutions that work for other R packages do not appear to work for brms.

**Comment by paul-buerkner** [comment]
See #298 for an answer to this question.

Am 04.12.2017 19:06 schrieb "fishextinction" <notifications@github.com>:

**Comment by fishextinction** [comment]
Thanks, updated to dev package and all is fine.

Is there a straightforward syntax for delineating group effects and then the rest of the variables as standard predictors? For example:
y ~ (1|group) + .

**Comment by paul-buerkner** [comment]
Yes this should work as you wrote.

Am 04.12.2017 21:15 schrieb "fishextinction" <notifications@github.com>:

Thanks, updated to dev package and all is fine.

Is there a straightforward syntax for delineating group effects and then
the rest of the variables as standard predictors? For example:
y ~ (1|group) + .

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/paul-buerkner/brms/issues/299#issuecomment-349091457>,
or mute the thread
