### ISSUE TITLE
Is the evidence ratio for a one sided hypothesis equivalent to a one sided bayes factor?

### ISSUE THREAD

**Issue by robustbayesian** [paul-buerkner/brms#311]
I have searched for an explanation of the evidence ratios used in the one sided hypothesis tests in brms, but I don't see that there's any previous history of the density of posterior > 0 over the density <0 being used as an inferential tool/quantification of evidence. It's intuitively sensible to me, but I am working on my masters thesis and am not sure if I can present these as bayes factors or if I need to document their use and statistical properties as different from Bayes factors.

The only evidence ratio I have found concerns comparing models with AIC.. 

Thanks!

**Comment by paul-buerkner** [comment]
These evidence ratios are indeed (one-sided) Bayes factors, but I realized this myself only recently, although the proof is rather simple (copy this in latex or Rmarkdown to get it rendered):

$$
\frac{P(\theta > 0 | y)}{P(\theta < 0 | y)} = \frac{\int_0^{\infty} p(\theta | y)}{\int_{-\infty}^0 p(\theta | y)} = \int_0^{\infty} \frac{p(y | \theta)p(\theta)}{\int_{-\infty}^{\infty} p(y | \theta)p(\theta)} / \int_{-\infty}^0 \frac{p(y | \theta)p(\theta)}{\int_{-\infty}^{\infty} p(y | \theta)p(\theta)} = \frac{\int_0^{\infty} p(y | \theta)p(\theta)}{\int_{-\infty}^0 p(y | \theta)p(\theta)} = BF_{\theta>0 \text{ vs. } \theta<0}
$$

However, this is not one of the BFs you typcially see being used and being critized. Those "standard" BFs are always against (or in favor) of a point hypothesis (e.g, `theta = 0`). To make it confusing, we suddently have **two** different "one-sided" BFs: The one you asked for testing `theta > 0 vs. theta < 0` and the one testing `theta > 0 vs. theta = 0`, with completely different statistical properties.

**Comment by robustbayesian** [comment]
Thanks you! I asked for theta > 0 vs. theta < 0 since that's the one it sounded like brms gives. 

> when the hypothesis if of the form a > b, the evidence ratio is the ratio of the posterior probability of 
   a> b and the posterior probability of a < b. 

Thanks again!

**Comment by paul-buerkner** [comment]
Exactly. Glad I could help!

**Comment by littlehifive** [comment]
@paul-buerkner sorry for commenting on this old thread, but I am a bit stuck on the equation you gave above. 

Given [the definition of Bayes Factor](https://en.wikipedia.org/wiki/Bayes_factor), I am wondering whether the following equation is valid (or is it not valid since the comparison hypothesis is not a point-null such as θ = 0?): 

BF_{θ > 0 vs. θ < 0} = [∫₀^∞ p(θ | y) dθ] / [∫₋∞^₀ p(θ | y) dθ]

But in the equation that you gave above, it seems that you are saying:

BF_{θ > 0 vs. θ < 0} = [∫₀^∞ p(y | θ) p(θ)] / [∫₋∞^₀ p(y | θ) p(θ)]

But I am not sure these two right-hand side formulas can be equated. Is there anything obvious that I am missing here? Or are you simply suggesting that posterior odds (of θ > 0 vs. θ < 0) can be thought of a different form of one-sided Bayes Factor?

Thanks so much for your help!

**Comment by IoSonoMarco** [comment]
@littlehifive the BF is the ratio between two marginal likelihoods p(y|M1)/p(y|M2). In Paul's equation, at the end, you are marginalizing out theta in both numerator and denominator, so you are computing a marginal likelibood under each model, where one model os theta>0, and the other is theta<0.

**Comment by mattansb** [comment]
Back to this following a discussion in bsky.

If the models are each sign restricted, the numerator won't be the same (since $p(\theta<0)=0$ for the first model, while $p(\theta<0)=1$ for the second model) and so don't cancel out - _but_ they might give the same integral value, which can definitely happen with a prior that is symmetric about the tested null (which is often the case).

Here is an example where the posterior evidence ratio isn't the BF between two complementary sign restricted models:

```R
library(brms)

set.seed(111)
d <- data.frame(y = rnorm(10))

# Prior is the positive part for N(0.5, 1)
mod1 <- brm(
  y ~ 1, 
  data = d,
  chains = 8, iter = 5500, warmup = 500, cores = 4,
  prior = set_prior("normal(0.5, 1)", class = "Intercept", 
                    lb = 0)
)

# Prior is the negative part for N(0.5, 1)
mod2 <- brm(
  y ~ 1, 
  data = d,
  chains = 8, iter = 5500, warmup = 500, cores = 4,
  prior = set_prior("normal(0.5, 1)", class = "Intercept", 
                    ub = 0)
)

# Unbounded prior
mod <- brm(
  y ~ 1, 
  data = d,
  chains = 8, iter = 5500, warmup = 500, cores = 4,
  prior = set_prior("normal(0.5, 1)", class = "Intercept")
)

(h <- hypothesis(mod, "Intercept < 0"))
#> Hypothesis Tests for class b:
#>        Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
#> 1 (Intercept) < 0    -0.58      0.28    -1.03     -0.1      34.06      0.97    *
#> ---
#> 'CI': 90%-CI for one-sided and 95%-CI for two-sided hypotheses.
#> '*': For one-sided hypotheses, the posterior probability exceeds 95%;
#> for two-sided hypotheses, the value tested against lies outside the 95%-CI.
#> Posterior probabilities of point hypotheses assume equal prior probabilities.

library(bridgesampling)

bayes_factor(
  bridge_sampler(mod2, silent = TRUE),
  bridge_sampler(mod1, silent = TRUE)
)
#> Estimated Bayes factor in favor of x1 over x2: 75.81310

# Same as:

prior_odds <- 
  pnorm(0, 0.5, 1, lower.tail = TRUE) / 
  pnorm(0, 0.5, 1, lower.tail = FALSE)
  
posterior_odds <- h$hypothesis$Evid.Ratio

posterior_odds / prior_odds
#> [1] 76.32496
```

Alternativly:

```R
(bf <- bayestestR::bayesfactor_restricted(
  mod, 
  hypothesis = c("b_Intercept < 0",
                 "b_Intercept > 0")
))
#> Bayes Factor (Order-Restriction)
#> 
#> Hypothesis      P(Prior) P(Posterior)    BF
#> b_Intercept < 0     0.31         0.97  3.13
#> b_Intercept > 0     0.69         0.03 0.041
#> 
#> * Bayes factors for the restricted model vs. the un-restricted model.

# To compare the two restricted models:
exp(-diff(bf$log_BF))
#> [1] 76.09737
```
