### ISSUE TITLE
Autoregressive effects

### ISSUE THREAD

**Issue by DavWest** [paul-buerkner/brms#320]
Hi Paul,

Autoregressive effects are not always working properly. I only tested some gaussian and ordinal models (univariate and multivariate) and only cor_arma(), cor_ar(), cor_ma(), cor_arr() and cor_bsts() correlation structures.

```
#data
d1 <- data.frame(y1 = ordered(sample(LETTERS[1:4], 100, replace=TRUE, prob=c(0.03, 0.29, 0.27, 0.41))),
                 y2 = ordered(sample(LETTERS[1:4], 100, replace=TRUE, prob=c(0.10, 0.33, 0.46, 0.11))),
                 x1 = rnorm(100),
                 y_gaus1 = rnorm(100),
                 y_gaus2 = rnorm(100))


############################
## autoregressive effects ##
############################

#univariate, gaussian; working
fit1_gaus <- brm(y_gaus1 ~ x1, data = d1, family = gaussian(), autocor = cor_arr())

#univariate, gaussian; only cor_arr() ERROR but other autoregressive terms are working
#cor_bsts not yet implemented
fit2_gaus <- brm(cbind(y_gaus1, y_gaus2) ~ x1, data = d1, family = gaussian(), autocor = cor_arr())

#univariate, ordinal; cor_arr() and cor_arma() working
#cor_ar(), cor_am() not yet implemented?
#cor_bsts() not yet implemented
fit1_ord <- brm(y1 ~ x1, data = d1, family = cumulative(link = "probit", threshold = "flexible"), autocor = cor_arma())
fit2_ord <- brm(y1 ~ x1, data = d1, family = cumulative(link = "probit", threshold = "flexible"), autocor = cor_ar())

#multivariate, ordinal; cor_arr() ERROR, cor_arma() working
#cor_ar(), cor_am() not yet implemented?
#cor_bsts() not yet implemented
fit3_ord <- brm(cbind(y1, y2) ~ x1, data = d1, family = cumulative(link = "probit", threshold = "flexible"), autocor = cor_arma())
fit4_ord <- brm(cbind(y1, y2) ~ x1, data = d1, family = cumulative(link = "probit", threshold = "flexible"), autocor = cor_ar())
```

It also looks like cor_bsts() is not yet implemented for all multivariate models. Do you have plans to implement this feature?

Best,
David

**Comment by paul-buerkner** [comment]
Hi David, there are mutliple things going on. 

(1) There was a bug in `cor_arr()` for multivariate models, which is now fixed in the dev version.

(2) The "not yet implement" is possibly a bit misleading, since I currently have no plans of implementing them for other families (I have removed the "yet" from the error message). In case of (AR)(MA) structures, the reason is mainly that we need some sort of "residuals" for ARMA to make sense, and for many families there is no canonical definition of what resiuals are. Accordingly, such structures are currently only implemented in linear gaussian and student-t models, but I am open to suggestions / Stan / JAGS code that demonstrates how to implement them for other families. 

(3) Just using `cor_arma()` actually does nothing, since it defaults to `cor_arma(p=0, q=0, r=0)`. Accordingly, you will have to specify `p`, `q`, or `r` to make it do anything. For this reason, I just made a small change so that an error is thrown, when all of the three arguments are 0. 

(4) `cor_bsts` is rather special and does not really fit into brms in retrospect. I don't think implementing it in the first place was one of my better ideas. Maybe I will deprecate it at some point and thus I am hesitant to invest much time in generalizing it to certain situations. That said, I just activated it to be usable in multivariate models with estimated residual correlations. I am not sure why I didn't allow it in the first place...

**Comment by DavWest** [comment]
Hi Paul,

Thanks!

With regard to your second comment, I was wandering whether there is some latent process underlying for example ordinal (or logistic) models that can be modelled as "residuals". I digged a little bit into the Stan code and found that the linear predictor mu was modelled as Xc*b. Isn't it possible to model b with some "residual"? And for (non-guassian) multivariate models wouldn't it be possible to use a multivariate distribution (like the guassian multivariate models), which was for example also used in the mvord package (https://cran.r-project.org/web/packages/mvord/vignettes/vignette_mvord.pdf)?

David

**Comment by DavWest** [comment]
Correction. My first suggestion about modelling a "residual" for b isn't a good idea. But the other suggestion might possibly be.

**Comment by paul-buerkner** [comment]
Implementing correlated multivariate ordinal models of the form fitted in **mvord** is conceptually rather different than the other things discussed here in this issue, which deal with autoregressive structures passed to agument `autocor`.

Would you mind opening a new issue for this feature so that we keep the issue list clean?

**Comment by DavWest** [comment]
Sure. No problem.
