### ISSUE TITLE
Zero-one inflated beta distribution

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#34]
Is there a way to use zero-one inflated beta distribution in brms? My variable has lots of zeros and (some) ones, with other values between 0 and 1. I think the zero-one inflated beta distribution is the right distribution for my problem.

**Comment by paul-buerkner** [comment]
Currently, it is not possible, but I could manage to implement it relatively easy (just copy things from the other zero_inflated families). When you say you have some ones, you also need a "one_inflated" family, if you want to use beta, because beta is only defined on ]0,1[.
Of course this is also possible to implement but requires more time.

**Comment by alireza202** [comment]
I can definitely ignore the ones right now. There are not that many, and are of less importance. But zeros can't be neglected. It would be great to implement the zero-inflated beta distribution. I can do it myself, if it's relatively easy.

**Comment by paul-buerkner** [comment]
I will try to do it tomorrow, it shouldn't take too long.

**Comment by alireza202** [comment]
Awesome!

**Comment by paul-buerkner** [comment]
You can now try out the `zero_inflated_beta` family. :-)
I will think about how to implement zero-one-inflated families, but this requires some more work on formula syntax and related features, which takes some time.

**Comment by alireza202** [comment]
This is great! I think this might be enough for me.

**Comment by paul-buerkner** [comment]
Ok, I am going to close this for now. A zero_one_inflated model is currently a bit far away from where I want brms to go. We would have to define 3 processes, one for the zero, one for the one, and the basic process in between. Thus, we would have to define 1 more internal variable, since `main` and `spec` are already in, referring to the main process and to the zero process (when using zero-inflated or hurdle models). I currently do not see another application of the 3rd variable outside of a `zero_one_inflated_beta family`. If we ever need this family or something similar, we can just reopen this issue or make a new one.

**Comment by liamkendall** [comment]
Hi Paul,

I'm currently unable to fit a zero_one_inflated_beta model, with the attached data, despite the response being strictly between 0 and 1 (and including both). Any ideas why it is not working? Thanks!


[data_example.txt](https://github.com/paul-buerkner/brms/files/6284957/data_example.txt)

`
data_example <- read.csv("data_example.csv")

example_zob_model <- brm(d ~ PC1 + (1|Id),
                          data = data_example,
                          family  = "zero_one_inflated_beta")`

`Error: Family 'zero_one_inflated_beta' requires response smaller than or equal to 1.`

**Comment by paul-buerkner** [comment]
The example just works for me. Consider updating your brms. Perhaps that could help. If that doesn't help, I assume there is some numerical issue so consider using something like `d <- ifelse(d > 1, 1, d)`
