### ISSUE TITLE
Automated marginal effect plots

### ISSUE THREAD

**Issue by rubenarslan** [paul-buerkner/brms#35]
As discussed via email, it would be cool to get automatic marginal effect plots to explore models quickly.

In some cases my lack of knowledge about brms internals and formula programming is a bit crippling (ie. not yet a perfect procedure to choose which variables to include in newdata object, nothing yet when random effects aren't to be marginalised).
I also summarise ordinal outcomes myself in a way that may be "impure" and if it's ok, should probably go in the predict method.

Here's what I have so far:
https://gist.github.com/rubenarslan/80ecc20be0e0600b41dc

**Comment by paul-buerkner** [comment]
Thanks, Ruben! Let's see if I can get this implemented within the text week.

**Comment by paul-buerkner** [comment]
Marginal effect plots can now be computed using the `margins_plot` method. I would be very greatful if you could test it with your models, see if everything is working correctly, and also if relevant features are missing. You can find the relevant source code in brmsfit-methods.R and plots.R.

In addition, there a some more decisions to be made and I am happy for any opinions on this:
- [ ] final name of the method
- [ ] final name of the arguments (especially for arguments `effects` and `data`)
- [ ] default value for argument `re_formula`

Some background: 
(1) A quick google search revealed that marginal plots typically mean something different (a bivariate dot plot and some sort of marginal distribution), whereas margins plot seems to be closer to what we do (likely because Stata has a method called `marginsplot`). I am, however, still unsure how to call this method.

(2) Personally, I feel that `effects` is closer to what we mean than `predictors`, as the former naturally comprises both main and interaction effects, but there may also be good arguments against it. The argument name `data` is not essentially wrong, but it doesn't really help in understanding what this argument actually means. Maybe there is a better name for it.

(3) For now, `re_formula` defaults to `NA` that is exclusion of all random effects in the prediction, where as it is set to `NULL` by default in the `predict` etc. methods. Intuitively, I think that a marginal plot should ignore the random effects variance by default, but again I am not sure yet.

**Comment by paul-buerkner** [comment]
From my side, we can close this issue. Ruben, did you find the time to test the method, already?

**Comment by rubenarslan** [comment]
Yes, I did some testing, but I haven't made reproducible test cases yet. I agree with your name choices!

Some notes so far:

1. I got much smaller intervals using the code I sent you for my cumulative models. Looks like predict  instead of fitted to me (cover nearly the whole scale). I may have been doing it wrong though?

2. I tried a re_formula = (1 + menstruation + included * fertile + fertile_mean | variable), ie getting effects by variable. I did not get plots by variable.

3. Separation of new data and effect generation, and plot generation worked well for `effects`. I like how you did it (with plot as the default method), but maybe a selector for the effect to plot would be good, so that I can do something like plot(efflist, "var1:var2") + scale_color_brewer().

4. I don't like geom_bar and geom_errorbar so much as the default when the IV is a factor. geom_bar suggests that it's count data and that 0 is a possible number in a model where it's not (cumulative) and errorbar emphasises the CI limits a lot, even though those are fairly unlikely. As a default, I'd prefer geom_pointrange.

**Comment by paul-buerkner** [comment]
Thanks for the suggestions!

1. Hmm, that's strange. I will have a look at it.

2. Plots by grouping factor are not yet implemented. In fact, I hadn't thought of this option yet... re_formula is just to select what kind of random effects to include in the prediction. Maybe we can have a phone call this week to discuss this.

3. I understand where you are coming from. However, this will likely lead to confusion as you can then specify effects in two ways. I'll see if I can find a good solution.

4. You are right, geom_pointrange is more appropriate here.

**Comment by rubenarslan** [comment]
1. Let me know if it helps if I send you a fit object.

2. Ah ok! Sure, give me a call.

3. Maybe you can just make the return object a named list instead of numbered? Then it's there for people to use, but you don't have the specification machinery twice.

**Comment by paul-buerkner** [comment]
1. Thanks! I'll see if I can reproduce it with my models and if this doesn't work, I'll get back to you.

3. Good idea!

**Comment by paul-buerkner** [comment]
I am now using `geom_pointrange` instead of `geom_bar`. Indeed it is the better plot for marginal effects.

With my models, I cannot reproduce the different CIs, for instance:

```R
fit <- brm(formula = rating ~ treat + period + carry + (1|subject), 
           data = inhaler, family = cumulative)
# both plots look identical
marginal_effects(fit, effects = "treat")
# I removed .brmsfit from the function definitions
plot_efflist(allEffects(fit, predictor = "treat"))
```
Maybe this is because you included the RE terms via `re_formula`, while you did not do so in your plot functions? Another reason might be that `marginal_effects` uses new levels of grouping factors if they are not specified in `data`, while there is no equivalent feature in your `allEffects` function.

Regarding separate plots by levels of a grouping factor, you can simply do (if I understand your goal correctly):

```R
# plot marginal effects of treat separately for the first 12 subjects
# differences are small because there is not much variation between subjects
# you have to match the level names exactly
marginal_effects(fit,  effects = "treat", re_formula = NULL,
                 data = data.frame(subject = 1:12, period = 0, carry = 0))
```

**Comment by rubenarslan** [comment]
Great. You're right, I can reproduce them too. I checked too lazily last time when removing the re_formula.
Maybe we should talk about this plot by group thing, not sure what you suggested is what I meant.

**Comment by paul-buerkner** [comment]
All plots in brms should now use the (probably user-defined) global ggplot theme by default. @rubenarslan would you mind trying it out with your plots? If it works, I guess we can close this issue.

**Comment by rubenarslan** [comment]
Yes, looks great now! Thanks so much.

**Comment by paul-buerkner** [comment]
And thank you so much for your ideas and your help! :-)
