### ISSUE TITLE
Handling a covariate in a multimembership model

### ISSUE THREAD

**Issue by afni-gangc** [paul-buerkner/brms#353]
Suppose that we have a multimembership model of the following form

y_ijk ~ b + alpha_i + beta_j + beta_k + e_ijk

where b is a population effect, alpha_i is the effect at the _i_ th level of a group factor **A**, beta_j and beta_k are the effects from a pair of members B_j and B_k in a group factor **B**. We can model the data y_ijk with

brm(y_ijk ~ 1 + ( 1 | **A** ) + ( 1 | mm(B_j, B_k) ) , ...)

Now I would like to incorporate a quantitative covariate x into the model above. The covariate x is associated with the members in the group factor B. Therefore, the new model becomes

y_ijk ~ b0 + b1 x_j + b1 x_k +  alpha0_i + alpha1_i x_j + alpha1_i x_k + beta1_j + beta_k + e_ijk

which cannot seem to be implemented under the current version of brm(): the difficulty is that I cannot find a way to code the following two pairs of effects: 1)  b1 x_j and b1 x_k and the population level, and 2) alpha1_i x_j and alpha1_i x_k within the group **A**.

**Comment by paul-buerkner** [comment]
The model you are describing in your second model, could be written as follows

```R
y ~ 1 + x1 + x2 + (1 + x1 + x2 | A) + (1 | m(B_j, B_k)) 
```

but I am not sure if this is what you have in mind?

**Comment by paul-buerkner** [comment]
Thanks, that makes sense. Using the same `b_1` in the population-level part is already possible by passing the sum of `x_j` and `x_k` as predictor since `b1 x_j + b_1 x_k = b1 (x_j + x_k)`.

Using the same alphas in the group-level part, however, is not yet implemented, but will definitely make a nice feature. I have yet to think about an appropriate formula syntax for this though.

**Comment by afni-gangc** [comment]
Thanks a lot for the quick implementation, Paul! 

So, for my model

y_ijk ~ b0 + b1 x_j + b1 x_k + alpha0_i + alpha1_i x_j + alpha1_i x_k + beta1_j + beta1_k + e_ijk

I do something like the following?

brm(y_ijk ~ 1 + mmc(x1, x2) + ( 1 + mmc(x1, x2) | **A** ) + ( 1 | mm(B_j, B_k) ) , ...)

Also, does mmc() come with similar options for weighting and scaling like mmc(x1, x2, weights=..., scale=...)?

**Comment by paul-buerkner** [comment]
`mmc` is just for use in group-level terms. For fixed effects terms, you can specify the desired coefficient manually without any new function (see above as well as ?mmc). I am confused by your model since a covariate modeled via `mmc` **only** makes theoretically sense when combined with a multil-membership term. That is, something like `(1 + mmc(x1, x2) | mm(B_j, B_k))` makes sense, but `(1 + mmc(x1, x2) | A)` does not. There is no need to specify weights or scale inside `mmc()` since this information is already provided in the call to `mm()`.
