### ISSUE TITLE
Warning message from rename_pars

### ISSUE THREAD

**Issue by Mamie** [paul-buerkner/brms#387]
I encountered a warning message from rename_pars when trying to run a multilevel model using the brms package. 

Here is my code:
```
library(brms)
library(brmstools)

d <- data.frame(
  BETA = rnorm(10),
  SE = 1,
  VARID = sample(1:5, 10, TRUE),
  POPULATION = factor(rep(1:2, 10)),
  DISEASE = factor(rep(1:2, each = 10))
)
fit <- brm(BETA|se(SE) ~  1 + (0 + POPULATION|VARID) + (0 + DISEASE|VARID), data=d,
           algorithm='meanfield', iter=1000)
```
And it gives the following warning message:

```
Warning message:
In names(x$fit@sim$samples[[i]])[change$pos] <- change$fnames :
  number of items to replace is not a multiple of replacement length
```

**Comment by paul-buerkner** [comment]
When using `algorithm='meanfield'` there seems to be a parameter generated by rstan, which is called `lp__.1`. This confuses brms, because it doesn't appear in `stanfit@sim$fnames_oi`. Not sure what is happening there, but before I do anything about it from the brms side, I will check with the Stan developers whether that's intentional.

**Comment by paul-buerkner** [comment]
@bgoodri said on discourse that it may be a bug in rstan. Anyway, I added a temporary fix for this in the latest github version of brms
