### ISSUE TITLE
Allow ordinal families in mixture models

### ISSUE THREAD

**Issue by mvuorre** [paul-buerkner/brms#389]
Is it possible to allow mixture models with ordinal families (or at least some of them)? [Source suggests](https://github.com/paul-buerkner/brms/blob/0bff1033376b90661121014623661bd78bc65450/R/families.R#L700) that they are not allowed because they might be incompatible with the `disc` parameter. Perhaps they could be allowed for ordinal models where `disc` is set to 1?

My motivation behind this (as usual) is with signal detection models. A nice write-up of the model(s) I have in mind is in Section 4. (p.309) of this paper: <https://www.sciencedirect.com/science/article/pii/S0022249610000027>.

**Comment by paul-buerkner** [comment]
Ensuring compatibility with `disc` turned out to be the smallest of the problems ;-)

Anyway, I think I got it running in the latest github version. I would be grateful for feedback if anything works as expected.

**Comment by mvuorre** [comment]
Thanks!! Would it also be possible to equate the mu parameters?

That is, I think I understand brms' mixture syntax (or maybe not), and am trying to specify this:

<img width="325" alt="screen shot 2018-03-21 at 12 51 30" src="https://user-images.githubusercontent.com/7349270/37724246-b4258e66-2d06-11e8-9b61-bfe10a41172a.png">

I write
```
brm(bf(y ~ 1, mu1 ~ 1 + x, mu2 ~ 1, mu2 = "mu1"),
    family = mixture(cumulative("probit"), cumulative("probit")),
    ...
```

And I get

```
Replacing initial definitions of parameters 'mu2'
Error: Equating parameters of class 'mu' is not allowed.
```

If this is getting too specific, or unnecessarily complicated to implement, don't worry about it. (My understanding is that there's no reason to not allow equating the 'mu's, though, and this could be relaxed by removing a single check.)

**Comment by paul-buerkner** [comment]
How do you identify components if not via mu?

**Comment by mvuorre** [comment]
Do you mean how they should be labeled? Or are you referring to the ordering constraint? Sorry, I don't think I follow.

**Comment by paul-buerkner** [comment]
Sorry my comment was a bit short. In your model above, what exactly is c_k and dx? Maybe we can work out how to fit that in brms, with or without constraining mu?

**Comment by mvuorre** [comment]
OK, thanks, let me elaborate:

c_k are the intercepts (thresholds) of the ordinal model, and I would like those to be constant across the two mixture components (if that is possible). 

d is a parameter for the effect of a 0/1 coded predictor x.

**Comment by paul-buerkner** [comment]
I see. Equating mu would imply fixing the linear predictor parts to the same values and those are the ones you want explicitely to be different, because one contains `item` and the other doesn't. So even if equating mu would be possible, you would not achieve what you want, because you only want the intercepts to be the same.

I can put some code into brms that allows to equate the intercepts in ordinal mixture models, but it seems very much like special case coding, with which I had some bad experiences when it comes to maintaining that sort of feature.

I think what brms needs, generally, is a way to equate certain parameters within linear predictors not just the whole parameter (depending how you put it, the intercepts are part of the linear predictor in ordinal models as well).

That said, if you extract the generated Stan code, equating the intercepts should be trivial. You could even put the stancode / stanmodel back into a brmsfit object, since the in and output doesn't change and rerun the model with brms via

```R
fit <- update(fit_new_stancode, recompile = FALSE)
`````

**Comment by mvuorre** [comment]
Thank you so much for taking the time to look into this. 

This feature is probably not worth the special case coding. However, if you ever get around to implementing the general method for equating parameters within the linear predictor, that would be very nice! (And presumably a generally useful feature.)

Until then, I'll edit the generated Stan code as you suggest. (I can see that it will be quite straightforward.)

Thanks again! (I am not sure if you want this issue closed--fine by me.)

**Comment by paul-buerkner** [comment]
I opened a new issue for the equating parameters thing (#390) so I also think the present issue can be closed.
