### ISSUE TITLE
the "meaning" of uncertainty intervals for a categorical regression in brms

### ISSUE THREAD

**Issue by bachlaw** [paul-buerkner/brms#397]
Paul,

I am struggling to understand the meaning of the uncertainty intervals around parameters provided by the categorical regression summary in `brms`.  

How does the uncertainty of those parameters actually propagate to the output?  `brms` certainly provides a categorical prediction with the net probability of each output category for each observation,  but no uncertainty around those categories.  

If we consider the various odds ratios between the base category and the other categories to be constant, at least vis-a-vis the respective odds-ratios, then arguably the only possible effect of parameter uncertainty can be to increase or decrease the amount of uncertainty going to the base category versus the category involving the parameter in question, with the remaining categorical probabilities remaining fixed. This strikes me as a bit odd in that it's not clear why parameter uncertainty couldn't have spillover effects increasing the likelihood of a different categorical response, but perhaps that is just the limitation of how the multinomial logistic regression is set up. The issue seems important because the prediction scale is where a logistic coefficient seems to have the most meaning, at least to me.

Admittedly this concern applies equally to standard errors reported by `nnet::multinom` or any other multinomial regression program (including obviously Stan itself), but since you have coded a Bayesian solution, I'm wondering if you have any thoughts on this issue or can point to any authorities you have found helpful in working through it. Thanks much.

**Comment by paul-buerkner** [comment]
`predict` basically works the same for all families in the sense that it predicts response values. You see this, if you run `predict(..., summary = FALSE)`. In those predictions goes both the uncertainty of the parameters as well the the probability of the categories given the predictors.

If you want to get uncertainty estimates of the probabilities of each category, use `fitted` instead of `predict`. 

In the future, please ask such questions on the brms-users google group, because more people find my answer there as compared to in a closed issue.

**Comment by bachlaw** [comment]
Got it, and will do.  Thanks.
