### ISSUE TITLE
Simplex + scale parametrization of hierarchical sigma

### ISSUE THREAD

**Issue by maltelau** [paul-buerkner/brms#400]
With hierarchical models, it can be hard to put priors on the scale of the random effects. One way to deal with it is to have 1 scale parameter for the total variation of the random effects, and a K-simplex to stand for the distribution among the effects. This is a simplification that comes with it's own set of assumptions of course, but it could be good for computational reasons. In the problem I'm currently working on, this makes the difference between stalling completely (no new samples for 12+ hours with refresh=1) and getting samples consistently.

An example model is
```{r}
m = brm(mpg ~ disp + (1 + disp|gear), dat = mtcars)
```
where the scale of the random effects (intercept and disp by gear) is modelled by brms as:
```{stan}
parameters {
  vector<lower=0>[M_1] sd_1;  // group-level standard deviations
}
model {
  target += student_t_lpdf(sd_1 | 3, 0, 10)
    - 2 * student_t_lccdf(0 | 3, 0, 10); 
}
```
What I'm asking is for the option to instead get a model like this:
```{stan}
parameters {
  simplex[M_1] sd_1_simplex;
  real<lower=0> sd_1_scale;
}
transformed parameters {
  vector<lower=0> [M_1] sd_1 = sd_1_simplex * sd_1_scale;
}
```
which allows us to give a prior representing the total scale of the random effects, and optionally (stan defaults to uniform, ie proportion 1/K for each of the K random effects) the relative scales of the different random effects (the simplex).
```{stan}
model {
  target += student_t_lpdf(sd_1_scale | 3, 0, 10) - M_1 * student_t_lccdf(0 | 3, 0, 10); 
}
```
(not 100% on putting `M_1` in the prior, but it seems to be what you were doing, even though you weren't spelling it out like that)

**Comment by paul-buerkner** [comment]
That's a very good idea! What I am thinking about is whether we should go for supporting across all random effects or "just" across the random effects of a particular grouping factor. What do you think?

**Comment by paul-buerkner** [comment]
You understood me correctly in this sense that I was thinking of the application range of one simplex parameter. In particular, I was thinking about situation (a) (multiple grouping factors `gear` and `vs` in your case). As you point out, this is neither a mathematical problem nor a problem of specifying this in Stan. Instead, we have to think of a reasonable interface in brms. If we want to allow the same simplex across grouping factors (example (a)), the interface will get **a lot** harder. Probably, we can make an interface solely via the `prior` argument without any change in the formula, because I think this is essenentialy an issue of the prior (even though the parameterziation changes internally).

**Comment by jgabry** [comment]
This reminds me a bit of the “decov” prior for covariance matrices we use
in rstanarm

http://mc-stan.org/rstanarm/articles/glmer.html#priors-on-covariance-matrices

**Comment by paul-buerkner** [comment]
This is now possible as a special case of the R2D2 prior in brms. Hence I will close this issue.
