### ISSUE TITLE
predictions of ordinal variables

### ISSUE THREAD

**Issue by bachlaw** [paul-buerkner/brms#42]
One of the best features of this package is its extensive support for ordinal regression.  Thank you for this.

However, two issues.  First, is there anyway to "predict" anything other than classes from, say, a cumulative ordinal regression?  POLR and Ordinal both support the ability to do this (type='prob' or 'cum prob'), and since my categories actually have "value" in a sense this ability would be very useful to me.  Or perhaps we can do something equivalent by working through the classes currently being predicted?

Second, when using meanfield VB, I am getting "log of 0" errors when using probit for the initiating values.  Logit works fine.  All output values / categories are between -1 and +2 and have been converted to ordered factors.  If this sounds like a bug, please let me know and I'll try to post a toy that can reproduce it.  

Again, many thanks.

**Comment by paul-buerkner** [comment]
Thanks for your interest in brms!

(1) I am not sure if I understand you correctly. When you want the predicted probabilites, you can use the `fitted` method. It will return a 3 dimensional array (the third dimension is equal to the number of categories). Here is an example:

```R
fit <- brm(rating ~ treat + period + carry, 
           data = inhaler, family = cumulatvie(), 
           prior = set_prior("normal(0,5)"))
# return predicted probabilities only for 3 observations here
fitted(fit, newdata = inhaler[c(1, 150, 300), ])

# output
, , P(Y = 1)

   Estimate  Est.Error   2.5%ile  97.5%ile
1 0.6878304 0.03532563 0.6184677 0.7548324
2 0.6878304 0.03532563 0.6184677 0.7548324
3 0.5314791 0.03478030 0.4630482 0.5995110

, , P(Y = 2)

   Estimate  Est.Error   2.5%ile  97.5%ile
1 0.2928746 0.02965866 0.2341233 0.3501148
2 0.2928746 0.02965866 0.2341233 0.3501148
3 0.3938830 0.02595518 0.3442861 0.4445546

, , P(Y = 3)

    Estimate   Est.Error     2.5%ile   97.5%ile
1 0.01516903 0.006567289 0.005337136 0.03070662
2 0.01516903 0.006567289 0.005337136 0.03070662
3 0.04825797 0.013060844 0.026449633 0.07727163

, , P(Y = 4)

     Estimate   Est.Error      2.5%ile   97.5%ile
1 0.004125913 0.002959327 0.0006973798 0.01189703
2 0.004125913 0.002959327 0.0006973798 0.01189703
3 0.026379934 0.010594791 0.0102511364 0.05078743
```

The `Estimate` columns contains the predicted probabilities an the other columns provide information on the uncertainty in these estimates. Is this what you wanted? If not, please provide a small example of the desired feature using polr or ordinal.

(2) VB algorithms (meanfield and fullrank) are currently experimental algorithms of Stan. Meanfield in particular may not work well even for relatively simple models (I wouldn't consider ordinal models to be particularily simple). Moreover, it reliably crashes my Windows laptop at the moment... Even if it works you should still rely on the NUTS sampler for final estimation. It is possible that your problem is a bug. However (given that the model works with sampling) it would likely be in Stan itself not in brms. That said, I am happy to see a toy example, but I am not sure, if I can provide a solution for it.

**Comment by paul-buerkner** [comment]
@bachlaw Just a quick follow up to ask you if you were able to extract the predicted probabilities of ordinal models?

**Comment by paul-buerkner** [comment]
Closing this as there hasn't been a response from the OP for over a month.
