### ISSUE TITLE
Rename summary columns of predict() and related methods

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#425]
When `predict` and related methods are called with `summary = TRUE`, the column names of the returned matrix are:

```R
colnames(predict(., summary = TRUE)) 
> "Estimate"  "Est.Error" "2.5%ile"   "97.5%ile" 
```

The names of the quantile columns are suboptimal since they aren't proper R variable names. Thus, if included in a data.frame, they cannot be extracted via `$` or any tidyverse extraction methods (but have to be renamed first).

For this reason, I would love to rename the quantile columns. Any suggestions are very welcome!

@jgabry, @mjskay, @rubenarslan

**Comment by ASKurz** [comment]
I’ve always liked *lower level* and *upper level*, which might lead one to do `ll_2.5` and `ul_97.5`. Or perhaps it’d be better to streamline with `q` standing for quantile and use `q_2.5` and `q_97.5`.

**Comment by paul-buerkner** [comment]
Thanks! I like lower and upper too, but I think we need to include the quantile value in the names, because we get more than two quantiles returned if argument `probs` is of length greater two.

**Comment by jgabry** [comment]
Out of curiosity, any idea how often predict with summary=FALSE is being
used with brms rather than posterior_predict?

**Comment by jgabry** [comment]
makes sense. What is Est.Error reporting? If you’re changing names maybe rename it to something that indicates the interpretation? E.g. SD, MAD_SD, etc.

**Comment by paul-buerkner** [comment]
Depending on argument `robust` its either SD or MAD_SD (same with Estimate being either mean or median).

**Comment by jgabry** [comment]
Ok so scrap my idea. Probably not good to change column names based on the
robust argument. Well, it’s actually maybe preferable pedagogically at an
early stage but not for a real applied statistics workflow.

**Comment by paul-buerkner** [comment]
I would also like to change the output to a `data.frame` instead of a matrix. If `summary = FALSE`, the output would remain a matrix though. Any thoughts?

**Comment by rubenarslan** [comment]
I don't love spelling out the percentiles, but all I have to do is wrap them in backticks `` `2.5%ile` `` for $ or tidyverse, and RStudio can automate that, so it doesn't hurt that much. 

Data.frame instead of matrix would be a good default though, I've never needed the matrix representation when using `summary = TRUE`.

**Comment by mjskay** [comment]
Since you want to maintain a one-row-per-prediction format, let me propose a possible criterion for helping to decide: given output with multiple intervals per prediction, how hard is it to convert the output into a format where each interval for each prediction has its own row (e.g., an `estimate`, `lower`, `upper`, and `prob` column, or equivalent)? That would be the canonical "tidy" format in my opinion---quantile values would not be in the columns names at all, since data (or in this case, meta-data) is easier to work with when stored in table cells rather than column names. In my experience, this format is also the easiest to use with ggplot.

Since that format would break the one-row-per-prediction semantics of `predict`, we could instead judge possible column names by how hard it is to convert the output of `predict` into a "tidy"er format. Below is my attempt to do so using different proposed formats for a hypothetical data frame where each estimate has two intervals.

**ll/ul prefix labelled with quantile values:**

``` r
data_frame(
    # fake hypothetical output of predict()
    estimate = c(1,2,3,4), 
    ll_2.5 = estimate - 0.5,
    ll_5 = estimate - 0.4,
    ul_95 = estimate + 0.4,
    ul_97.5 = estimate + 0.5
  ) %>%
  gather(limit, value, -estimate) %>%
  separate(limit, into = c("side", "p"), sep = "_", convert = TRUE) %>%
  mutate(
    # rounding needed because floating point errors can screw up the spread() call below
    interval_prob = round(ifelse(side == "ll", 1 - p/100 * 2, p/100 * 2 - 1), 2)
  ) %>%
  select(-p) %>%
  spread(side, value)
#> # A tibble: 8 x 4
#>   estimate interval_prob    ll    ul
#> *    <dbl>         <dbl> <dbl> <dbl>
#> 1     1.00         0.900 0.600  1.40
#> 2     1.00         0.950 0.500  1.50
#> 3     2.00         0.900 1.60   2.40
#> 4     2.00         0.950 1.50   2.50
#> 5     3.00         0.900 2.60   3.40
#> 6     3.00         0.950 2.50   3.50
#> 7     4.00         0.900 3.60   4.40
#> 8     4.00         0.950 3.50   4.50
```

**q prefix labelled with quantile values:**

``` r
data_frame(
    estimate = c(1,2,3,4), 
    q_2.5 = estimate - 0.5,
    q_5 = estimate - 0.4,
    q_95 = estimate + 0.4,
    q_97.5 = estimate + 0.5
  ) %>%
  gather(limit, value, -estimate) %>%
  separate(limit, into = c("q", "p"), sep = "_", convert = TRUE) %>%
  mutate(
    # extra work needed here to recover the side
    side = ifelse(p < 50, "ll", "ul"),
    # rounding needed because floating point errors can screw up the spread() call below
    interval_prob = round(ifelse(side == "ll", 1 - p/100 * 2, p/100 * 2 - 1), 2)
  ) %>%
  select(-p, -q) %>%
  spread(side, value)
#> # A tibble: 8 x 4
#>   estimate interval_prob    ll    ul
#> *    <dbl>         <dbl> <dbl> <dbl>
#> 1     1.00         0.900 0.600  1.40
#> 2     1.00         0.950 0.500  1.50
#> 3     2.00         0.900 1.60   2.40
#> 4     2.00         0.950 1.50   2.50
#> 5     3.00         0.900 2.60   3.40
#> 6     3.00         0.950 2.50   3.50
#> 7     4.00         0.900 3.60   4.40
#> 8     4.00         0.950 3.50   4.50
```

Switching to `q` instead of `ll`/`ul` adds additional complexity to recovering the relationship between the upper and lower limits, because you first have to determine if a given column is an upper or lower limit.

That said, I would argue both of these formats involve a decent amount of work to get from raw form into a tidy table. Most of the work stems from one problem: semantically, `ll_2.5` and `ul_97.5` are linked (they are from the same interval), just as `ll_5` and `ul_95` are linked, but neither pair is labelled as such. We need to recover this relationship first in order to tidy the table.

Therefore, I would perhaps argue for something like this:

**ll/ul prefix labelled according to the interval probability:**

``` r
data_frame(
    estimate = c(1,2,3,4), 
    ll_95 = estimate - 0.5,
    ll_90 = estimate - 0.4,
    ul_90 = estimate + 0.4,
    ul_95 = estimate + 0.5
  ) %>%
  gather(limit, value, -estimate) %>%
  separate(limit, into = c("side", "interval_prob"), sep = "_", convert = TRUE) %>%
  spread(side, value)
#> # A tibble: 8 x 4
#>   estimate interval_prob    ll    ul
#> *    <dbl>         <int> <dbl> <dbl>
#> 1     1.00            90 0.600  1.40
#> 2     1.00            95 0.500  1.50
#> 3     2.00            90 1.60   2.40
#> 4     2.00            95 1.50   2.50
#> 5     3.00            90 2.60   3.40
#> 6     3.00            95 2.50   3.50
#> 7     4.00            90 3.60   4.40
#> 8     4.00            95 3.50   4.50
```

With my second-favorite suggestion being something like the *ll/ul prefix labelled with quantile values* format, since it saves one line over the *q prefix labelled with quantile values* format when tidying.

**Comment by rubenarslan** [comment]
The problem with the ll/ul notation is that people don't have to specify intervals, e.g. they can call `probs = c(0.2, 0.5, 0.9)`. I don't know how often people want to do that though. You could force the people using this uncommon approach to jump through the hoop of always specifying an interval (and maybe discarding one limit).

**Comment by paul-buerkner** [comment]
Thanks @mjskay! This is certainly a good approach to determine reasonable names! 

I share the concern of @rubenarslan because we currently do not enforce any restrictions on the supplied `probs` argument. It may be worth restricting its flexibility, but I don't know how many users this change will affect. In particular disallowing the `probs = 0.5` case seems somehwat problematic to me.

I agree that this is worth standardizing across brms, rstanarm and possibly other packages.

**Comment by mjskay** [comment]
Ah makes sense, in that case `q_` seems sensible.

**Comment by paul-buerkner** [comment]
Thanks for all the ideas and feedback!!

My current take would be `Q<quantile>` or `q<quantile`, for instance `Q97.5`. The upper case version is more consitent with the `Estimate` and `Est.Error` names which I am hesitant to change right now. Are there any arguments against this approach?

**Comment by paul-buerkner** [comment]
The names of the quantile columns have now been changed in the dev version. Thank you all for participating in this discussion!

**Comment by jgabry** [comment]
@paul-buerkner this is going to result in errors in any existing code out there that uses the old names, right?

**Comment by paul-buerkner** [comment]
yes indeed...

Jonah Gabry <notifications@github.com> schrieb am Mi., 9. Mai 2018, 17:59:

**Comment by jgabry** [comment]
To avoid that you could probably do something similar to what I did when deprecating old ways of accessing estimates from loo objects: https://github.com/stan-dev/loo/commit/744623592bab578975ed5d16b3447f572c6ce44a. It was a hassle but avoids breaking backwards compatibility.

**Comment by paul-buerkner** [comment]
Nice! The problem I see is that the class of the output will likely be changed rather quickly mostly from matrix to data.frame in which case the solution won't work anymore. Also, we had to include the deprecated columns as well, which would likely lead to more confusion than doing good. I think the solution is nicely done for custom list classes, but not sure how well this works for matrices.

**Comment by jgabry** [comment]
Oh, I was thinking that with summary=T you had decided to return a data frame. In that case I think this could work, but for a matrix I agree it wouldn’t work well.

**Comment by paul-buerkner** [comment]
Initially, I wanted to convert it to a data.frame, but then I realized that the result may actually be an array in some cases with the most important case being multivariate models but also (univariate) ordinal models.
