### ISSUE TITLE
Make a "tidy" method for brmsfit objects

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#43]
See https://github.com/dgrtwo/broom.

**Comment by alireza202** [comment]
+1

**Comment by joelgombin** [comment]
That'd be great indeed. I don't think it should be too difficult since there already is a tidyer for MCMC objects, including Stan (see https://github.com/dgrtwo/broom/blob/master/R/mcmc_tidiers.R)

**Comment by jgabry** [comment]
A while ago I made a pull request to broom fixing a small bug in the MCMC
tidiers and also more recently a pull request adding tidiers for
rstanarm, but they're both still sitting there untouched, as are about 10
other pull requests. So I'm not sure if broom is being actively developed
at the moment. Looks like only 1 commit in the past few months. So probably
no need to worry about this at least until the author starts looking at PRs
again. That is, unless you want to include the tidiers in brms instead of
in broom.

**Comment by paul-buerkner** [comment]
Thanks Jonah, that's good to know! It is probably not ideal to encourage others to make pull requests and then not to maintain the package... ;-)

My plan was indeed to include the methods in broom, and it may lead to some backwards compatibility issues if I first included it in brms and then moved to broom.

**Comment by joelgombin** [comment]
I tested using the MCMC tidier from broom, it works fine on the `brmsfit$fit`. But of course it could make sense to use the richer information that the `brmsfit` object holds.

**Comment by paul-buerkner** [comment]
That's good to know, thanks!

**Comment by paul-buerkner** [comment]
As soon as the PR for broom has been merged (see https://github.com/dgrtwo/broom/pull/149), this issue can be closed.

**Comment by bbolker** [comment]
Bump, would love to see this incorporated ...

**Comment by paul-buerkner** [comment]
Me too! I made a pull request to **broom** on the 12. of July but it is still sitting there untouched along with over 10 other pull requests...

**Comment by paul-buerkner** [comment]
The PR to **broom** has finally been merged! :-)
