### ISSUE TITLE
Auto-scale and rescale

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#440]
I wonder if you would consider a feature that would automatically scale all continuous inputs so their standard deviation is 1/2 and mean-centre all binary inputs -- so as to allow priors to be easily chosen. Then to rescale the posteriors back to the original units?

**Comment by paul-buerkner** [comment]
I thinks that's a feature worth discussing. A few questions up front:

1) I assume we should center continuous predictors a well, right?
2) What kind of mean-centering do you have in mind for binary inputs?
3) What shell we do with categorical predictors with more than two categories?
4) What should be the scope of the scaling? Should it affect only "fixed" effects or also the "random effects"?

**Comment by andymilne** [comment]
Hi Paul

1. Yes, everything centred.

2. Subtracting their mean (as suggested by Gelman et al, p.5, https://arxiv.org/pdf/0901.4011.pdf)

3. I'm not completely sure. But if we have a variable with N categories, and we assume each category occurs the same amount of times (as in a balanced experimental design), the standard deviation of each of the categories (initially dummy/binary coded) would be sqrt((N-1)/N^2), so they would be scaled so as to make their standard deviation 1/2. So if N = 2, no scaling is required; if N = 3, scale by approx 1.06; if N = 4, scale by approx 1.15; etc. Then subtract the mean. Or, do without scaling and just mean-centre. Maybe there is an established method?

4. I would assume the standard deviations and correlations in the group effects would be in the same scale as the transformed variables

Of course, most of the above are trivial for the user to do to the data before fitting the model, but the transform of the posterior back to the original units is not, and would be a real time-saver when those original units are meaningful.

**Comment by paul-buerkner** [comment]
So basically, we would take all columns of the design matrix, scale them to SD 1/2 and center them around zero? That's a doable procedure. The centering of the columns is already done internally to improve sampling speed (without changing the output).

What we can't do is to allow some special cases for factors because of the infinite number of potential codings users can choose from. Also, everything that works before creating the design matrix will require too much special case coding I guess.

One more question. Why isn't it trivial to rescale the posterior samples? After all it is just a divison of the obtained sampled by 2 times the SD.

**Comment by andymilne** [comment]
Yes to all you say. I agree that keeping scaling for factors simple makes more sense. 

Re the rescaling, it is just that it is convenient for the user to simply use summary(mdl) or stan_plot(mdl), etc, and see everything in the original scale without having to faff around with additional coding. More work for you, less for us :-) But I think it would be an appealing feature because there are many cases where a user having come from a non-Bayes background may feel this is all an additional task they didn't have to bother with before, and it's a barrier.

**Comment by paul-buerkner** [comment]
That indeed makes sense to me. Any comments from @jgabry or @avehtari about this idea?

**Comment by avehtari** [comment]
>  a feature that would automatically scale

I say no for automatic. It has to be explicit choice by the modeler. 

> so as to allow priors to be easily chosen

I would think it would be easier to choose good priors knowing the original scales?

>  all continuous inputs so their standard deviation is 1/2

Andrew regrets proposing this, and there are many others, too, that think that 1 would be better, but even then it is not sensible for all covariates but you need to know what you are scaling. Some of the covariates might even have non finite sd and then scaling by empirical sd will be bad.

> More work for you, less for us :-) 

There will be too many cases where automatic transformation will make some one loose their mind and to get it certainly work for everything, it would need to go to C++ level.

I suggest instead to provide a helper function for scaling data, with different options for how to transform (sd, interquartile range, rank normalization, log, sqrt, etc) and other function for mapping predictions to untransformed scale, When used for target, one function could provide Jacobian for loo. But all this would better be explicit.

**Comment by andymilne** [comment]
Explicit choice -- absolutely. The default should be no scaling.

> Some of the covariates might even have non finite sd and then scaling by empirical sd will be bad.

> There will be too many cases where automatic transformation will make some one loose their mind and to get it certainly work for everything, it would need to go to C++ level.

I would think that for the vast majority of data used in regression, such issues (infinite standard deviation) would not occur. Maybe there just needs to be clear warnings given if the scaling does fail. 

> I suggest instead to provide a helper function for scaling data, with different options for how to transform (sd, interquartile range, rank normalization, log, sqrt, etc) and other function for mapping predictions to untransformed scale, When used for target, one function could provide Jacobian for loo. But all this would better be explicit.

Additional options like these make a lot of sense!

**Comment by jgabry** [comment]
I definitely understand the motivation for this feature, but from both a robust user workflow and software dev perspective I strongly prefer any explicit rescaling of variables to be done by the user ahead of time.

**Comment by andymilne** [comment]
The user would explicitly declare that the variables should be scaled then rescaled (with the default being no scaling, of course) and the scaling method used (as per Aki's comments). I think the convenience of this, for the user, would be significant. But maybe I don't fully understand what you think the concerns would be regarding robustness of user workflow and dev perspective. Presumably these would be mitigated if the options were explicitly made in the call to brm?

**Comment by paul-buerkner** [comment]
Thanks Jonah and Aki for your feedback! Of course, **if** such a feature ended up being implemented it would not be the default and instead had to be specified explicitely via, say, `brm(..., autoscale = TRUE)`.

Currently, we have two proposals. 1) Do it internally and directly output the unscaled coefficients although the scaled coefficients are those being fitted. 2) Provide explicit functions to be called before and after the model fitting to transform and backtransform variables / coefficients.

1) concerns me not just because of the problems Aki pointed out, but also because it is a lot of work to implement and maintain the feature. Let me explain a little bit more. The modeling options you have in brms are so large that the scope of the scaling is not trivial to determine. Of course it would affect the population-level coefficients and possibly also the group-level coefficients, but how about all the coefficients of special effects terms such as `me()` or `cs()`? And then there are things we cannot scale at all such as monotonic effects. Due to the modularized internal structure of the brms models, we had to apply the scaling and rescaling at many different points in the code requiring non-negligable amount of special case coding. Also, if we implemented such a feature we would always have to think of whether / how to handle it for new terms added in the future. To summarize I don't think this is a viable option given that the actual benefit of the user is just to have the coefficients automatically re-scaled to the original scales (the data preparation stuff is trivial from the users' side).

2) That's certainly something to consider. However, I think this is not necessarily something to implement in brms, at least not all the data prepration stuff beforehand. That's better done in packages concerned with data handling. The explicit re-scaling of coefficients could be done in brms, but to some amount we already have this feature. If a variable `x` was scaled by `SD = 20`, say, we could apply the rescaling easily via `hypothesis(fit, "x / 20 = 0")`.

There are more things I could discuss but I think the arguments above rather speak against such a feature (in particular if option (1) was the goal). Option (2) is ok but this may not be something that needs to be implemented in brms directly.

**Comment by andymilne** [comment]
Re option 1, would it still be problematic if `autoscale = TRUE` applies only to standard predictors (i.e., not the special predictor terms such as `me()`, `cs()`)? If the user chooses `autoscale = TRUE` for a model with such terms, there is a warning that only standard predictors will be scaled. 

Option 2, I agree, sounds more like something better handled outside brms.

**Comment by avehtari** [comment]
> I would think that for the vast majority of data used in regression, such issues (nonfinite standard deviation) would not occur.

Oh, you've been lucky with your data!

>  Maybe there just needs to be clear warnings given if the scaling does fail.

How do you define fail? Universal default scaling is as impossible as universal default model.

> had to be specified explicitely via, say, brm(..., autoscale = TRUE)

I would strongly prefer a separate function, so that the data transformation is made first and sensibility of the data transformations are checked before fitting a model.

> 2) Provide explicit functions to be called before and after the model fitting to transform and backtransform variables / coefficients.

I support this approach.

> That's better done in packages concerned with data handling.

And there are already packages doing these, although I think they don't have functions for the after fitting work.

So maybe it would be good to check what is available already and how they could work with brns and rstanarm?

**Comment by paul-buerkner** [comment]
I agree with you, Aki. I don't really like option one (build stuff into brm directly) even if we strongly restrict its range of application. My `brm(..., autoscale = TRUE)` "proposal" was just an example of how one could define a user interface. After some thought I don't like adding a new argument to `brm` just for a rather special convenience functionality even if we had agreed on building it into `brms` directly. 

Accordingly, I think that we should go with option 2, that is find outside functionality to scale data and potentially also explicitely rescale posterior samples after model fitting.

**Comment by andymilne** [comment]
Thank you for taking the time to consider these suggestions.

**Comment by paul-buerkner** [comment]
@andymilne Thank you for bringing up the feature request! As you can see we take the ideas of users very seriously. As I said above, from a dev perspective, the costs of implementing and maintaining this feature as well as the concerns Jonah and Aki brough up outweigh the potential benefits we expect users to have. During the last three years working on brms, I have implemented many things I later wished I had not, as they complicated the internal structure and made it hard to make progress. That's why I have grown to be more conservative when it comes to new features.

**Comment by avehtari** [comment]
@andymilne I think support functions for data transformations would be very useful, so I hope this doesn't end here even if brms is not the place for this. Maybe tidybayes?

**Comment by japhir** [comment]
Hi, a bit late to the party, but I was trying to see whether scaling my input parameters manually made a difference in my model fits (except for making setting some priors a bit less intuitive).

I'm now confused by the `brms(..., normalize)` parameter. Does this mean the same as what is discussed in this thread or not?

If I look at the generated stan code, I see some lines in the `transformed_data` section that imply that the data are centered (mean is subtracted) but not normalized `(x - mean(x)) / sd(x)` but I've only just started using stan and brms and am a little lost here.

**Comment by paul-buerkner** [comment]
Hi, please ask brms related question on https://discourse.mc-stan.org/c/jobs/33

**Comment by japhir** [comment]
Ok thank, I thought it was related to this feature discussion, but I've now created [a post](https://discourse.mc-stan.org/t/brms-input-scaling-clarification/23601). :)

**Comment by awaldman123** [comment]
Dear All,

I'm new to brms and I've posted here: https://discourse.mc-stan.org/t/scale-continuous-predictors/24333/3

However, I stumbled across this thread and wanted to see what ultimately came of this? Is there documentation of explicit functions to call for scaling before model building and rescaling afterwards? Is anything automatically handled?

**Comment by japhir** [comment]
See the [post](https://discourse.mc-stan.org/t/brms-input-scaling-clarification/23601/3?u=japhir) by @martinmodrak  who helped me understand.

**Comment by awaldman123** [comment]
Thanks! I looked and see that predictors are centered but not scaled. Would it be advisable to scale continuous predictors outside the package before model fitting? If so, how would I back transform the coefficients afterwards? I see this thread discussed providing some set functions or guidance to do so but couldn't find anything. Thanks for your help! I'm very new to the package and Bayesian approaches in general.

**Comment by martinmodrak** [comment]
Please keep this place for discussing bugs/features and brms development. To get help with your analysis, head to https://discourse.mc-stan.org (as you already did).

**Comment by awaldman123** [comment]
My apologies, I thought this was related to this particular feature request and thought it may reopen the discussion.
