### ISSUE TITLE
Dirichlet and Multinomial Models

### ISSUE THREAD

**Issue by paul-buerkner** [paul-buerkner/brms#463]
The Dirichlet distribution is a multivariate generalization of the beta distribution and may not only be used as prior for some parameters but also as response distribution if the response is a probability vector of more than two categories. I am not yet sure about an appropriate interface for this model, because it requires multiple columns as response input, but maybe I get an idea at some point. The implementation can otherwise closely follow that of the `categorical` distribution.

**Comment by jamesrrae** [comment]
Great. This would address the issue I raised in this feature request, no?:

https://github.com/paul-buerkner/brms/issues/396

**Comment by paul-buerkner** [comment]
Not exactly. The Dirichlet distribution is not a multivariate distribution of **correlated** (in the sense of a correlation matrix) beta variables. Rather the dirichlet distribution is to beta what categorical is to bernoulli and neither of them is multivariate in the sense of #396.

**Comment by jamesrrae** [comment]
That's too bad. I was hopeful that it may have resolved the issue that comes up in data I come across pretty frequently (i.e., multiple beta variables)!

**Comment by paul-buerkner** [comment]
I think a reasonable way to specify the response of a Dirichlet model would be to use a matrix column in the data. For instance

```r
A <- rbind(
  c(0.2, 0.3, 0.5),
  c(0.8, 0.1, 0.1)
)
df <- data.frame(x = rnorm(2)
df$A <- A
brm(A ~ x, data = df, family = Dirichlet())
```

**Comment by paul-buerkner** [comment]
The same structure could be used to implement multinomial models. Updating the title accordingly.

**Comment by szuniga07** [comment]
Thanks for this post, Paul. I am very new to BRMS thanks to a great recommendation from Frank Harrell. I want to do a simple multinomial logistic model with only a categorical X (eventually, outcome ~ medical_centers). In a general way, how would you set a prior argument with a 15 level categorical X? E.g., brm(A ~ x, data = df, family = Dirichlet(), set_prior=?). I apologize for what obvious things I have missed.

**Comment by szuniga07** [comment]
Thanks, Paul. I will go ahead and do that. Thanks again for starting this section.

**Comment by szuniga07** [comment]
P.s. Thanks again for your reply. I will delete my posts by the end of the day so it doesn't clutter up that page. 
Best,
Steve

On September 8, 2018, at 1:24 AM, Paul-Christian Bürkner <notifications@github.com> wrote:

I thinks this may not be the right place to ask since this is about multinomial responses. I would you suggest, you first look at the doc of ?set_prior first. If you still have questions, ask at https://discourse.mc-stan.org/

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/paul-buerkner/brms","title":"paul-buerkner/brms","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/paul-buerkner/brms">https://github.com/paul-buerkner/brms</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paul-buerkner in #463: I thinks this may not be the right place to ask since this is about multinomial **responses**. I would you suggest, you first look at the doc of `?set_prior` first. If you still have questions, ask at <a href="https://discourse.mc-stan.org">https://discourse.mc-stan.org</a>/"}],"action":{"name":"View Issue","url":"<a href="https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172">https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172">https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172</a>", "url": "<a href="https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172">https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [paul-buerkner/brms] Dirichlet and Multinomial Models (#463)", "sections": [ { "text": "", "activityTitle": "**Paul-Christian Bürkner**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@paul-buerkner", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"paul-buerkner/brms\",\n\"issueId\": 463,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"paul-buerkner/brms\",\n\"issueId\": 463\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172">https://github.com/paul-buerkner/brms/issues/463#issuecomment-419623172</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349920028\n}" } ], "themeColor": "26292E" } ]

**Comment by paul-buerkner** [comment]
Multinomial and Dirichlet models can now be estimated in the GitHub version of brms.

**Comment by szuniga07** [comment]
Thank you very much for the update, Paul.

Best wishes to you in the new year.

Sincerely,
Steve

On January 30, 2019, at 6:22 AM, Paul-Christian Bürkner <notifications@github.com> wrote:

Multinomial and Dirichlet models can now be estimated in the GitHub version of brms.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/paul-buerkner/brms","title":"paul-buerkner/brms","subtitle":"GitHub repository","main_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/header.png">https://github.githubassets.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/avatar.png">https://github.githubassets.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/paul-buerkner/brms">https://github.com/paul-buerkner/brms</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paul-buerkner in #463: Multinomial and Dirichlet models can now be estimated in the GitHub version of brms."}],"action":{"name":"View Issue","url":"<a href="https://github.com/paul-buerkner/brms/issues/463#issuecomment-458961100">https://github.com/paul-buerkner/brms/issues/463#issuecomment-458961100</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/paul-buerkner/brms/issues/463#issuecomment-458961100">https://github.com/paul-buerkner/brms/issues/463#issuecomment-458961100</a>", "url": "<a href="https://github.com/paul-buerkner/brms/issues/463#issuecomment-458961100">https://github.com/paul-buerkner/brms/issues/463#issuecomment-458961100</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by Robinlovelace** [comment]
Just a follow-up on this, I have an application for Dirichlet regression: estimating the % of trips in cities, zones and desire lines made by different modes of transport such as car, bike, walk. 

Just discovered that you can do it in a Bayesian framework with `brms`, great work @paul-buerkner! FYI the minimal example I put together based on the code above was as follows:

```r
# install.packages("brms")
library(tidyverse)
library(brms)
A = rbind(
  c(0.2, 0.3, 0.5),
  c(0.8, 0.1, 0.1)
)
df = data.frame(x = rnorm(2))
df$A = A
m = brm(A ~ x, data = df, family = dirichlet())

res  = predict(m, data.frame(x = 0:3))
res_matrix = res[, 1, ]
rowSums(res_matrix)
res_df = as.data.frame(res_matrix) %>% 
  mutate(x = 0:3) %>% 
  pivot_longer(matches("[0-3]"))
ggplot(res_df) +
  geom_area(aes(x, value, fill = name))
```

Which generated this:

![image](https://user-images.githubusercontent.com/1825120/68551551-f893ba00-0405-11ea-9172-e315a1ee5fd3.png)

Out of interest, would you say that this is a good approach to tackle the issue of predicting mode splits with confidence intervals? See here for some city data I've been looking at, would be great to get a solid predictive model of cycling so that you could predict the % increase with changes to multiple parts of transport systems:

https://github.com/ATFutures/who3/tree/master/scenarios

**Comment by szuniga07** [comment]
Thank you for this. Very much appreciated.

Best,
Steve

On November 10, 2019, at 2:05 PM, Robin <notifications@github.com> wrote:

Just a follow-up on this, I have an application for Dirichlet regression: estimating the % of trips in cities, zones and desire lines made by different modes of transport such as car, bike, walk.

Just discovered that you can do it in a Bayesian framework with brms, great work @paul-buerkner! FYI the minimal example I put together based on the code above was as follows:

# install.packages("brms") library(tidyverse) library(brms) A = rbind( c(0.2, 0.3, 0.5), c(0.8, 0.1, 0.1) ) df = data.frame(x = rnorm(2)) df$A = A m = brm(A ~ x, data = df, family = dirichlet()) res = predict(m, data.frame(x = 0:3)) res_matrix = res[, 1, ] rowSums(res_matrix) res_df = as.data.frame(res_matrix) %>% mutate(x = 0:3) %>% pivot_longer(matches("[0-3]")) ggplot(res_df) + geom_area(aes(x, value, fill = name))

Which generated this:

￼

Out of interest, would you say that this is a good approach to tackle the issue of predicting mode splits with confidence intervals? See here for some city data I've been looking at, would be great to get a solid predictive model of cycling so that you could predict the % increase with changes to multiple parts of transport systems:

https://github.com/ATFutures/who3/tree/master/scenarios

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/paul-buerkner/brms/issues/463?email_source=notifications">https://github.com/paul-buerkner/brms/issues/463?email_source=notifications</a>\u0026email_token=ACFSULI2HYOIGSYE4IHBVP3QTCAT3A5CNFSM4FG3LMOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDVIGAI#issuecomment-552239873", "url": "<a href="https://github.com/paul-buerkner/brms/issues/463?email_source=notifications">https://github.com/paul-buerkner/brms/issues/463?email_source=notifications</a>\u0026email_token=ACFSULI2HYOIGSYE4IHBVP3QTCAT3A5CNFSM4FG3LMOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDVIGAI#issuecomment-552239873", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by paul-buerkner** [comment]
Please ask brms related questions on https://discourse.mc-stan.org/ using the Interfaces - brms tag.
