### ISSUE TITLE
User-defined function/distributions ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [paul-buerkner/brms#47]
Wouldn't it be nice if some interface could allow the (Stan ?) definition of user functions / distributions to be passed to the ```functions{}``` paragraph of the Stan code implementing a model ?

Case in point : I followed the advice given in the (now closed) issue #46, which was essentially to give a name to the linear part of a nonlinear model in the ```formula``` argument of ```brm``` and to define it in the ```nonlinear``` argument ; an example : 
```
brm(Y ~ LinPred + log(k+(1-k)*exp(beta*X)), data=...,
    nonlinear = list(LinPred ~ A + B + (1|C), k ~ 1, beta ~ 1),
    prior=c(set_prior("cauchy(0,3)", nlpar="beta")
            set_prior("uniform(0,1)", nlpar="k", lb=0, ub=1),
            set_prior("uniform(-100,100)", nlpar="LinPred", lb=-100, ub=100)))
```

The last prior definition is a nonsense, since LinPred is a (deterministic) function of the independent variables and the corrsponding (fixed effect) parameters. What should have been writtent would be something along the lines of ```set_prior("flat()", nlpar="LinPred")```, which would be meaningful if we could pass the Stan snippet : 
```
functions {
    real flat_log(real x) {
        return 0.0;
    }
}
```

in the Stan model code.

Other uses : simplifying the writing of complex nonlinear functions, implementing alternate parametrization of various distributions, etc...

What do you think ?

**Comment by paul-buerkner** [comment]
I like the idea and it shouldn't be too difficult to implement either.

However, let me clarify something about the "LinPred" prior. LinPred is not deterministic in the sence that it depends on the fixed effects parameters for A and B as well as on some group specific terms of C. The group specifc terms have internal default priors, but the fixed effects haven't. So when I force you to put a prior on non-linear parameters, I actually force you to put priors on their corresponding fixed effects (in your case for the Intercept as well as A and B). You can see that this actually happens by investigating `stancode(<your model>)`. This is definitely something that needs to be clarified in the documentation as well as in the error message that occurs when not setting priors.

**Comment by EmmanuelCharpentier** [comment]
To be precise, LinPred is a deterministic functin of random elements. Therefore, ```brm``` shouldn't check the existence of a (nonsensical) prior for LinPred, but the existence of a prior for all (fixed and random) coefficients of the formula on its right-hand size.

Presently, the nonsensical prior for LinPred is enough to satisfy ```brm```'s checks. It turns out that my current example is able to run with these non-priors. Sheer luck ?

**Comment by paul-buerkner** [comment]
As I said, the error message regarding missing priors on non-linear parameters is misleading and I already tried to improve it in commit 40bdebb. As you correctly point out, it doesn't make sence to put a prior on LinPred itself and this is not what happens in brms. By writing
```R
set_prior("uniform(-100,100)", nlpar="LinPred", lb=-100, ub=100)
``` 
you actually put priors on the fixed effects of LinPred, because the `class` argument of `set_prior` defaults to `b` (i.e. fixed effects).

**Comment by paul-buerkner** [comment]
Using the `stan_funs` argument in `brm` and `make_stancode` it should now be possible to add Stan functions to the code. You can try it out with the dev version from github:

```R
devtools::install_github("paul-buerkner/brms")
```

I would be greaful, if you could give me feedback on whether it also works for you.

**Comment by EmmanuelCharpentier** [comment]
I'll look into that, tonight if I'm lucky, tomorrow night or Saturday if 
I'm not...

A quick one : how do you specify a prior for the standard-deviation of a 
group random effect for a nonlinear parameter ? All my attempts were 
rejected... The results I get with defaults are acceptable, but I feel 
that these defaults might be a bit tight for one particular random effect.

**Comment by paul-buerkner** [comment]
There was actually a bug that prohibited to define priors on standard deviations of specific random effects in non-linear models. Thanks for catching that! The problem should now be fixed in the latest dev version on github.

**Comment by EmmanuelCharpentier** [comment]
Both features work for me. Sample code : 
```
lS <- "  real logSigmoid(real t, real k0, real k1) {
      real tmp;
      tmp <- k1*(t-k0);
      return tmp-log(exp(tmp)+1);
  }
"
bar <- brm(log(Duree) ~ LinPred - logSigmoid(Exp,Exp0,k1),
                 data=Data,
                 nonlinear=list(LinPred ~ Classe + Arcade + ReTt +
                                    noWO + noTf + (1|Etudiant), 
                                k1 ~ 1+(1|Etudiant),
                                Exp0 ~ 1+(1|Etudiant)),
                 prior=c(set_prior("uniform(0,1)", nlpar="k1",
                                   lb=0, ub=1),
                         set_prior("cauchy(0,4)", nlpar="Exp0"),
                         set_prior("cauchy(0,10)", class="sd",
                                   group="Etudiant",
                                   nlpar="Exp0"),
                         set_prior("cauchy(0,5)", class="b",
                                   nlpar="LinPred")),
                 stan_funs=lS,
                 control=list(adapt_delta=0.99, max_treedepth=11))
```
Thanks a lot !

**Comment by EmmanuelCharpentier** [comment]
Ahem...

It turns out that using a user-defined function breaks WAIC and LOO : one gets an error telling that this function is not available. In what follows, ```bar``` is a brm fit using the ```logSigmoid``` user-defined function.
```
> WAIC(Duree.NoExp,Duree.Fac,Duree.Ord,Duree.Lin,Duree.NonLin,Duree.Sig,bar)
Error in eval(expr, envir, enclos) : 
  impossible de trouver la fonction "logSigmoid"
> LOO(Duree.NoExp,Duree.Fac,Duree.Ord,Duree.Lin,Duree.NonLin,Duree.Sig,bar)
Error in eval(expr, envir, enclos) : 
  impossible de trouver la fonction "logSigmoid"
```

One could define a function of the same name in R, or one could expose the user-defined function(s) in R, at least in the evaluation frame of LOO and/or WAIC. The latter would be preferable for consistency reasons, but needs more work, as far as I understand.

HTH,

**Comment by paul-buerkner** [comment]
I am aware of this problem and I agree that exposing user-defined stan functions is the preferable way. However, this still leads to problems in the evaluation of the non-linear model formula in R, because evaluation is performed in a vectorized manner and the stan-functions are not necessarily vectorized (in fact they would have to except matrices as input). 

Of course, I could fall back to pointwise evaluation in this case, but this will horribly slow in R, as we had to loop over a matrix of dimension Nsamples x Nobservation, which is rather huge for larger models. 

Accordingly, for now, it appears to me that defining an equivalent R functions is the better way to go. I would love to automate this, but as you can imagine, it's difficult (if not impossible) to parse an arbitrary Stan function to an equivalent R function. Thus, I improved the occuring error message encouraging the user to write the R function himself. Usually this should take not longer than a few seconds as one already has defined the function in Stan language.

I am working on restructuring the computation of the log-likelihood and when it's done, I will revisit our case again. Maybe then it could make sence to use the Stan functions directly.

**Comment by EmmanuelCharpentier** [comment]
On 26/02/2016 14:08, Paul-Christian Bürkner wrote:
> I am aware of this problem and I agree that exposing user-defined stan
> functions is the preferable way. However, this still leads to problems
> in the evaluation of the non-linear model formula in R, because
> evaluation is performed in a vectorized manner and the stan-functions
> are not necessarily vectorized (in fact they would have to except
> matrices as input).
>
> Of course, I could fall back to pointwise evaluation in this case, but
> this will horribly slow in R, as we had to loop over a matrix of
> dimension Nsamples x Nobservation, which is rather huge for larger models.
>
> Accordingly, for now, it appears to me that defining an equivalent R
> functions is the better way to go. I would love to automate this, but as
> you can imagine, it's difficult (if not impossible) to parse an
> arbitrary Stan function to an equivalent R function. Thus, I improved
> the occuring error message encouraging the user to write the R function
> himself. Usually this should take not longer than a few seconds as one
> already has defined the function in Stan language.

Thanks for the advice. Questions :
	- should the R function take "scalars" (i. e. length-1
	  vectors), vectors or matrix arguments ?
	- ditto for the Stan function : can they benefit of vector or
	  matrix arguments ?

A vignette for nonlinear models appears more and more necessary. Would 
you like me to give it a try ? I'd be delighted to help you if I can.

> I am working on restructuring the computation of the log-likelihood and
> when it's done, I will revisit our case again. Maybe then it could make
> sence to use the Stan functions directly.

I'd be delighted... to test this !

In the interim, would it make sense to use loo::loo and/or loo::waic 
from the loo package on the "fit" components ?

Sincerely yours,

					Emmanuel Charpentier

**Comment by paul-buerkner** [comment]
As long as your R functions fall back to vectorized R base function, such as `+`, `exp` or `sin` there is nothing to worry about, as they except any type of vector (internally matrices are also vectors in R).
Stan will benefit only little on vectorized functions as long as they do not appear within "sampling statements". Also, the current non-linear Stan code created by brms requires function to take reals, not vectors. For your particular case, the R function would just look like this:
```R
logSigmoid <- function(t, k0, k1) {
  tmp <- k1*(t-k0);
  tmp - log(exp(tmp)+1)
}
```

I totally agree that a vignette is needed and its already on my ToDo-list (see #37).

Internally, brms calls loo::loo and loo::waic anyway. I am not exactly sure what you mean by "fit components", but what I am planning to do is using loo::loo.function instead of loo::loo.matrix to reduce the RAM requirements of methods such as logLik and predict.

**Comment by paul-buerkner** [comment]
As long as your R functions fall back to vectorized R base function, such as `+`, `exp` or `sin` there is nothing to worry about, as they except any type of vector (internally matrices are also vectors in R).
Stan will benefit only little on vectorized functions as long as they do not appear within "sampling statements". Also, the current non-linear Stan code created by brms requires function to take reals, not vectors. For your particular case, the R function would just look like this:
```R
logSigmoid <- function(t, k0, k1) {
  tmp <- k1*(t-k0);
  tmp - log(exp(tmp)+1)
}
```

I totally agree that a vignette is needed and its already on my ToDo-list (see #37).

Internally, brms calls loo::loo and loo::waic anyway. I am not exactly sure what you mean by "fit components", but what I am planning to do is using loo::loo.function instead of loo::loo.matrix to reduce the RAM requirements of methods such as logLik and predict.

**Comment by paul-buerkner** [comment]
I added a reminder to #40 so that I don't forget to take a look at user-defined Stan functions again once pointwise log-likelihood computation is implemented. I guess this issue can be closed now. Many thanks for your ideas and your help!
