### ISSUE TITLE
Autocorrelation processes for non-linear and/or non-Gaussian models

### ISSUE THREAD

**Issue by devillemereuil** [paul-buerkner/brms#519]
Hi,

I have the following model at the moment, in which a Gaussian optimum is fitted with a zero-inflated Poisson distribution and varying optimum and maximal value for each year:

````R
prior <- 
    prior(gamma(0.01, 0.01), class = "b", nlpar = "Wmax", lb = 0) +
    prior(gamma(0.01, 0.01), class = "b",  nlpar = "omega", lb = 0) +
    prior(normal(0, 10), class = "b", nlpar = "theta") +
    prior(cauchy(0,5), class = "sd", group = "Year", nlpar = "theta") +
    prior(cauchy(0,5), class = "sd", group = "Year", nlpar = "Wmax")

formula <- 
    bf(Fitness ~ Wmax * exp(-(((Pheno.scale - theta) / omega)^2)),
       omega ~ 1,
       theta + Wmax ~ (1|Year),
       nl = TRUE)

mod_paper <- 
    brm(formula = formula,
        data    = data,
        prior   = prior,
        family  = zero_inflated_poisson(link = "identity"),
        warmup  = 500,
        iter    = 1500,
        thin    = 1)
````

(I know this model can be somehow reduced to a GLMM, but not if I want to separate the random effects for `Wmax` and `theta`... anyway)

I want to change the random effect for an autocorrelated process (AR1 for example) between years for `theta` and `Wmax`.

Right now, this does not seem to be possible with brms for two reasons:

1. AR processes do not seem to be implemented for non-Gaussian distributions (at least, not for Poisson and ZI Poisson).
2. There does not seem to be a way to associate the AR1 process to a specific non-linear parameter (ie. `theta` or `Wmax`)

So I guess I'll have to resort to another way to do this (pure rstan?), but I thought it would be useful to open a feature request for those cases and see whether they were on the pipeline for future versions.

**Comment by paul-buerkner** [comment]
These two AR processes are very different.

1) would refer to an AR1 process of **residuals**, which we don't canonically have in a (ZI-)Poisson model, but have to manually add using a "random effect" over observations. This is something I can implement in the future for some families (definitely for Poisson and perhaps for ZI-Poisson).

2) An AR1 process of `theta` (or `Wmax`) is already possible although a little bit heavy in the implementation. You have to specify a user-defined Stan function that takes all values of the non-linear parameters at once (not only the `n`th observation), and inside this function loop over observations and relate `theta[n]` to `theta[n-1]`.  If `nlfun` was this function (supplied to `brm` via argument  `stanvars`), you could specify the model formula as follows

```
formula <- 
    bf(Fitness ~ nlfun(Wmax, Pheno.scale, theta, omega),
       omega ~ 1,
       theta + Wmax ~ (1|Year),
       nl = TRUE,
       loop = FALSE)
```

The `loop = FALSE` is important so that brms does not loop over observations itself.

**Comment by devillemereuil** [comment]
Thank you for this. It seems 1. is not really what I had in mind then. I imagine 2. would work also for a ZI-Poisson?

How would I include an random "node" in the nlfun function? More precisely, AR1 would look like (in BUGS syntax):
````
theta[n] ~ dnorm(beta * theta[n-1], tau)
````
Would the following be correct in `nlfun`?
````R
theta[n] <- beta * theta[n-1] + rnorm(0, sigma)
````

(My issue here is with `rnorm`, adding `beta` and `sigma` as parameters seem trivial, but I'm not sure how to handle the stochasticity within nlfun...)

**Comment by devillemereuil** [comment]
Will do thanks!
