### ISSUE TITLE
usability of censored model formula outside of `brm`

### ISSUE THREAD

**Issue by topepo** [paul-buerkner/brms#537]
I want to use `brms` models in other packages using wrappers. In the course of doing this, I need to evaluate the model formula on the data set used for fitting. With more traditional survival formats, this works fine:

``` r
library(survival)
library(brms)
f <- Surv(time, censored) ~ age
model.matrix(f, head(kidney))
#>   (Intercept) age
#> 1           1  28
#> 2           1  48
#> 3           1  32
#> 4           1  31
#> 5           1  10
#> 6           1  16
#> attr(,"assign")
#> [1] 0 1
```

There is no `cens` function, so is there a way to do the same thing with a formula such as `time | cens(censored) ~ age`?

**Comment by paul-buerkner** [comment]
You can use the `parse_bf` function to split the formula into its parts. The corresponding function to `cens` is called `resp_cens` where `resp_` will automatically be added to the formula by `parse_bf`.

**Comment by paul-buerkner** [comment]
In the new github version of brms, you can now access `data_response` and `data_predictor` which will return lists of data related to response and predictor variables, respectively. Please note that these output lists may be quite long because of the flexibility of the models that can be specified with brms.

**Comment by topepo** [comment]
Thanks
