### ISSUE TITLE
Minor issue for brms models with smooths

### ISSUE THREAD

**Issue by lukeholman** [paul-buerkner/brms#562]
```
library(brms)
library(dplyr)
fake_data <- data.frame(successes = sample(100, 100, replace = T),
                        trials =  rep(100, 100),
                        date = rep(1:50, 2),
                        treatment = rep(c("A", "B"), each = 50))  

# This works fine, because "treatment" is a factor at this point
b <- brm(successes | trials(trials) ~ s(date, by = treatment), 
         family = "binomial",
         data = fake_data)


# Let's convert "treatment" to a character. brms should not care...
fake_data <- fake_data %>%
           mutate(treatment = as.character(treatment)))

# identical model gives a puzzling error
b <- brm(successes | trials(trials) ~ s(date, by = treatment), 
         family = "binomial",
         data = fake_data)
> Error in mgcv::smoothCon(eval2(smterms[i]), data = data, knots = knots,  : 
                             Can't find by variable
```

Maybe brms could internally coerce characters to factors in this context? The issue is that `s()` is from `mgcv`, and that package mandates that one uses factors over characters, which is a surprise to those of us accustomed to brms (which mostly doesn't care, or at least has nice clear error messages).

Alternatively if this is risky, maybe you could instead return a warning something like "Error: arguments to "by" inside s() must be formatted as factors, not as characters".

**Comment by paul-buerkner** [comment]
Good idea! I stumbled upon this issue multiple times myself and wondered every time what went wrong...

It seems as if there were other places where **mgcv** just throws weird error messages for factor like variables (characters and logical vectors) without this being necessary. 

I just made a minor change to brms so that factor-like variables will now behave like factors in smooth terms.

Still, I suggest you ask Simon wood about also changing this internally in mgcv, as well.
