### ISSUE TITLE
Function run() not found when using future=TRUE in brm

### ISSUE THREAD

**Issue by jknowles** [paul-buerkner/brms#579]
When using multisession or cluster future in the future package, the `brm` function returns the following error on my setup:

```
Error in run(rstan::sampling, args) : could not find function "run"
```

On my machine this can be reproduced with the following:

```
library(parallel)
library(future)
library(snow)
library(brms)
plan(multisession(workers = 4))
bprior1 <- prior(student_t(5,0,10), class = b) +
prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ log_Age_c + log_Base4_c * Trt + (1|patient),
            data = epilepsy, family = poisson(), 
            prior = bprior1, future = TRUE)
```

Oddly, it works fine if you reduce the library calls:

```
library(future)
library(brms)
plan(multisession(workers = 4))
bprior1 <- prior(student_t(5,0,10), class = b) +
prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ log_Age_c + log_Base4_c * Trt + (1|patient),
            data = epilepsy, family = poisson(), 
            prior = bprior1, future = TRUE)
```

This suggests there is a namespace conflict occurring somewhere with the `run()` function perhaps?

**Comment by paul-buerkner** [comment]
It's not a namespace conflict since `run` can't be found in the first case. Rather it has to do something with the environment in which stuff is called. If the environment is outside of the brms namespace, `run` won't be found because it is currently only an internal function of brms. I am not sure, why the call is evaluated outside of the brms namespace, though.

Anyway, exporting `run` should fix the problem.

**Comment by paul-buerkner** [comment]
The problem should be fixed now in the dev version of brms on GitHub. Thanks for reporting this issue!

**Comment by jknowles** [comment]
Confirmed this fixed the problem. Thanks!
