### ISSUE TITLE
Problems with large matrix for conditional autoregressive structures

### ISSUE THREAD

**Issue by JacopoCerri** [paul-buerkner/brms#588]
Dear all,

I am fitting a quantile regression based on an asymmetric Laplace distribution. As I would like to account for a first-order spatial dependence, I am trying to include a conditional autogressive structure. Notably, I am following the suggestions provided [here](https://rdrr.io/cran/brms/man/cor_car.html). 
The problem is that my neighborhood matrix seems to be too large and R cannot allocate large vectors (I am on Ubuntu, so I am already exploiting all the memory available). My dataset is not small (n=304), but neither huge.
Below you can find the code. Find the dataset attached.

```
Grid <- expand.grid(df$lon, df$lat)

K <- nrow(Grid)

distance <- as.matrix(dist(Grid))

W <- array(0, c(K, K))

W[distance == 1] <- 1

qr25 <- brm(bf(varfarms ~ wolf.colonization + varpop0111 + wolf.colonization*varpop0111, 
               quantile = 0.25), data = df, family = asym_laplace(), autocor = cor_car(W))

summary(qr25)

marginal_effects(qr25)
```

Any idea on how to deal with this problem? The 'bigmemory' package seems to be an option, but before using my memory on the hard disk, I was thinking about making the matrix lighter. My programing skills are fairly limited and there might be a solution that I ignore.

Kind regards,

Jacopo Cerri

[DataBRMSForum.csv.zip](https://github.com/paul-buerkner/brms/files/2753048/DataBRMSForum.csv.zip)

**Comment by paul-buerkner** [comment]
It seems unlikely to me that a 304x304 matrix creates any memory issues. Let me see if I can find the bottleneck that leads to this problem.

**Comment by paul-buerkner** [comment]
It seems the problem happens much earlier and is unrelated to brms. In 

```R
Grid <- expand.grid(df$lon, df$lat)
```

you create a data.frame of $304^2 = 92416$ rows. When you then call `distance` on it, the result becomes a 92416 x 92416 matrix, which is arguably too large for R to handle. I suggest you use sparse matrix algebra as provided in the **Matrix** package to create and appropriate distance matrix and try it with that. Since the brms issue tracker is not a general R help forum, I am closing this issue for being unrelated to brms.
