### ISSUE TITLE
loo y hash mismatch

### ISSUE THREAD

**Issue by avehtari** [paul-buerkner/brms#642]
Both models below fit_2 and fit_3 have the same y, but loo_compare warns about different y
```
library("rstanarm")
options(mc.cores = parallel::detectCores())
library("brms")
library("loo")

#' **Load data**
data(roaches)
(n <- nrow(roaches))
#' scale the number of roaches by 100
roaches$roach100 <- roaches$roach1 / 100

fit_2 <- stan_glm(y ~ roach100 + treatment + senior, family=neg_binomial_2,
  offset=log(exposure2), data=roaches, seed=SEED, refresh=0)
loo_2 <- loo(fit_2)

roaches$logp1_roach1 <- log(roaches$roach1+1)
roaches$log_exposure2 <- log(roaches$exposure2)
#+ results='hide'
fit_3 <- brm(bf(y ~ logp1_roach1 + treatment + senior,
                 zi ~ logp1_roach1 + treatment + senior),
             family=zero_inflated_negbinomial(), data=roaches,
             prior=set_prior("normal(0,1)"), seed=SEED, refresh=500)
loo_3 <- loo(fit_3)
loo_compare(loo_2, loo_3)
```

rstanarm uses y with attributes cleared
```
yy<-get_y(fit_3)
attributes(yy)<-NULL
attr(loo_2, "yhash")==digest::sha1(yy)
```

**Comment by jgabry** [comment]
To follow up on this, Aki is currently using the branch corresponding to this loo PR 

https://github.com/stan-dev/loo/pull/103

where the loo package itself now for `yhash` attributes before comparing models (so rstanarm and brms just need to add the hashes to the loo objects but not check them). 

It looks like brms does a bunch of stuff before hashing in 

https://github.com/paul-buerkner/brms/blob/e9910507e3c3e4786c5e6b48d08b1b01dbdc0860/R/loo-helpers.R#L301 

whereas in 

https://github.com/stan-dev/rstanarm/blob/918103f961732e393f123b8960d5daeeadb99590/R/loo.R#L732

rstanarm just removes attributes from `y` and then hashes it. The attributes are removed so that it is just the values that need to be the same for loo to allow the comparison. 

I think this difference is what results in the different hashes from brms and rstanarm despite the values of `y` being the same in both cases.

**Comment by paul-buerkner** [comment]
The bunch of other stuff is necessary due to the potential complexity of brms model and their responses. We may stop including attributes though in the hashing. I will take a closer look.

**Comment by paul-buerkner** [comment]
should be fixed now.

**Comment by jgabry** [comment]
Thanks Paul!
