### ISSUE TITLE
Fitted correlated timeseries plotting is off by one

### ISSUE THREAD

**Issue by jebyrnes** [paul-buerkner/brms#653]
This seems like an odd behavior - consider the sunspot data.

```
library(brms)
library(ggplot2)

sun_dat <- data.frame(sunspots = as.vector(sunspot.year),
                      years = 1700:1988,
                      g = factor(1))
```

Let's say we fit this with an AR1 structure to look at if there is non-stationarity.

```
mod_brm <- brm(sunspots ~ years,
               autocor=cor_ar(formula = ~years, p = 1),
               data = sun_dat)
```

If we plot the fitted results, they do not line up with the timeseries.  Compare these two plots.

```
ggplot(sun_dat,
       aes(x = years, y = sunspots)) +
  geom_line() +
  geom_line(y = fitted(mod_brm)[,1], alpha = 0.5, lwd = 2, color = "red")
```

![image](https://user-images.githubusercontent.com/757410/56525608-13e9b700-6500-11e9-823d-856a8638ae25.png)

Note how the peaks and dips are just a little off? Now, let's take out the first observation, and add an NA at the end.

```

ggplot(sun_dat,
       aes(x = years, y = sunspots)) +
  geom_line() +
  geom_line(y = c(fitted(mod_brm)[-1,1], NA), alpha = 0.5, lwd = 2, color = "red")
```

![image](https://user-images.githubusercontent.com/757410/56525695-31b71c00-6500-11e9-8e2d-79f2af26571f.png)

Problem solved. What is driving this behavior? It seems like something folk might not notice, and so at least a warning should be issued when using `fitted` or `predict`.

**Comment by paul-buerkner** [comment]
This may look like a bug but I don't think it is one. For comparison lets also fit the model with `stats::arima`

```R
mod_arima <- arima(sunspot.year, c(1, 0, 0), xreg = 1700:1988)
print(mod_arima)
```

which I would consider the frequentist "gold-standard" implementation for this model. We we compare residuals of both implementations

```R
resid_brm <- residuals(mod_brm)
resid_arima <- residuals(mod_arima)
plot(resid_brm[, 1], resid_arima)
```

we see that they are in almost perfect alignment. Further, when we compare `LOOIC` and `AIC` of the two models (which is ok for the purpose of a quick approximation, since we used almost flat priors for the bayesian model and have an approximately normal posterior) we see that they align very closely as well. 

I can't tell you exactly why shifting by one makes the in-sample fit *appear* so much better, but I don't think there is a bug in the brms implementation.

**Comment by jebyrnes** [comment]
Definite example of Problem Existing Between Keyboard And Chair

https://stats.stackexchange.com/questions/404650/why-is-arima-in-r-one-time-step-off is a great explainer
