### ISSUE TITLE
Marginalising "out" a factor

### ISSUE THREAD

**Issue by tomwallis** [paul-buerkner/brms#66]
This is probably a more general question for R factor syntax, but if you have suggestions it would be appreciated.

Let's say I have data with three factors: A and B both have two levels whereas C has four. I've fit a model using sum coding for the factors. Now I would like to plot the marginal estimates from the model for A and B (i.e. a two by two plot), *ignoring* or *marginalising out* factor C (rather than conditioning on only one level).

The `conditions` argument of `marginal_effects` allows me to specify the level I want to use for factor C... but shouldn't it be possible (because of sum coding) to just zero out the three coefficients associated with C, thus arriving at the grand mean (all other things being equal)?

**Comment by paul-buerkner** [comment]
I agree that it would be great to have an option for this. It would mean to bypass the coding of the factor somehow to set all dummy variables to zero arriving at the grand mean in case of sum coding. 

However, from a technical perspective, this would be rather complicated to implement. We can't just pass this via `conditions`, because factor levels have to be validated somehow as new factor levels are meaningless in fixed effects. Also, we couldn't use the canoical `stats::model.matrix` anymore to generate the dummy variables for the factors. In fact, this would require much special case coding making the code error prone and difficult to maintain. Accordingly, I hesitate to implement this feature.

What you can do, however, is generating the dummy variables yourself and putting them into the model as numeric variables. Then, you can plot marginal effects for any numeric values you want, e.g. zero. Here is an example:

```R
dat <- data.frame(y = rnorm(90), x = factor(rep(c("a", "b"), each = 45)),
                  z = factor(rep(1:3, 30)))
contrasts(dat$z) <- contr.sum(3)
dat <- cbind(dat, model.matrix(~z, data = dat)[, -1, drop = FALSE])
fit <- brm(y ~ x * (z1 + z2), data = dat)
marginal_effects(fit, effects = "x", conditions = data.frame(z1 = 0, z2 = 0))
```

**Comment by tomwallis** [comment]
Thanks for the suggestions and example code. While that would definitely be good for small models, I have a rather large one so I would hesitate to code it like that (setting individual predictor columns to zero).

Would it be instead possible to allow the user to pass a *custom* design matrix to the prediction functions (e.g. `marginal_effects`). That is, instead of passing `condition`, pass the entire fixed-effects design matrix. This would flag errors if the matrix was the wrong dimension for the fitted model, but otherwise just internally multiply in that custom matrix instead of the internal one. That would obviously allow the user to make some pretty meaningless predictions, but would also allow for more flexibility (as in the case above).

Anyway. Thanks for thinking about it. I understand that you don't want to add hard-to-maintain code.

Incidentally, I will be away for a week so I won't reply to this message in a timely fashion.

**Comment by paul-buerkner** [comment]
I will think about a way to make this possible. :-)

**Comment by tomwallis** [comment]
That would be super. Maybe a standalone prediction function that takes `(y, X)` as arguments (where X is a custom fixed-effects design matrix; I can't imagine why one would need more flexibility for the random effects than is already offered)?

Then one could write some code to generate the design matrix (calling `model.matrix()`, and manually zero out all columns associated with the contrasts you want to marginalise over).

**Comment by paul-buerkner** [comment]
After giving it another thought, I have some conceptual objections with this sort of marginalization, although I clearing understand your reasoning. When we model a factor as a 'fixed effect' we assume that only excatly those factor levels appearing in the data are the relevant (and existing) ones. When we then go ahead and make predictions of the grand mean (by setting all dummy variables to zero in case of sum coding) we predict something that -- according to the model -- doesn't really exists. 

If, however, we model the factor as a 'random' effect, we assume that the levels appearing in the data are drawn from a normal population. Therefore making predictions for the population-level mean is consistent with our modeling assumption and this is excatly what `marginal_effects` does when marginalizing over random effects. 

I am still not sure whether (and how) I should implement this, but I don't think that passing a fixed effects design matrix is really the best choice -- at least from a coding perspective -- despite being probably the most flexible solution.

**Comment by tomwallis** [comment]
To me, the case of marginalising out a factor as detailed above is the same logic as examining "main effects" in ANOVA. I can see your reasoning but I think this is probably case-specific: in many use cases it *could* make sense to marginalise out a factor in this way, rather than treating the factor as a random effect. In a two-by-two experimental design (two factors each with two levels), for example, we might be interested in testing not only whether there are simple effects (differences in the factor levels conditioning on each level of the other factor) but also main effects (differences in factor levels ignoring the other factor). 

As a simple example from experimental psychology, consider the classic "Stroop" task, where I ask you to report the *colour* of the text a word is written in and I measure your response time to do so. The word can either be *congruent* (e.g. `GREEN` written in green letters) or *incongruent* (e.g. `GREEN` written in blue letters). The typical result is that you're faster in the congruent than the incongruent condition. Now imagine I include a second factor: whether you are performing only that single task, or whether I ask you to concurrently perform a second task (e.g. remember a telephone number). Imagine I expect an interaction, such that when you are acting in the dual-task condition I expect the difference between congruent and incongruent conditions to be even larger than in the single task condition. In this case, it would still be nice to be able to test or plot the main effect of congruent / incongruent, ignoring the task – which one could achieve by marginalising out the single / dual-task factor as described above. Note that it's not really useful to think of either of these conditions as random effects being sampled from a population of all possible conditions.

**Comment by paul-buerkner** [comment]
Would it suffice for your analyses, if I implemented an option to set the dummy variables of a factor to zero (thus allowing to estimate the grand mean in case of sum coding)? This was our first discussed solution I believe.

The alternative to pass the whole design matrix could cause many unexpected problems and goes too deep into the system so that's not really something I am comfortable with.

**Comment by tomwallis** [comment]
That would be perfect, and I would prefer that to passing a whole design matrix, but I had thought that the latter might have been easier to code.

Note that the zeroing method would also need to zero out any interaction terms associated with that factor.

**Comment by paul-buerkner** [comment]
The discussed feature is now implemented (at least as a 'beta' version). Just put `NA` into the factor variables, which you want to marginalize out in the described way, for instance:

```R
marginal_effects(fit, effects = "y", conditions = data.frame(x = c("a", NA))
# this will also work in predict etc.
predict(fit, newdata = data.frame(x = c("a", NA))
```

 Actually it turned out to be quite simple after I found a way to tell `stats::model.matrix` what to do. Builing a work-around myself without using `model.matrix` would have been a huge pain especially when also having to amend interaction terms. The current implementation works in a very canonical way by internally adding a new factor level which is `0` for all dummy variables and making sure the rest of the contrasts matrix stays the same. It should work with arbitrary interaction terms.

I would be greatful for your feedback on whether it also works for your models.

**Comment by tomwallis** [comment]
Thanks for implementing this. It appears to work for my models (at least, no error is thrown and the predictions change).

So if I understand your code correctly, the above is zeroing out all levels of `x` that are not `"a"`? And, if I wanted to zero all levels of `x` (i.e. completely marginalise over the factor in sum coding) I could write:

```r
conditions = data.frame(x = NA)
```

?

**Comment by paul-buerkner** [comment]
Yep. Basically all rows where x is `NA` will lead all dummy variables of x to be zero for these conditions.

**Comment by tomwallis** [comment]
Ok, great, thanks. This will be very useful for me.
