### ISSUE TITLE
Structural Time Series using brms?

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#69]
I was reading this, and I wondered if it is possible to do a similar thing using brms:

http://multithreaded.stitchfix.com/blog/2016/04/21/forget-arima/

I know we can do ARMA models with brms, but this formulation is rather different.

**Comment by paul-buerkner** [comment]
This sounds interesting. As far as I understand the post, this is not yet possible with brms. 
However, after taking a quick look, it definitely seems to be worth implementing. I will take a closer look at this type of model and see what needs to be done in order to get it running.

**Comment by paul-buerkner** [comment]
An implementation of the structural time series model with local level terms (as described in the blogpost) is now availabe in the dev version of brms. You can access it by using the `cor_bsts` function for the `autocor` argument. In the tests I have run so far, Stan does a fairly good job in estimating this type of model. In theory, the class of structural time series models is way larger (and in fact also comprises ARMA correlations), but I am not sure how much generality will be useful for users of brms (and also doable for me).  

What is currently missing is a function automating the forecasting, not because it's particularily difficult to implement but because it doesn't fit nicely in the existing prediction functions of brms. I have yet to come up with a solution that doesn't require too much special case coding.

**Comment by alireza202** [comment]
That's a great addition Paul! Next time I want to do time series, I'll definitely check it out!

**Comment by alireza202** [comment]
I'm having difficulties getting this model converged with `cor_bsts`:
```
fixed_prior = c(set_prior('normal(0, 5)', class = 'b'),
                set_prior('student_t(3, 0, 10)', class = 'sigmaLL'))

brm(formula = y ~ p + (p | item), 
    data = training,
    family = negbinomial(),
    chains = 4,
    cluster = 4,
    prior = fixed_prior, 
    autocor = cor_bsts(~ t | item),
    iter = 2000, 
    warmup = 500) -> model
```
I get:
```
Correlation Structure: bsts(~t | item)
        Estimate Est.Error l-95% CI u-95% CI Eff.Sample Rhat
sigmaLL     0.15      0.03     0.09     0.22         26 1.14
```
I tried tightening the prior by `set_prior('student_t(3, 0, 1)', class = 'sigmaLL')`, but it still didn't converge.

Here's the mixing plot:

<img width="479" alt="screen shot 2016-06-14 at 12 17 07 pm" src="https://cloud.githubusercontent.com/assets/6646274/16056382/2227304c-322a-11e6-82d6-40f4fe7348db.png">

**Comment by paul-buerkner** [comment]
Hmm, that's not great. Maybe, 500 warmup samples are not enough and using warmup = 1000 will help (I am sceptical though). You may just need to sample longer... You could also try using a normal(0,1) prior instead of a studen_t prior on `sigmaLL`.  How many observations do you have per item?

**Comment by alireza202** [comment]
I have minimum 10, and maximum 26 samples per item. But median is 22. I'm running the model with the new prior and `warmup = 1000` now. It usually takes a lot longer to run with `cor_bsts`.

**Comment by alireza202** [comment]
Still didn't converge.

**Comment by paul-buerkner** [comment]
Is the time variable `weeknum`? In this case, I could try fitting it myself and see what happens.

**Comment by alireza202** [comment]
No, I'll send you the dataset by email shortly.

**Comment by paul-buerkner** [comment]
This has been implemented in brms for some time now. I am currently not planning to extend this feature, so I am closing this issue now.
