### ISSUE TITLE
Function to make drake-compatible plan for running brms models in parallel

### ISSUE THREAD

**Issue by jzelner** [paul-buerkner/brms#691]
This is an extension of #690. I have a working piece of code that will compile a brms model, make `num_chains` drake targets for it, run each in parallel, and then bring them back together using `combine_models`. Where I am stuck is on the best way to go about wrapping this in a function that could take a model name, an arbitrary call to `brm` and auto-generate this `drake_plan` dataframe:

```{r}
chain_ids <- 1:4
gaussian_plan <- drake_plan(
  gaussian_m_sampler =   brm(
    model_f,
    data = df,
    family = gaussian(),
    chains = 0
  ),

  gaussian_m_runs = target(
  update(gaussian_m_sampler,
    model_f
  ),
  transform = map(x = !!chain_ids)
),
  gaussian_m = target(
    brms::combine_models(gaussian_m_runs),
    transform = combine(gaussian_m_runs)
  )
)
```

**Comment by paul-buerkner** [comment]
I don't know drake and this issues seems to have become more or less independent of brms now, since brms is merely used in the model fitting. To support an arbitrary brms  you can pass it as an expression and evaluate it in the `parent.frame` of the function (i.e., in the parent environment from which the function was called). You may get better and more detailed answers one stack overflow, since the problem is applicable to any model fitting package that can combine models after the fact.
