### ISSUE TITLE
Plot the structure of the model like in Greta

### ISSUE THREAD

**Issue by bakaburg1** [paul-buerkner/brms#700]
As you may know, R library Greta for probabilistic inference via tensorflow, has a feature for automatically plotting the structure of a model (https://cran.r-project.org/web/packages/greta/vignettes/get_started.html towards the end). This is quite useful to show models in publications and presentations, especially for hierarchical models.

Greta implements it using DiagrammeR.

It would be nice to see it implemented in brms (or stan in general).

Thank you,
Angelo

**Comment by paul-buerkner** [comment]
For Stan itself such a graph is not generally possible (to my knowledge) as Stan does not follow a graph structure and may have more general expressions. You may ask at https://discourse.mc-stan.org/ about this.
 
For (some) brms models, it might be possible to make such a graph but since these models are not naturally represented in a graph structure, the work required to make such a plot will likely not be justified by the outcome. I conside a better representation of a brms or Stan model that stan model itself, which, in case of brms models, you can generated via `make_stancode`.

**Comment by paul-buerkner** [comment]
After giving this a bit more thought, I don't think I will ever do this in brms myself as it is not worth the enormous effort. However, if Stan supported such a feature in the future, I could surely support it in brms as well, by just building on what Stan did in this case.

**Comment by bakaburg1** [comment]
Ok, seems fair. If I build something my self I'll be happy to share it with you!

**Comment by paul-buerkner** [comment]
Thank you!
