### ISSUE TITLE
Use extract_draws to get predictions of specified smooth terms

### ISSUE THREAD

**Issue by dshelldhillon** [paul-buerkner/brms#738]
Hi Paul,
This is in reference to this issue. https://discourse.mc-stan.org/t/calculate-the-first-derivative-and-its-posterior-distribution-of-an-estimated-spline-trend/10577

I thought I had resolved it, however, it was pointed out by the orignal author of the paper whose study I was trying to replicate in a bayesian inference, that I need to work at the level of smooths.   

I'm trying to calculate the first derivative of the estimated trend, by making predictions at the x predictor separated by a small epsilon.  

Is there currently a way of getting the linear sum of ONLY the spline term predictions? (I don't want the fixed effect and intercept in my predictions).  But I do want the sampling variance within the spline term predictions.   

Thank you!

**Comment by paul-buerkner** [comment]
Usually, questions should not be asked as github issues but on https://discourse.mc-stan.org (with the Interfaces - brms) tag, but this time I make an exception as this question may l ead to a feature request.

What you need to use is the `smooths_only` argument from `extract_draws` and the proceed something along the lines of how its done in marginal_smooths.R line 160 ff. This is a little bit of manual work and it could make sense to add a method called `posterior_smooths` which basically works like `marginal_smooths` but does not summarise and plot the results and instead simply returns
the posterior matrix of specific smooths. But let's see how far you can already get using the manual route.

**Comment by paul-buerkner** [comment]
Edit: What you can also try is to call `ms <- marginal_smooths(..., spaghetti = TRUE)` and then extract the `spaghetti` arguments of the elements of `ms`. This may actually come relatively close to what you want.

**Comment by paul-buerkner** [comment]
I may misunderstand your code but it seems you are computing things in the wrong order. In Bayesian statistiscs always go (1) for your transformation of the posterior on the level of the posterior samples and (2) summarise your posterior (mean, quantile etc.) only **after** all transformations have been done. It seems in your case you compute quantiles first and then transform, which may often be incorrect.

**Comment by dshelldhillon** [comment]
Hi Paul- thanks for nudging me in the right direction.  You're correct.  I got it to work with the ugly piece of code below - 

Everthing else remains the same upto exteracting the model matrix of the splines. A lot of it is hard coded though - that's the next step!
```
## get the spline coefficients  (hard coding columns for now - need to come up with a better way)
## we have a total of 24 spline coefficients, 8 for each group  
## we get the whole posterior distirbution  
samples <- posterior_samples(mod) %>%
  select(9:32)


## get the lpmatrix for the first grid  
x1 <- post_first$dpars$mu$sm$re$sx2fac1$Zs %>% pluck(1) ## for factor 1 
x2 <- post_first$dpars$mu$sm$re$sx2fac2$Zs %>% pluck(1) ## for factor 2
x3 <- post_first$dpars$mu$sm$re$sx2fac3$Zs %>% pluck(1) ## for factor 3
X0 <- cbind(x1,x2) %>% cbind(x3)
colnames(X0) <- names(samples)

## get the lpmatrix  for the second grid  
x1 <- post_second$dpars$mu$sm$re$sx2fac1$Zs %>% pluck(1)
x2 <- post_second$dpars$mu$sm$re$sx2fac2$Zs %>% pluck(1)
x3 <- post_second$dpars$mu$sm$re$sx2fac3$Zs %>% pluck(1)
X1 <- cbind(x1,x2) %>% cbind(x3)
colnames(X1) <- names(samples)

## take the difference - the predictions 
Xp <- (X1 - X0)/epsilon

##### We first need to get a distribution of the predicted posterior, then calculate the intervals - like so  

samples <- as.matrix(samples)
der <- matrix(data = NA, nrow = 18000, ncol = 4000)
for (i in 1:nrow(samples)) {
der[,i] <- Xp %*% samples[i,]
}

der <- t(der)
der_mean <- apply(der,MARGIN = 2,FUN = mean)
der_lower <- apply(der,MARGIN = 2,FUN = quantile, prob = 0.025)
der_upper <- apply(der,MARGIN = 2,FUN = quantile, prob = 0.975)

data.frame(der_mean) %>%
  cbind(der_lower) %>%
  cbind(der_upper) %>%
  cbind(first) %>%
  ggplot(.,aes(x2,der_mean)) + geom_line(aes(color = fac)) + geom_ribbon(aes(ymin = der_lower, ymax = der_upper), alpha = 0.1)
```
Thanks a ton!

**Comment by jflournoy** [comment]
I am working on implementing this myself, and the brms codebase has changed somewhat since the above solution was posted. It seems to me that, now, the best bit of code to pull from for getting posterior samples for the smooth terms is [`conditional_smooths`](https://github.com/paul-buerkner/brms/blob/d87622bc778be86dc63a8d523752c2360d3fda08/R/conditional_smooths.R), especially if one has other terms in the model that ought to be accounted for somehow. 

I've tried one solution that seems to work for a simple smooth in a linear model (e.g., `bf(y ~ s(x) + z1 + z2)`) by adding an argument that allows the user to provide the values along which to generate the posterior predictions (that is, allowing the user to set [`values[[cv]]`](https://github.com/paul-buerkner/brms/blob/d87622bc778be86dc63a8d523752c2360d3fda08/R/conditional_smooths.R#L150) rather than having `resolution` determine them, which will allow someone to get samples along a certain range of values `vec` as well as `vec + epsilon`. This small modification, and setting `spaghetti = TRUE`, seems like it provides the necessary posterior samples for computing the derivative.

This is what the modification would look like: https://github.com/jflournoy/brms/commit/2ae5549d7f7bf986bf99ebffdffdfe698b705841#diff-e4ee6336090c4ab0c7cde46bfc0c96b0

Is it inappropriate to add this to the `conditional_smooths.R` function? Would it be better somewhere else? Am I wrong that `conditional_smooths` returns the kind of samples we would want to accomplish the goal of the original poster?

**Comment by paul-buerkner** [comment]
Thank you for looking into this! The idea is that, eventually, we have a method that does the post-processing for specific smooths (as does `conditional_smooths` at the moment) and once we have that `conditional_smooths` just becomes a wrapper around the new method..

**Comment by paul-buerkner** [comment]
I have added this issue to the next brms milestone so I will come back to it before the next release and will hopefully make this possible.

**Comment by paul-buerkner** [comment]
This feature is now implemented on github via method `posterior_smooths`.
