### ISSUE TITLE
Is reparametrization necessary/possible in brms?

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#74]
I'm not very familiar with reparametrization idea, but I've been reading that it helps speed up the execution. Is it possible to do reparametrization in brms, or is it already done, or do I need to go and directly change the stan code? I'm doing hierarchical negative binomial regression of this form:
```
brm(formula = y ~ p + t + (p + t | item), 
    data = df,
    family = "negbinomial",
    chains = 4,
    cluster = 4,
    prior = fixed_prior, 
    iter = 1200, 
    warmup = 500) -> fit_model
```

**Comment by paul-buerkner** [comment]
There are various forms of reparametrization some of them speed up the computation for some models. I try my best to keep the Stan code of brms as efficient as possible, which also includes reparameterizations. For instance, it is more efficient to use a centered fixed effects design matrix and to correct the intercept afterwards. This is done automatically in brms. Also, random effects models are written in a way that turned out to be the most efficient in various tests I made (at the cost of arkward looking Stan code if many random effects are modeled).

Accordingly, you don't have to worry about reparametrization yourself. If I become aware of another option to improve sampling efficiency, I will try to implement it directly without the user noticing the internal changes.
