### ISSUE TITLE
plot.brmsfit examples do not run

### ISSUE THREAD

**Issue by joranE** [paul-buerkner/brms#75]
I'm on OSX, R 3.3.0, brms 0.9.1 and the `plot.brmsfit` function appears broken. Running the examples under `?plot.brmsfit` yields:

    Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
      polygon edge not found

I have grid 3.3.0 and gridExtra 2.2.1 and gtable 0.2.0. Perhaps a change in gridExtra or gtable caused this?

**Comment by joranE** [comment]
Appears fixed in the development version from github...close if you like.

**Comment by paul-buerkner** [comment]
Hmm this is a weird error. I couldn't reproduce it with brms 0.9.1 and I am a bit confused that the error went away in the dev version of brms since I didn't change anything in the plot method after brms 0.9.0. Anyway, the error appears to have occured at deeper levels of grid, so I don't think it would fixable at my end anyway. Feel free to reopen this issue if it happens again.
