### ISSUE TITLE
Clarification on hurdle model

### ISSUE THREAD

**Issue by wfolta** [paul-buerkner/brms#78]
I may simply not be understanding how it works, but I wanted to try the negative binomial hurdle model to compare some results to a paper. In the paper, the outputs included the coefficients for both the negative binomial part of the model and also the hurdle model, separately. (By default, the same variables are used in each part, though you can specify different variables as well.)

My confusion is that `brm` presents one set of coefficients and I can't figure out how they relate to the paper's two sets of coefficients. The paper is using the `pscl` package's `hurdle`. Perhaps a few words in the documentation on how `brm`'s model/coefficients might correspond to `pscl`'s `hurdle`'s model/coefficients would be helpful for someone wanting to compare or move to `brms`.

Thanks for the great product, which only keeps on improving!

**Comment by paul-buerkner** [comment]
To specify hurdle and related models, brms uses what I call "multivariate" syntax (because it comes from packages implementing multivariate models). To force different sets of coefficients for the negbinomial and the hurdle part, you have 2 options.

1. Use the internally generated variable `trait` to specify all coefficients as part of both model parts:
```R
brm(y ~ 0 + trait + trait:(<your predictors>), ...)
```

2. Use the internally generated variables `main` and `spec` to specify different coefficients for different model parts

```R
brm(y ~ 0 + main + spec + main:(<predictors set 1>) + spec:(<predictor set 2>), ...)
```

Using neither option 1 or 2 effectively leads to pooled estimates between the two model parts, which doesn't make much sense (I geuss I should warn users when this happens). Some of the details are also explained in the "Details" section of `help(brm)`.

**Comment by wfolta** [comment]
Thanks! I missed the Details discussion. Thought I sort of had that down, but never used Hurdle so probably blanked it out of my mind. Didn't see it in the Vignette. I could imagine a warning message printing that the results are (or will be) pooled, which is probably not what the user really wants.

**Comment by paul-buerkner** [comment]
Great! I will leave this issue open until I implemented this warning message.

**Comment by paul-buerkner** [comment]
I have added the warning we were talking about. So I think this can be closed now.

**Comment by wfolta** [comment]
One more small item. I believe the Hurdle part of your model is modeling the probability of a zero, so you might want to note this. (This is the opposite of, say, `pscl`'s `hurdle` in which it is modeling the probability of being non-zero, and hence the signs are opposite.) Thanks!

**Comment by paul-buerkner** [comment]
Thanks! I will add this to the documentation.
