### ISSUE TITLE
Unable to perform GAM with adaptive smoothing

### ISSUE THREAD

**Issue by a-hurst** [paul-buerkner/brms#792]
I've been trying to figure out a good model for some data where the log-odds of a binary outcome changes smoothly over time with a curve-like shape (points are the means of bins across the data, for illustration): 

![Screen Shot 2019-11-19 at 6 28 53 PM](https://user-images.githubusercontent.com/18648066/69195711-763c8180-0afa-11ea-800d-d17315532079.png)

Apart from the continuous `trialnum` variable, I also have a single categorical predictor with three levels (different methods of measuring the same outcome variable), and I want to compare the rates/magnitudes of change over time. This seemed to me like a good use-case for a GAM, but with regular b-splines (`bs = "bs"`) or p-splines (`bs = "ps"`) the fit of the model is much more wiggly than I'd expect the actual latent variable to be.

In contrast, fitting the GAM with an adaptive smooth (`bs = "ad"`) fits my pilot data much more nicely, but brms chokes on the argument:

```r
fit <- brm(mw ~ s(trialnum, bs="ad", k=15), family = 'bernoulli', data=b)
```
```
Error in smooth2random.mgcv.smooth(sm, names(data), type = 2) :
  Can not convert this smooth class to a random effect
```

Based on a bit of digging, it looks like the problem might be that the "ad" smooth isn't supported for GAMMs according to the mcgv docs, and that brms appears to generate all GAMs as GAMMs behind the scenes (hence the random effect error despite my model not being multi-level). Would it be possible to add support for adaptive smooths to brms, or would that complicate matters too much on the back end? If the latter, are there any alternative approaches to a smoother GAM that are currently supported in brms?

Thanks in advance!

**Comment by paul-buerkner** [comment]
You are right that brms does not support those splines as long as mgcv does not support representing them as random effects. I currently don't have any plans to change the backend in order to support other kinds of smooth terms. It is just too painful. 

You can try to control the wiggliness of the splines by other means as described in the mgcv manual. 

In the future, please ask brms related questions on https://discourse.mc-stan.org/ (using the Interfaces - brms tag) unless you report a bug or have a feature request (which in your case you had in a way).
