### ISSUE TITLE
Support for smooths in multilevel syntax

### ISSUE THREAD

**Issue by StaffanBetner** [paul-buerkner/brms#812]
This is a suggestion that is a bit open on the details on the implementation, but it would be good if smooths could be used in the multilevel syntax, like this: 
```
y ~ s(x) + (s(x)|id)
```
I suppose that it will be the smoothness parameter (i.e. the standard deviation in the random effect formulation of smooths) that will be the parameter that is pooled.

The reason for this suggestion is that it is very unintuitive how to specify the most similar model with mgcv syntax. mgcv just supports the same smoothness or unpooled different smoothness for group-level smooths.

**Comment by paul-buerkner** [comment]
I agree though I have no clear idea how to implement that either. Perhaps by translating it to some mgcv smooths under the hood could be an option.

**Comment by StaffanBetner** [comment]
I am not sure how it fits with the random effect parameterization of smooths, but since the smooth is defined 
![image](https://user-images.githubusercontent.com/8129424/81076144-96ff6480-8eeb-11ea-8b63-e7fe9d48e71c.png) then the betas could be the pooled parameters. Similiar to how poly(..., degree) works in the multilevel syntax.

**Comment by paul-buerkner** [comment]
Thanks for the suggestion. Do you have a reference where this is advocated? hierarchical smooths are already supported in brms via s(..., bs = "fs") so the question is if this additional syntax would be necessary actually? No matter how exactly it would be implemented, the coding effort would be large without any big benefit in comparison to factor-smooths ("fs") terms.

**Comment by StaffanBetner** [comment]
I am a bit unsure whether what I propose are the same as factor-smooths or not, but I think it might. The reason for suggesting smooths in the multilevel syntax is that the "re" (bs=c("cr", "re")) or "fs" (they should be the same) syntax is very cumbersome for more complex structures. It arises some concerns though, as it is not clear whether it provides any benefit to the model to allow the betas in the basis decomposition to covary with other covariates, which would be a common side effect for a (s(x)+x2|group) syntax.

**Comment by paul-buerkner** [comment]
I do see your point. However, I don't think we will ever get to interact s() with the group syntax of brms. The reason is that everything related to splines via s() is handled by mgcv, which is a good thing because brms doesn't need to worry about a lot of the difficult stuff. However, this makes it almost impossible to combine s() with group syntax because it would require messing with the internals of mgcv, which (even if reasonably possible) would not be worth the effort or maintenance burden.

What we can do though is using splines genenerated by the splines or splines2 packages. They should work just like poly() in that the are naturally compatible with group syntax and thus already possible in brms. 

For the above reasons, I think the issue can safely be closed. Feel free to reopen it, if splines generated by the splines or splines2 package not work in the expected way with group syntax.
