### ISSUE TITLE
Setting upper/lower bounds separately for each covariate

### ISSUE THREAD

**Issue by alireza202** [paul-buerkner/brms#86]
I tried doing:

```
priors = c(set_prior('normal(0, 10)', class = 'b', coef = 'x', ub = 0),
           set_prior('normal(0, 10)', class = 'b', coef = 'y', ub = 3))
```
where `x` and `y` are two covariates, but I got the error:

```
'coef' may not be specified when using boundaries
```
Is there really noway to do this?

**Comment by paul-buerkner** [comment]
There is a way, but it is slightly arkward and it will only work when the covariates you put boundaries on are continuous (doing this with categorical predictors may end in having unidentified models due to multiple intercepts). Let's say `z` is your response and `x` and `y` are the covariates.

```R
priors = c(set_prior('normal(0, 10)', class = 'b', ub = 0, nlpar = 'etax'),
           set_prior('normal(0, 10)', class = 'b', ub = 3, nlpar = 'etay'),
           set_prior('normal(0, 100)', class = 'b', nlpar = 'rest'))
model = brm(z ~ rest + etax + etay, <data, family etc.>, 
            nonlinear = list(rest ~ <other predictors>, 
                             etax ~ 0 + x, etay ~ 0 + y),
            prior = priors)
  
```

**Comment by alireza202** [comment]
Thanks!

Also I was wondering, if I have `z ~ x + y + x | item`, can I put an upper bound for the combined estimated value of 'population-level' and 'group-level'? Say I put an upper bound on the population-level effect of coefficient `x` to be `ub = 0`. But the group-level effect can be still larger than zero.

**Comment by paul-buerkner** [comment]
Currently it is not possible to do this, and I wonder in which situtation this is scientifically reasonable. Do you mind explaining in which context you want to apply that?

**Comment by alireza202** [comment]
Well in my case, we expect to see a decay behavior for all items, and not a growth behavior, but they all might have different decay behaviors...

**Comment by paul-buerkner** [comment]
I see. Are you only _expecting_ a decay behavior or are you sure that there must be one (because of some law of nature or similar)? Could it be that there is a growth im some cases even though it might be unlikely? If so, I wouldn't put any hard boundary on the parameters (neither on the fixed nor on the random effects). Because you are actually making it impossible to detect a growth behavior this way. If there is only decay behavior, your model will tell you and if there is some growth, your model will tell you too. But forcing it to be smaller 0 might make your model invalid as it cannot tell you anything anymore about the direction.

If you strongly believe in a decay behavior, than why not putting an informative prior on the respective fixed effect that has most of it's propability for negative values.

**Comment by paul-buerkner** [comment]
@alireza202 I currently don't see a way to put boundaries on group-level effects, despite the fact that I am sceptical about it's practical use. Accordingly, I will close this issue.

**Comment by jgabry** [comment]
Even if you did have an easy way of implementing this I think it's probably better to _not_ make it easy for people to do it. Maybe there are some rare cases when it would be ok, but it's definitely not advisable in general (and, as you say, informative priors is pretty much always a better option). If it's easy to do people will do it, so maybe best to avoid altogether.

**Comment by paul-buerkner** [comment]
Thanks for your insights @jgabry!

**Comment by alireza202** [comment]
I understand that in general, this is not a good idea. But in my problem, I have cases where the item is showing a behavior that is logically impossible, and the reason is that there are variables that I can't take into account, and I don't know about, and these result in the illogical behavior that I see. 

One strategy to deal with these is to remove that item's specific random effect variable (in the above example, `z ~ x + y + x | item` the random effect `x`) and only use the fixed effect for it. Note that I don't want to remove random effect for the intercept, but just the covariate. 

I know this is very specific, and you probably don't want to implement it, but if I can make a hack myself, it would be great. Any pointers on how to do this? Would it make sense to identify these items after the fit, and run a separate `predict` function with a modified `re.formula`, for example `re.formula = ~ 1 | item`?

**Comment by paul-buerkner** [comment]
In principle, you can use the Stan code generated by **brms** as a template and amend it a bit. You can create the Stan code of the model via `make_stancode` or access it via `stancode` if you already have fitted your model. There you will see some `z_<number>` parameters which form the basis of the group-level effects. You have to split them up into multiple parameter vectors so that you can assign lower bound just for the group-level-effect of x. For instance `vector<upper=0>[N_1] z_1_2;` in the parameters block. Let me say again that I don't think you should do that as you are effectively putting half normal priors on the group-level effects and I don't know about the implications for the model.

You can also use the option with `re_formula`. Keep in mind though that you effectively exclude the group-level uncertainty in the in x for this items in this case.

**Comment by alireza202** [comment]
Thanks Paul. I think I'll go with the second option for now.
