### ISSUE TITLE
false alarms when  save_all_pars = TRUE and there is a random effect correlation

### ISSUE THREAD

**Issue by bnicenboim** [paul-buerkner/brms#864]
I create fake data here for demonstrating the problem:
```
library(dplyr)
library(brms)
data <- tibble(x= rnorm(1000), y = rnorm(1000), z = rnorm(1000), g =rep(1:10,100))
```
This model works with no problems

```
fit_works <- brm(y ~ x + (x|g), data= data, control = list(adapt_delta =.9)) 
```

This one works but throws warnings

```
fit_fails <- brm(y ~ x + (x|g), data= data,
                 save_all_pars = TRUE,
                 control = list(adapt_delta =.9)) 

# Warning messages:
#   1: The largest R-hat is NA, indicating chains have not mixed.
# Running the chains for more iterations may help. See
# http://mc-stan.org/misc/warnings.html#r-hat 
# 2: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
# Running the chains for more iterations may help. See
# http://mc-stan.org/misc/warnings.html#bulk-ess 
# 3: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
# Running the chains for more iterations may help. See
# http://mc-stan.org/misc/warnings.html#tail-ess 
```

Funnily enough, I opened a similar bug in the past #392 ! (updated)

**Comment by paul-buerkner** [comment]
Thanks for opening this issue.

The warnings are issued by rstan not by brms but I managed to get rid of them from the brms side. I wouldn't call this a bug really since rstan is right that those things occur. brms summary is not specifically prepared to 'save_all_pars' so there may be more models where such kinds of warnings will occur as additionally stored parameters are not always removed from all summary computation (although they won't appear in the output).

I am not sure if you linked to the right old issue.

**Comment by bnicenboim** [comment]
I fixed the old issue id. Thanks for taking care of this on your side. I'll also open an issue in rstan (soon).
