### ISSUE TITLE
priors for grouping vars

### ISSUE THREAD

**Issue by davidfoxcroft** [paul-buerkner/brms#870]
Hi, in the latest version (2.12.4) is there ? glitch in the created stancode for group priors:

e.g 

`target += std_normal_lpdf(z_1[1]);`

 whereas it should be something like: 
 
 `(z_1[1] | 0,1) `

**Comment by paul-buerkner** [comment]
Std_normal is normal(0, 1)

davidfoxcroft <notifications@github.com> schrieb am Di., 31. März 2020,
17:26:

**Comment by paul-buerkner** [comment]
Perhaps your cmdstan is outdated.

davidfoxcroft <notifications@github.com> schrieb am Di., 31. März 2020,
18:00:

**Comment by davidfoxcroft** [comment]
I'm on version v2.22.1 (Jan 31 2020).

**Comment by davidfoxcroft** [comment]
I've seen this is already raised as an issue for cmdstan:

[https://github.com/stan-dev/stanc3/issues/393](url)

Please go ahead and close this. Thanks for your help today - much appreciated.

**Comment by paul-buerkner** [comment]
Ok. Good to know

**Comment by jgabry** [comment]
Yeah this is a stanc3 bug, but unfortunately I don't think it has been fixed yet (it looks like that issue https://github.com/stan-dev/stanc3/issues/393 is still open). This can still be run in cmdstan but you'd need to tell it to use stanc2 instead of stanc3. In cmdstanr that can be done by specifying `cpp_options = list("STANC2"=TRUE)` when compiling. 

Note: if you try that then don't be alarmed if the first time it takes a long time to compile because it will need to build stanc2. After the first time it will only need to compile the stan code and not stanc2 itself.

**Comment by jgabry** [comment]
To follow up, here's how you could do it in cmdstanr: 

```r
stan_program <- tempfile(fileext=".stan") # doesn't have to be a temp file
cat(make_stancode(...), file = stan_program) 
mod <- cmdstan_model(stan_program, cpp_options = list("STANC2"=TRUE))
fit <- mod$sample(...)
```
