### ISSUE TITLE
Calling update() on brm object

### ISSUE THREAD

**Issue by ajpag** [paul-buerkner/brms#889]
When calling ```update()``` on a brm object to change arguments, some of the pre-specified arguments in the original object do not carry over, specifically ```open_progress``` and ```refresh``` (there may be more, but have not done a full check). My understanding is that ```update()``` is only supposed to change arguments if you explicitly call them within ```update()``` , e.g. ```sample_prior```.

Is this behavior expected?

**Comment by paul-buerkner** [comment]
The arguments you name are direclty passed to (r)stan withut brms being involved it that. So, unless they are stored inside the stanfit object (which I doubt but do not know for sure), there is no way to update them because they are not known anymore at updating time. I don't want to store them manually inside the brms argument as they do not affect the model itself but rather how its fitting process is displayed. So you may likel need to pass them again every time you call `update`.

**Comment by ajpag** [comment]
Ok this makes sense. Thank you.
