### ISSUE TITLE
brms non linear regression: prior restrictions also apply to regression coefficients

### ISSUE THREAD

**Issue by Kreile** [paul-buerkner/brms#908]
Hi there
Not sure if this is an issue, but when using non linear models with _nl = TRUE_ and _prior(lb = x, nlpar = b)_,
then some regression parameter _c_ in _b ~ 1 + c*x_
is not allowed to have negative values as well. We almost got bitten by this as we were insecure about our covariable _x_ maybe having a negative effect on _b_.
If this was intended so then never mind, but might be worthwhile mentioning in the documentation or also on the example on GitHub.

Cheers
Giuachin

**Comment by paul-buerkner** [comment]
Since you did not specify the `class` argument in `prior(lb = x, nlpar = b)`, it will apply to fixed effects by default. Since non-linear parameters in brms (`b` in your case) are just placeholders for linear predictors, there is no prior that will directly apply to `b` itself. If you want to transform `b` as whole so that it is positive only, you can, for example, model it on the log scale.

**Comment by Kreile** [comment]
Just to clarify, so if I set prior(nlpar = b, class = Intercept), then it is the prior on the intercept
b right? Just because you are saying there is no prior that applies directly to b

**Comment by Kreile** [comment]
I should have added that I used a separate prior for b: prior(nlpar = b, class = b, coef = x)

**Comment by paul-buerkner** [comment]
Yes. You can check what parameters can have priors via `get_prior`.
