### ISSUE TITLE
Problem with beta_binomial2 custom family?

### ISSUE THREAD

**Issue by andymilne** [paul-buerkner/brms#927]
I am sure this used to work, but doesn't any longer:

```
beta_binomial2 <- 
  custom_family(
    "beta_binomial2", dpars = c("mu", "phi"),
    links = c("logit", "log"), lb = c(NA, 0),
    type = "int", vars = "trials[n]"
  )

stan_funs <- "
  real beta_binomial2_lpmf(int y, real mu, real phi, int T) {
    return beta_binomial_lpmf(y | T, mu * phi, (1 - mu) * phi);
  }
  int beta_binomial2_rng(real mu, real phi, int T) {
    return beta_binomial_rng(T, mu * phi, (1 - mu) * phi);
  }
"

stanvars <- 
  stanvar(scode = stan_funs, block = "functions")

expose_functions(fit2, vectorize = TRUE)
```

Running any model (in brms 2.13.0) with `family = beta_binomial2`, I get the error message
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
No matches for: 

  beta_binomial2_lpmf(int, real, real, int)

Function beta_binomial2_lpmf not found.
 error in 'model143153ec877a_file143158a00f6d' at line 92, column 65
  -------------------------------------------------
    90:   if (!prior_only) {
    91:     for (n in 1:N) {
    92:       target += beta_binomial2_lpmf(Y[n] | mu[n], phi, trials[n]);
                                                                        ^
    93:     }
  -------------------------------------------------

Error in stanc(model_code = paste(program, collapse = "\n"), model_name = model_cppname,  : 
  failed to parse Stan model 'file143158a00f6d' due to the above error.
```

**Comment by paul-buerkner** [comment]
Thank you for reporting this issue. I can run the code in the custom families vignette without issues though.

Your above code is not reproducible, as `fit2` is undefined. Can you please provide a minimally reproducible example? Also, what version of brms and Stan are you using?

**Comment by MilaniC** [comment]
try:

type_ = "int", vars = "vint1[n]" )

rather than

type = "int",  vars = "trials[n]" )

**Comment by MilaniC** [comment]
and then of course in the model:

alive|vint(N)

**Comment by paul-buerkner** [comment]
Can you please provide the full code that creates the error not just
snippets? The chance I copy them together incorrectly in some subtle way is
too high otherwise.

Milani <notifications@github.com> schrieb am So., 14. Juni 2020, 02:44:

**Comment by MilaniC** [comment]
@paul-buerkner 

the OP @andymilne uses ...

`beta_binomial2 <- custom_family( 
       "beta_binomial2", dpars = c("mu", "phi"), 
       links = c("logit", "log"), lb = c(NA, 0), 
       type = "int", vars = "trials[n]" )`

but it should be (and is in the most recent vignette but not in older vignette) ...

`beta_binomial2 <- custom_family( 
       "beta_binomial2", dpars = c("mu", "phi"), 
       links = c("logit", "log"), lb = c(NA, 0), 
       type = "int", vars = "vint1[n]" )`

and then for example in the model itself need to ...

`brm(alive|vint(clutch)~..... +  ## "vint()" now instead of "alive|trails(clutch)" `

Your original vignette referred to "trail" but your latest vignette refers to "vint1"

**Comment by MilaniC** [comment]
Fixing a typo ...

@paul-buerkner

the OP @andymilne uses ...

`beta_binomial2 <- custom_family( "beta_binomial2", dpars = c("mu", "phi"), links = c("logit", "log"), lb = c(NA, 0), type = "int", vars = "trials[n]" )`

but it should be (and is in the most recent vignette but not in older vignette) ...

`beta_binomial2 <- custom_family( "beta_binomial2", dpars = c("mu", "phi"), links = c("logit", "log"), lb = c(NA, 0), type = "int", vars = "vint1[n]" )`

and then for example in the model itself need to ...

brm(alive|vint(clutch)~..... + ## "vint()" now instead of "alive|trials(clutch)"

Your original vignette referred to "trials" but your latest vignette refers to "vint1"

**Comment by paul-buerkner** [comment]
Thanks! I think I get it now (and I thought you were the OP at first in my tired mind).

**Comment by paul-buerkner** [comment]
Even with `trials` instead of `vint` it works for me with the code

```R
library(brms)
data("cbpp", package = "lme4")

beta_binomial2 <- custom_family(
  "beta_binomial2", dpars = c("mu", "phi"),
  links = c("logit", "log"), lb = c(NA, 0),
  type = "int", vars = "trials[n]"
)

stan_funs <- "
  real beta_binomial2_lpmf(int y, real mu, real phi, int T) {
    return beta_binomial_lpmf(y | T, mu * phi, (1 - mu) * phi);
  }
  int beta_binomial2_rng(real mu, real phi, int T) {
    return beta_binomial_rng(T, mu * phi, (1 - mu) * phi);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions")

fit2 <- brm(
  incidence | trials(size) ~ period + (1|herd), data = cbpp, 
  family = beta_binomial2, stanvars = stanvars
)
```

so I am really lost when it comes to reproducing the issue at least with brms >= 2.13.0

**Comment by MilaniC** [comment]
Like the OP @andymilne it fails for me using the code you had in the older vignette. It works with the changes I highlight from your most recent vignette.

**Comment by andymilne** [comment]
I had failed to include the `stanvars = stanvars` argument in `brm()`. It works now -- sorry for wasting everyone's time.

**Comment by paul-buerkner** [comment]
Thank you! Next time, please provide a fully reproducible example right away as I will be able to see problems much faster this way.
