### ISSUE TITLE
Interval-Censored Response Variables

### ISSUE THREAD

**Issue by rtaph** [paul-buerkner/brms#93]
Hi Paul,

Thanks for the great package.

Is there a way of specifying an interval-censored response variable? That is, a dependent variable that is both left-censored and right-censored?

Thanks,

**Comment by paul-buerkner** [comment]
Hi Raphael,

I am afraid it is not yet possible, but I will try to implement this. Currently, my main concern is a syntactical one. When we only have left and right censoring, the current syntax `y | cens(censored)` works well. `y` contains the (possibly) censored response and `censored` indicates whether it is left, right, or not censored. However, I am not yet sure how to best specify interval censoring in this framwork, because we essentially need 2 `y` values. One for the upper and one for the lower bound. Do you have an idea on how the syntax for interval censoring should look like?

**Comment by rtaph** [comment]
Hi Paul,

I have come across three ways of specifying this syntax:


##### Approach 1: Wrapper Function
Pass-in a "censored response" object via a specialized function.
```
m1a <- survreg(Surv(lwr, upr, type = "interval2") ~ x,  data = df, dist = "weibull")
m1b <- survreg(Surv(lwr, upr, status, type = "interval") ~ x,  data = df, dist = "weibull")
```

##### Approach 2: Matrix
Pass a _n_ x 2 matrix as the response.
```
m2 <- MCMCglmm(cbind(lwr, upr) ~ x + (1 | z), family = "cenpoisson", data = df)
m3 <- icenReg::ic_par(cbind(lwr, upr) ~ x, data = df, model = "po", dist = "gamma")
```
##### Approach 3: Additional Formals
Specify the bounds as arguments in the function call.
```
m3 <- SMNCensReg::CensReg.SMN(status, y = lwr, LS = upr, x = x, cens = "interval")
```

The most popular packages for interval regressions specify both the upper and lower bounds on the left-hand side of the tilde. I like the wrapper approach with `Surv` because it makes the nature of the response explicit. This could be important for a package like `brms` where there is a lot of flexibility in specifying many models. In contrast, the matrix implementation in packages like MCMCglmm relies on the family argument to figure out how to handle the response. And other packages like `icenreg` are written specifically and only to handle censored models, and so expect a censored `y`.


One aspect that seems more elegant in matrix approach is that the type of censoring is specified using only the lower and upper bounds (no need of a status/type variable). For example, a left-censored observation can be `c(-Inf, b)`, a doubly-censored observation can be `c(a, b)`, and an observation with no censoring can be `c(a, a)`. This could work with the wrapper approach too, as is the case with survreg where `cens = interval2`.

Lastly, the `Surv` object forces users to define intervals as open on the left and closed on the right (a, b]. I imagine this is a design choice that leads to more simplicity and stability.

Cheers,

**Comment by paul-buerkner** [comment]
Many thanks for the detailed suggestions! I will take a look at all of them and see what is the best option for brms.

**Comment by pistacliffcho** [comment]
Just a comment: `icenReg` originally only used the `Surv(l, r, type = "interval2") ~...` formula syntax. I added the `cbind(l, r) ~ ...` option because it became *really* annoying to type out the full `Surv(l, r, type = "interval2")` each time I wanted to fit a model. 

But as rtaph noted, in your package you may want to make it more explicit to the user that they are fitting an interval censored model. In `icenReg`, this is your only option, so there's no question. If you really wanted, you could just make a wrapper function around `cbind` called `intCen` or something of the sort.

**Comment by paul-buerkner** [comment]
Interval censoring is now implemented. In the doc I write

> With the expection of categorical and ordinal families, left, right, and interval censoring can be modeled through y | cens(censored) ~ predictors. The censoring variable (named censored in this example) should contain the values 'left', 'none', 'right', and 'interval' (or equivalenty -1, 0, 1, and 2) to indicate that the corresponding observation is left censored, not censored, right censored, or interval censored. For interval censored data, a second variable (let's call it y2) has to be passed to cens. In this case, the formula has the structure y | cens(censored, y2) ~ predictors. While the lower bounds are given in y, the upper bounds are given in y2 for interval censored data. Intervals are assumed to be open on the left and closed on the right: (y, y2].

I chose to use this syntax as it nicely fits into the existing formula syntax of **brms** and  is similar to how it is done in `Surv`.
