### ISSUE TITLE
Complement or extend the bridgesampling package with the new BFpack

### ISSUE THREAD

**Issue by TarandeepKang** [paul-buerkner/brms#951]
Hi Paul,

I just came across this new package as described in this preprint: https://arxiv.org/abs/1911.07728 

To me at least, it looks more flexible and versatile than bridgesampling, you may of course disagree! 

Apologies if you already know about this, or if I'm on the wrong track, I am rather new to this! 

Thanks for all the great work!

**Comment by paul-buerkner** [comment]
Thanks. The BFpack package seems to provide standalone functions for computing Bayes factors for specific models, rather than a general purpose algorithm to compute Bayes factors based on models fitted with other software (e.g., Stan). I thus don't see how this could be combined with brms functionality but I am happy to convinced otherwise.
