### ISSUE TITLE
Error: Family 'cox' requires response greater than 0

### ISSUE THREAD

**Issue by proshano** [paul-buerkner/brms#964]
In trying to simulate some survival data to test out the brms Cox call, I get the above error. Here is some reproducible code:

library(brms)
library(simsurv)
library(survival)
set.seed(1234)

covs <- data.frame(id  = 1:10000, trt = stats::rbinom(200, 1L, 0.5))
d2 <- simsurv(lambdas = 0.02,
              gammas  = .1,
              betas   = c(trt = -0.5),
              x       = covs,
              maxt    = 30)
d2$eventtime <-floor(d2$eventtime)
d2 <- merge(d2, covs)
d2$censored<- 1-d2$status
d2

fit_coxph <- coxph(Surv(eventtime, status) ~ trt, data = d2)
summary(fit_coxph)

fit_brm <- brm(eventtime | cens(censored) ~ 1 + trt, 
               data = d2, family = brmsfamily("cox"))

**Comment by paul-buerkner** [comment]
The problem is that your model contains survival times which are exactly zero because of `floor(d2$eventtime)`. Not sure if they are reasonable. 

Anyway, with the latest github version of brms, you can now try to fit the model with a little bit of manual work:

```R
cox_fam <- brmsfamily("cox", bhaz = list(Boundary.knots = c(-1, 31)))
fit_brm <- brm(eventtime | cens(censored) ~ 1 + trt,
               data = d2, family = cox_fam)
```

where the boundary knots are tuned your time-to-event data at hand (min = 0, max = 30). 

Note that the cox family is not officially supported and may be changed at any time.

**Comment by proshano** [comment]
brilliant thank you so much!
