### ISSUE TITLE
Attaching warning messages to model output

### ISSUE THREAD

**Issue by hoangtt1989** [paul-buerkner/brms#97]
Sometimes when I run a model from `brm`, a warning message about divergent transitions or large Rhat values will appear suggesting that the model has not converged. I'm currently using a script that runs a large number of models (about 200) and it would be convenient if I could directly access any warning messages that are currently just output to the console or appended to `summary(my_model)`. Is there any way to do this, for example `my_model$fit$warning`?

**Comment by paul-buerkner** [comment]
These warnings are not actually generated by brms but by (R)Stan. the `.$fit` part of a `brmsfit` object is the `stanfit` object which cannot easily has it's structure changed due to being and S4 object.  However, it already contains information on the number of divergent transitions.  You can access them via the following helper function:

```R
n_divergent <- function(x) {
  stopifnot(is(x, "brmsfit"))
  out <- lapply(x$fit@sim$samples, function(y) 
    sum(attr(y, "sampler_params")[["divergent__"]]))
  sum(unlist(out))
}
```

**Comment by paul-buerkner** [comment]
@hoangtt1989 Did this solve your question?

**Comment by hoangtt1989** [comment]
It did, thank you!
